import wx # for wx.Colour values

Origins = ['Magic','Mutation','Natural','Science','Technology']

Archetypes = {
    "Arachnos Soldier": {
        'Faction': 'V',
        "Epic": {
            "Mace Mastery": [
                "Mace Blast",
                "Web Envelope",
                "Disruptor Blast",
                "Summon Blaster",
            ],
            "Leviathan Mastery": [
                "Spirit Shark",
                "School of Sharks",
                "Chum Spray",
                "Summon Guardian",
            ],
            "Soul Mastery": [
                "Dark Obliteration",
                "Gloom",
                "Soul Tentacles",
                "Summon Widow",
            ],
            "Mu Mastery": [
                "Mu Lightning",
                "Electrifying Fences",
                "Ball Lightning",
                "Summon Striker",
            ],
        },
        "Primary": {
            "Arachnos Soldier": [
                "Single Shot",
                "Pummel",
                "Burst",
                "Wide Area Web Grenade",
                "Heavy Burst",
                "Bayonet",
                "Venom Grenade",
                "Frag Grenade",
            ],
            "Crab Spider Soldier":[
                "Channelgun",
                "Slice",
                "Longfang",
                "Aim",
                "Suppression",
                "Arm Lash",
                "Venom Grenade",
                "Frag Grenade",
                "Frenzy",
                "Omega Maneuver",
            ],
            "Bane Spider Soldier": [
                "Bash",
                "Mace Beam",
                "Mace Beam Blast",
                "Build Up",
                "Mace Beam Volley",
                "Poisonous Ray",
                "Pulverize",
                "Shatter",
                "Placate",
                "Crowd Control",
            ],
        },
        "Secondary": {
            "Training and Gadgets": [
                "Tactical Training: Maneuvers",
                "Tactical Training: Assault",
                "Tactical Training: Leadership",
                "Call Reinforcements",
            ],
            "Crab Spider Training": [
                "Fortification",
                "Summon Spiderlings",
            ],
            "Bane Spider Training": [
                "Cloaking Device",
                "Surveillance",
                "Web Cocoon",
            ],
        },
    },
    "Arachnos Widow": {
        'Faction': 'V',
        "Epic": {
            "Mace Mastery": [
                "Mace Blast",
                "Web Envelope",
                "Disruptor Blast",
                "Summon Blaster",
            ],
            "Leviathan Mastery": [
                "Spirit Shark",
                "School of Sharks",
                "Chum Spray",
                "Summon Guardian",
            ],
            "Soul Mastery": [
                "Dark Obliteration",
                "Gloom",
                "Soul Tentacles",
                "Summon Widow",
            ],
            "Mu Mastery": [
                "Mu Lightning",
                "Electrifying Fences",
                "Ball Lightning",
                "Summon Striker",
            ],
        },
        "Primary": {
            "Widow Training": [
                "Poison Dart",
                "Swipe",
                "Strike",
                "Dart Burst",
                "Follow Up",
                "Spin",
                "Lunge",
                "Confront",
            ],
            "Night Widow Training": [
                "Mental Blast",
                "Build Up",
                "Smoke Grenade",
                "Slash",
                "Eviscerate",
                "Psychic Scream",
            ],
            "Fortunata Training": [
                "Mental Blast",
                "Telekinetic Blast",
                "Subdue",
                "Aim",
                "Psychic Scream",
                "Dominate",
                "Psychic Tornado",
                "Scramble Thoughts",
                "Total Domination",
                "Psychic Wail",
            ],
        },
        "Secondary": {
            "Teamwork": [
                "Tactical Training: Maneuvers",
                "Indomitable Will",
                "Tactical Training: Assault",
                "Tactical Training: Leadership",
            ],
            "Widow Teamwork": [
                "Mask Presence",
                "Mind Link",
                "Placate",
                "Tactical Training: Vengeance",
                "Elude",
            ],
            "Fortunata Teamwork": [
                "Mask Presence",
                "Mind Link",
                "Confuse",
                "Tactical Training: Vengeance",
                "Aura Of Confusion",
            ],
        },
    },
    "Blaster": {
        'Faction': 'H',
        "Epic": {
            "Cold Mastery": [
                "Snow Storm",
                "Flash Freeze",
                "Frozen Armor",
                "Hibernate",
            ],
            "Electric Mastery": [
                "Charged Armor",
                "Static Discharge",
                "Shocking Bolt",
                "EMP Pulse",
            ],
            "Flame Mastery": [
                "Char",
                "Fire Shield",
                "Rise of the Phoenix",
                "Bonfire",
            ],
            "Force Mastery": [
                "Personal Force Field",
                "Repulsion Field",
                "Temp Invulnerability",
                "Force of Nature",
            ],
            "Munitions Mastery": [
                "Sleep Grenade",
                "LRM Missile",
                "Cryo Freeze Ray",
            ],
        },
        "Primary": {
            "Archery": [
                "Snap Shot",
                "Aimed Shot",
                "Fistful of Arrows",
                "Blazing Arrow",
                "Aim",
                "Ranged Shot",
                "Stunning Shot",
                "Rain of Arrows",
                "Explosive Arrow",
            ],
            "Assault Rifle": [
                "Burst",
                "Slug",
                "Buckshot",
                "M30 Grenade",
                "Beanbag",
                "Sniper Rifle",
                "Flamethrower",
                "Ignite",
                "Full Auto",
            ],
            "Dual Pistols": [
                "Pistols",
                "Dual Wield",
                "Empty Clips",
                "Swap Ammo",
                "Bullet Rain",
                "Suppressive Fire",
                "Executioner's Shot",
                "Piercing Rounds",
                "Hail of Bullets",
            ],
            "Electrical Blast": [
                "Charged Bolts",
                "Lightning Bolt",
                "Ball Lightning",
                "Short Circuit",
                "Aim",
                "Zapp",
                "Tesla Cage",
                "Voltaic Sentinel",
                "Thunderous Blast",
            ],
            "Energy Blast": [
                "Power Bolt",
                "Power Blast",
                "Energy Torrent",
                "Power Burst",
                "Sniper Blast",
                "Aim",
                "Power Push",
                "Explosive Blast",
                "Nova",
            ],
            "Fire Blast": [
                "Flares",
                "Fire Blast",
                "Fire Ball",
                "Rain Of Fire",
                "Fire Breath",
                "Aim",
                "Blaze",
                "Blazing Bolt",
                "Inferno",
            ],
            "Ice Blast": [
                "Ice Bolt",
                "Ice Blast",
                "Frost Breath",
                "Aim",
                "Freeze Ray",
                "Ice Storm",
                "Bitter Ice Blast",
                "Bitter Freeze Ray",
                "Blizzard",
            ],
            "Psychic Blast": [
                "Psionic Dart",
                "Mental Blast",
                "Telekinetic Blast",
                "Psychic Focus",
                "Will Domination",
                "Psionic Lance",
                "Psionic Tornado",
                "Scramble Thoughts",
                "Psychic Wall",
            ],
            "Radiation Blast": [
                "Neutrino Bolt",
                "X-Ray Beam",
                "Irradiate",
                "Electron Haze",
                "Aim",
                "Proton Volley",
                "Cosmic Burst",
                "Neutron Bomb",
                "Atomic Blast",
            ],
            "Sonic Attack": [
                "Shriek",
                "Scream",
                "Howl",
                "Shockwave",
                "Shout",
                "Amplify",
                "Siren's Song",
                "Screech",
                "Dreadful Wail",
            ],
        },
        "Secondary": {
            "Devices": [
                "Web Grenade",
                "Caltrops",
                "Taser",
                "Targeting Drone",
                "Smoke Grenade",
                "Cloaking Device",
                "Trip Mine",
                "Time Bomb",
                "Auto Turret",
            ],
            "Electricity Manipulation": [
                "Electric Fence",
                "Charged Brawl",
                "Lightning Field",
                "Havoc Punch",
                "Build Up",
                "Lightning Clap",
                "Thunder Strike",
                "Power Sink",
                "Shocking Grasp",
            ],
            "Energy Manipulation": [
                "Power Thrust",
                "Energy Punch",
                "Build Up",
                "Bone Smasher",
                "Conserve Power",
                "Stun",
                "Power Boost",
                "Boost Range",
                "Total Focus",
            ],
            "Fire Manipulation": [
                "Ring of Fire",
                "Fire Sword",
                "Combustion",
                "Fire Sword Circle",
                "Build Up",
                "Blazing Aura",
                "Consume",
                "Burn",
                "Hot Feet",
            ],
            "Ice Manipulation": [
                "Chilblain",
                "Frozen Fists",
                "Ice Sword",
                "Chilling Embrace",
                "Build Up",
                "Ice Patch",
                "Shiver",
                "Freezing Touch",
                "Frozen Aura",
            ],
            "Mental Manipulation": [
                "Subdual",
                "Mind Probe",
                "Telekinetic Thrust",
                "Psychic Scream",
                "Concentration",
                "Drain Psyche",
                "World of Confusion",
                "Scare",
                "Psychic Shockwave",
            ],
        },
    },
    'Brute': {
        'Faction': 'V',
        "Epic": {
            "Mace Mastery": [
                "Mace Blast",
                "Web Envelope",
                "Disruptor Blast",
                "Summon Blaster",
            ],
            "Leviathan Mastery": [
                "Spirit Shark",
                "School of Sharks",
                "Chum Spray",
                "Summon Guardian",
            ],
            "Soul Mastery": [
                "Dark Obliteration",
                "Gloom",
                "Soul Tentacles",
                "Summon Widow",
            ],
            "Mu Mastery": [
                "Mu Lightning",
                "Electrifying Fences",
                "Ball Lightning",
                "Summon Striker",
            ],
        },
        "Primary": {
            "Battle Axe": [
                "Beheader",
                "Chop",
                "Gash",
                "Build Up",
                "Swoop",
                "Taunt",
                "Whirling Axe",
                "Cleave",
                "Pendulum",
            ],
            "Claws": [
                "Swipe",
                "Strike",
                "Slash",
                "Spin",
                "Follow Up",
                "Taunt",
                "Focus",
                "Eviscerate",
                "Shockwave",
            ],
            "Dark Melee": [
                "Shadow Punch",
                "Smite",
                "Shadow Maul",
                "Touch of Fear",
                "Siphon Life",
                "Taunt",
                "Dark Consumption",
                "Soul Drain",
                "Midnight Grasp",
            ],
            "Dual Blades": [
                "Nimble Slash",
                "Power Slice",
                "Ablating Strike",
                "Typhoon's Edge",
                "Blinding Feint",
                "Taunt",
                "Vengeful Slice",
                "Sweeping Strike",
                "One Thousand Cuts",
            ],
            "Electric Melee": [
                "Charged Brawl",
                "Havoc Punch",
                "Jacobs Ladder",
                "Build Up",
                "Thunder Strike",
                "Taunt",
                "Chain Induction",
                "Lighning Clap",
                "Lightning Rod",
            ],
            "Energy Melee": [
                "Barrage",
                "Energy Punch",
                "Bone Smasher",
                "Build Up",
                "Whirling Hands",
                "Taunt",
                "Total Focus",
                "Stun",
                "Energy Transfer",
            ],
            "Fiery Melee": [
                "Scorch",
                "Fire Sword",
                "Cremate",
                "Build Up",
                "Incinerate",
                "Taunt",
                "Breath of Fire",
                "Fire Sword Circle",
                "Greater Fire Sword",
            ],
            "Stone Melee": [
                "Stone Fist",
                "Stone Mallet",
                "Heavy Mallet",
                "Build Up",
                "Fault",
                "Taunt",
                "Seismic Smash",
                "Hurl Boulder",
                "Tremor",
            ],
            "Super Strength": [
                "Jab",
                "Punch",
                "Haymaker",
                "Hand Clap",
                "Knockout Blow",
                "Taunt",
                "Rage",
                "Hurl",
                "Foot Stomp",
            ],
            "War Mace": [
                "Bash",
                "Pulverize",
                "Jawbreaker",
                "Build Up",
                "Clobber",
                "Taunt",
                "Whirling Mace",
                "Shatter",
                "Crowd Control",
            ],
        },
        "Secondary": {
            "Dark Armor": [
                "Dark Embrace",
                "Death Shroud",
                "Murky Cloud",
                "Obsidian Shield",
                "Dark Regeneration",
                "Cloak Of Darkness",
                "Cloak Of Fear",
                "Oppressive Gloom",
                "Soul Transfer",
            ],
            "Electric Armor": [
                "Charged Armor",
                "Lightning Field",
                "Conductive Shield",
                "Static Shield",
                "Conserve Power",
                "Power Sink",
                "Prestige Power Surge ",
            ],
            "Energy Aura": [
                "Kinetic Shield",
                "Power Shield",
                "Entropy Shield",
                "Energy Cloak",
                "Energy Drain",
                "Conserve Power",
                "Overload",
            ],
            "Fiery Aura": [
                "Fire Shield",
                "Blazing Aura",
                "Healing Flames",
                "Plasma Shield",
                "Consume",
                "Burn",
                "Fiery Embrace",
                "Rise of the Phoenix",
            ],
            "Invulnerability": [
                "Temp Invulnerability",
                "Dull Pain",
                "Unyielding",
                "Invincibility",
                "Unstoppable",
            ],
            "Stone Armor": [
                "Rock Armor",
                "Earth's Embrace",
                "Mud Pots",
                "Rooted",
                "Brimstone Armor",
                "Crystal Armor",
                "Minerals",
                "Granite Armor",
            ],
            "Super Reflexes": [
                "Focused Fighting",
                "Focused Senses",
                "Practiced Brawler",
                "Evasion",
                "Elude",
            ],
            "Willpower": [
                "Mind Over Body",
                "Indomitable Will",
                "Rise To The Challenge",
                "Heightened Senses",
                "Resurgence",
                "Strength of Will",
            ],
        },
    },
    'Controller': {
        'Faction': 'H',
        "Epic": {
            "Fire Mastery": [
                "Fire Blast",
                "Fire Ball",
                "Fire Shield",
                "Consume",
            ],
            "Ice Mastery": [
                "Ice Blast",
                "Hibernate",
                "Frozen Armor",
                "Ice Storm",
            ],
            "Primal Forces Mastery": [
                "Power Blast",
                "Conserve Power",
                "Temp Invulnerability",
                "Power Boost",
            ],
            "Psionic Mastery": [
                "Mental Blast",
                "Indomitable Will",
                "Mind Over Body",
                "Psionic Tornado",
            ],
            "Stone Mastery": [
                "Hurl Boulder",
                "Fissure",
                "Rock Armor",
                "Earth's Embrace",
            ],
        },
        "Primary": {
            "Earth Control": [
                "Stone Prison",
                "Fossilize",
                "Stone Cages",
                "Quicksand",
                "Salt Crystals",
                "Stalagmites",
                "Earthquake",
                "Volcanic Gasses",
                "Animate Stone",
            ],
            "Fire Control": [
                "Ring of Fire",
                "Char",
                "Fire Cages",
                "Smoke",
                "Hot Feet",
                "Flashfire",
                "Cinders",
                "Bonfire",
                "Fire Imps",
            ],
            "Gravity Control": [
                "Crush",
                "Lift",
                "Gravity Distortion",
                "Propel",
                "Crushing Field",
                "Dimension Shift",
                "Gravity Distortion Field",
                "Wormhole",
                "Singularity",
            ],
            "Ice Control": [
                "Chilblain",
                "Block of Ice",
                "Frostbite",
                "Arctic Air",
                "Shiver",
                "Ice Slick",
                "Flash Freeze",
                "Glacier",
                "Jack Frost",
            ],
            "Illusion Control": [
                "Spectral Wounds",
                "Blind",
                "Deceive",
                "Flash",
                "Superior Invisibility",
                "Group Invisibility",
                "Phantom Army",
                "Spectral Terror",
                "Phantasm",
            ],
            "Mind Control": [
                "Mesmerize",
                "Levitate",
                "Dominate",
                "Confuse",
                "Mass Hypnosis",
                "Telekinesis",
                "Total Domination",
                "Terrify",
                "Mass Confusion",
            ],
            "Plant Control": [
                "Entangle",
                "Strangler",
                "Roots",
                "Spore Burst",
                "Seeds of Confusion",
                "Spirit Tree",
                "Vines",
                "Carrion Creepers",
                "Fly Trap",
            ],
        },
        "Secondary": {
            "Cold Domination": [
                "Infrigidate",
                "Ice Shield",
                "Snow Storm",
                "Glacial Shield",
                "Frostwork",
                "Arctic Fog",
                "Benumb",
                "Sleet",
                "Heat Loss",
            ],
            "Empathy": [
                "Healing Aura",
                "Heal Other",
                "Absorb Pain",
                "Resurrect",
                "Clear Mind",
                "Fortitude",
                "Recovery Aura",
                "Adrenalin Boost",
                "Regeneration Aura",
            ],
            "Force Field": [
                "Personal Force Field",
                "Deflection Shield",
                "Force Bolt",
                "Insulation Shield",
                "Detention Field",
                "Dispersion Bubble",
                "Repulsion Field",
                "Repulsion Bomb",
                "Force Bubble",
            ],
            "Kinetics": [
                "Transfusion",
                "Siphon Power",
                "Repel",
                "Siphon Speed",
                "Increase Density",
                "Speed Boost",
                "Inertial Reduction",
                "Transference",
                "Fulcrum Shift",
            ],
            "Radiation Emission": [
                "Radiant Aura",
                "Radiation Infection",
                "Accelerate Metabolism",
                "Enervating Field",
                "Mutation",
                "Lingering Radiation",
                "Choking Cloud",
                "Fallout",
                "EM Pulse",
            ],
            "Sonic Resonance": [
                "Clarity",
                "Disruption Field",
                "Sonic Barrier",
                "Sonic Cage",
                "Sonic Dispersion",
                "Sonic Haven",
                "Sonic Repulsion",
                "Sonic Siphon",
                "Liquefy",
            ],
            "Storm Summoning": [
                "Gale",
                "O2 Boost",
                "Snow Storm",
                "Steamy Mist",
                "Freezing Rain",
                "Hurricane",
                "Thunder Clap",
                "Tornado",
                "Lightning Storm",
            ],
            "Thermal Radiation": [
                "Warmth",
                "Fire Shield",
                "Cauterize",
                "Plasma Shield",
                "Power of the Phoenix",
                "Thaw",
                "Forge",
                "Heat Exhaustion",
                "Melt Armor",
            ],
            "Trick Arrow": [
                "Acid Arrow",
                "Ice Arrow",
                "Entangling Arrow",
                "Disruption Arrow",
                "EM Pulse Arrow",
                "Flash Arrow",
                "Glue Arrow",
                "Oil Slick Arrow",
                "Poison Gas Arrow",
            ],
        },
    },
    'Corruptor': {
        'Faction': 'V',
        "Epic": {
            "Mace Mastery": [
                "Web Envelope",
                "Scorpion Shield",
                "Web Cocoon",
                "Summon Disruptor",
            ],
            "Leviathan Mastery": [
                "Spirit Shark Jaws",
                "School of Sharks",
                "Summon Coralax",
            ],
            "Soul Mastery": [
                "Dark Embrace",
                "Soul Drain",
                "Soul Storm",
                "Summon Mistress",
            ],
            "Mu Mastery": [
                "Summon Adept",
                "Electric Shackles",
                "Power Sink",
                "Charged Armor",
            ],
        },
        "Primary": {
            "Archery": [
                "Snap Shot",
                "Aimed Shot",
                "Fistful of Arrows",
                "Blazing Arrow",
                "Aim",
                "Explosive Arrow",
                "Ranged Shot",
                "Stunning Shot",
                "Rain of Arrows",
            ],
            "Assault Rifle": [
                "Burst",
                "Slug",
                "Buckshot",
                "M30 Grenade",
                "Beanbag",
                "Sniper Rifle",
                "Flamethrower",
                "Ignite",
                "Full Auto",
            ],
            "Dark Blast": [
                "Dark Blast",
                "Gloom",
                "Moonbeam",
                "Dark Pit",
                "Tenebrous Tentacles",
                "Night Fall",
                "Torrent",
                "Life Drain",
                "Blackstar",
            ],
            "Dual Pistols": [
                "Pistols",
                "Dual Wield",
                "Empty Clips",
                "Swap Ammo",
                "Bullet Rain",
                "Suppressive Fire",
                "Executioner's Shot",
                "Piercing Rounds",
                "Hail of Bullets",
            ],
            "Electrical Blast": [
                "Charged Bolts",
                "Lightning Bolt",
                "Ball Lightning",
                "Short Circuit",
                "Aim",
                "Zapp",
                "Tesla Cage",
                "Voltaic Sentinel",
                "Thunderous Blast",
            ],
            "Energy Blast": [
                "Power Bolt",
                "Power Blast",
                "Energy Torrent",
                "Power Burst",
                "Sniper Blast",
                "Aim",
                "Power Push",
                "Explosive Blast",
                "Nova",
            ],
            "Fire Blast": [
                "Flares",
                "Fire Blast",
                "Fire Ball",
                "Rain Of Fire",
                "Fire Breath",
                "Aim",
                "Blaze",
                "Blazing Bolt",
                "Inferno",
            ],
            "Ice Blast": [
                "Ice Bolt",
                "Ice Blast",
                "Frost Breath",
                "Aim",
                "Freeze Ray",
                "Ice Storm",
                "Bitter Ice Blast",
                "Bitter Freeze Ray",
                "Blizzard",
            ],
            "Radiation Blast": [
                "Neutrino Bolt",
                "X-Ray Beam",
                "Irradiate",
                "Electron Haze",
                "Proton Volley",
                "Aim",
                "Cosmic Burst",
                "Neutron Bomb",
                "Atomic Blast",
            ],
            "Sonic Attack": [
                "Shriek",
                "Scream",
                "Howl",
                "Shockwave",
                "Shout",
                "Amplify",
                "Siren's Song",
                "Screech",
                "Dreadful Wail",
            ],
        },
        "Secondary": {
            "Cold Domination": [
                "Infrigidate",
                "Ice Shield",
                "Snow Storm",
                "Glacial Shield",
                "Frostwork",
                "Arctic Fog",
                "Benumb",
                "Sleet",
                "Heat Loss",
            ],
            "Dark Miasma": [
                "Twilight Grasp",
                "Tar Patch",
                "Darkest Night",
                "Howling Twilight",
                "Shadow Fall",
                "Fearsome Stare",
                "Petrifying Gaze",
                "Black Hole",
                "Dark Servant",
            ],
            "Kinetics": [
                "Transfusion",
                "Siphon Power",
                "Repel",
                "Siphon Speed",
                "Increase Density",
                "Speed Boost",
                "Inertial Reduction",
                "Transference",
                "Fulcrum Shift",
            ],
            "Pain Domination": [
                "Nullify Pain",
                "Soothe",
                "Share Pain",
                "Conduit Of Pain",
                "Enforced Morale",
                "Soothing Aura",
                "World of Pain",
                "Anguishing Cry",
                "Painbringer",
            ],
            "Radiation Emission": [
                "Radiant Aura",
                "Radiation Infection",
                "Accelerate Metabolism",
                "Enervating Field",
                "Mutation",
                "Lingering Radiation",
                "Choking Cloud",
                "Fallout",
                "EM Pulse",
            ],
            "Sonic Resonance": [
                "Sonic Siphon",
                "Sonic Barrier",
                "Sonic Haven",
                "Sonic Cage",
                "Disruption Field",
                "Sonic Dispersion",
                "Sonic Repulsion",
                "Clarity",
                "Liquefy",
            ],
            "Storm Summoning": [
                "Gale",
                "O2 Boost",
                "Snow Storm",
                "Steamy Mist",
                "Freezing Rain",
                "Hurricane",
                "Thunder Clap",
                "Tornado",
                "Lightning Storm",
            ],
            "Thermal Radiation": [
                "Warmth",
                "Fire Shield",
                "Cauterize",
                "Plasma Shield",
                "Power of the Phoenix",
                "Thaw",
                "Forge",
                "Heat Exhaustion",
                "Melt Armor",
            ],
            "Traps": [
                "Web Grenade",
                "Caltrops",
                "Triage Beacon",
                "Acid Mortar",
                "Poison Trap",
                "Seeker Drones",
                "Trip Mine",
                "Time Bomb",
                "Force Field Generator",
            ],
            "Trick Arrow": [
                "Entangling Arrow",
                "Flash Arrow",
                "Glue Arrow",
                "Ice Arrow",
                "Poison Gas Arrow",
                "Acid Arrow",
                "Disruption Arrow",
                "Oil Slick Arrow",
                "EMP Arrow",
            ],
        },
    },
    'Defender': {
        'Faction': 'H',
        "Epic": {
            "Dark Mastery": [
                "Oppressive Gloom",
                "Dark Consumption",
                "Dark Embrace",
                "Soul Drain",
            ],
            "Electric Mastery": [
                "Electric Fence",
                "Thunder Strike",
                "Charged Armor",
                "Power Sink",
            ],
            "Power Mastery": [
                "Conserve Power",
                "Temp Invulnerability",
                "Total Focus",
                "Power Build Up",
            ],
            "Psychic Mastery": [
                "Dominate",
                "Mass Hypnosis",
                "Mind Over Body",
                "Telekinesis",
            ],
        },
        "Primary": {
            "Cold Domination": [
                "Infrigidate",
                "Ice Shield",
                "Snow Storm",
                "Glacial Shield",
                "Frostwork",
                "Arctic Fog",
                "Benumb",
                "Sleet",
                "Heat Loss",
            ],
            "Dark Miasma": [
                "Twilight Grasp",
                "Tar Patch",
                "Darkest Night",
                "Howling Twilight",
                "Shadow Fall",
                "Fearsome Stare",
                "Petrifying Gaze",
                "Black Hole",
                "Dark Servant",
            ],
            "Empathy": [
                "Healing Aura",
                "Heal Other",
                "Absorb Pain",
                "Resurrect",
                "Clear Mind",
                "Fortitude",
                "Recovery Aura",
                "Adrenalin Boost",
                "Regeneration Aura",
            ],
            "Force Field": [
                "Personal Force Field",
                "Deflection Shield",
                "Force Bolt",
                "Insulation Shield",
                "Detention Field",
                "Dispersion Bubble",
                "Repulsion Field",
                "Repulsion Bomb",
                "Force Bubble",
            ],
            "Kinetics": [
                "Transfusion",
                "Siphon Power",
                "Repel",
                "Siphon Speed",
                "Increase Density",
                "Speed Boost",
                "Inertial Reduction",
                "Transference",
                "Fulcrum Shift",
            ],
            "Radiation Emission": [
                "Radiant Aura",
                "Radiation Infection",
                "Accelerate Metabolism",
                "Enervating Field",
                "Mutation",
                "Lingering Radiation",
                "Choking Cloud",
                "Fallout",
                "EM Pulse",
            ],
            "Sonic Resonance": [
                "Sonic Siphon",
                "Sonic Barrier",
                "Sonic Haven",
                "Sonic Cage",
                "Disruption Field",
                "Clarity",
                "Sonic Repulsion",
                "Sonic Dispersion",
                "Liquefy",
            ],
            "Storm Summoning": [
                "Gale",
                "O2 Boost",
                "Snow Storm",
                "Steamy Mist",
                "Freezing Rain",
                "Hurricane",
                "Thunder Clap",
                "Tornado",
                "Lightning Storm",
            ],
            "Traps": [
                "Web Grenade",
                "Caltrops",
                "Triage Beacon",
                "Acid Mortar",
                "Force Field Generator",
                "Poison Trap",
                "Seeker Drones",
                "Trip Mine",
                "Time Bomb",
            ],
            "Trick Arrow": [
                "Ice Arrow",
                "Acid Arrow",
                "Entangling Arrow",
                "Flash Arrow",
                "Glue Arrow",
                "Poison Gas Arrow",
                "Disruption Arrow",
                "Oil Slick Arrow",
                "EM Pulse Arrow",
            ],
        },
        "Secondary": {
            "Archery": [
                "Snap Shot",
                "Aim",
                "Aimed Shot",
                "Fistful of Arrows",
                "Flaming Arrow",
                "Rain of Arrows",
                "Ranged Shot",
                "Stunning Shot",
                "Explosive Arrow",
            ],
            "Assault Rifle": [
                "Burst",
                "Slug",
                "Buckshot",
                "M30 Grenade",
                "Beanbag",
                "Sniper Rifle",
                "Flamethrower",
                "Ignite",
                "Full Auto",
            ],
            "Dark Blast": [
                "Night Fall",
                "Dark Blast",
                "Gloom",
                "Moonbeam",
                "Dark Pit",
                "Tenebrous Tentacles",
                "Torrent",
                "Life Drain",
                "Blackstar",
            ],
            "Dual Pistols": [
                "Pistols",
                "Dual Wield",
                "Empty Clips",
                "Swap Ammo",
                "Bullet Rain",
                "Suppressive Fire",
                "Executioner's Shot",
                "Piercing Rounds",
                "Hail of Bullets",
            ],
            "Electrical Blast": [
                "Charged Bolts",
                "Lightning Bolt",
                "Ball Lightning",
                "Short Circuit",
                "Aim",
                "Zapp",
                "Tesla Cage",
                "Voltaic Sentinel",
                "Thunderous Blast",
            ],
            "Energy Blast": [
                "Power Bolt",
                "Power Blast",
                "Energy Torrent",
                "Power Burst",
                "Sniper Blast",
                "Aim",
                "Power Push",
                "Explosive Blast",
                "Nova",
            ],
            "Ice Blast": [
                "Ice Bolt",
                "Ice Blast",
                "Frost Breath",
                "Aim",
                "Freeze Ray",
                "Ice Storm",
                "Bitter Ice Blast",
                "Bitter Freeze Ray",
                "Blizzard",
            ],
            "Psychic Blast": [
                "Mental Blast",
                "Subdue",
                "Psionic Lance",
                "Psychic Scream",
                "Telekinetic Blast",
                "Will Domination",
                "Psionic Tornado",
                "Scramble Thoughts",
                "Psychic Wail",
            ],
            "Radiation Blast": [
                "Neutrino Bolt",
                "X-Ray Beam",
                "Irradiate",
                "Electron Haze",
                "Proton Volley",
                "Aim",
                "Cosmic Burst",
                "Neutron Bomb",
                "Atomic Blast",
            ],
            "Sonic Attack": [
                "Shriek",
                "Scream",
                "Howl",
                "Shockwave",
                "Shout",
                "Amplify",
                "Siren's Song",
                "Screech",
                "Dreadful Wail",
            ],
        },
    },
    'Dominator': {
        'Faction': 'V',
        "Epic": {
            "Mace Mastery": [
                "Poisonous Ray",
                "Scorpion Shield",
                "Disruptor Blast",
                "Summon Tarantula",
            ],
            "Leviathan Mastery": [
                "Water Spout",
                "Chum Spray",
                "Summon Coralax",
            ],
            "Soul Mastery": [
                "Dark Consumption",
                "Dark Embrace",
                "Dark Obliteration",
                "Summon Seer",
            ],
            "Mu Mastery": [
                "Power Sink",
                "Charged Armor",
                "Ball Lightning",
                "Summon Guardian",
            ],
        },
        "Primary": {
            "Earth Control": [
                "Stone Prison",
                "Fossilize",
                "Stone Cages",
                "Quicksand",
                "Salt Crystals",
                "Stalagmites",
                "Earthquake",
                "Volcanic Gasses",
                "Animate Stone",
            ],
            "Fire Control": [
                "Ring of Fire",
                "Char",
                "Fire Cages",
                "Smoke",
                "Hot Feet",
                "Flashfire",
                "Cinders",
                "Bonfire",
                "Fire Imps",
            ],
            "Gravity Control": [
                "Crush",
                "Lift",
                "Gravity Distortion",
                "Propel",
                "Crushing Field",
                "Dimension Shift",
                "Gravity Distortion Field",
                "Wormhole",
                "Singularity",
            ],
            "Ice Control": [
                "Chilblain",
                "Block of Ice",
                "Frostbite",
                "Arctic Air",
                "Shiver",
                "Ice Slick",
                "Flash Freeze",
                "Glacier",
                "Jack Frost",
            ],
            "Mind Control": [
                "Mesmerize",
                "Levitate",
                "Dominate",
                "Confuse",
                "Mass Hypnosis",
                "Telekinesis",
                "Total Domination",
                "Terrify",
                "Mass Confusion",
            ],
            "Plant Control": [
                "Entangle",
                "Strangler",
                "Roots",
                "Spore Burst",
                "Seeds of Confusion",
                "Spirit Tree",
                "Vines",
                "Carrion Creepers",
                "Fly Trap",
            ],
        },
        "Secondary": {
            "Earth Assault": [
                "Stone Spears",
                "Stone Mallet",
                "Tremor",
                "Hurl Boulder",
                "Power Boost",
                "Heavy Mallet",
                "Seismic Smash",
                "Mud Pots",
                "Fissure",
            ],
            "Electrictiy Assault": [
                "Charged Bolts",
                "Charged Brawl",
                "Lightning Bolt",
                "Havoc Punch",
                "Build Up",
                "Zapp",
                "Static Discharge",
                "Thunder Strike",
                "Voltaic Sentinel",
            ],
            "Energy Assault": [
                "Power Bolt",
                "Bone Smasher",
                "Power Push",
                "Power Blast",
                "Power Boost",
                "Whirling Hands",
                "Total Focus",
                "Sniper Blast",
                "Power Burst",
            ],
            "Fiery Assault": [
                "Flares",
                "Incinerate",
                "Fire Breath",
                "Fire Blast",
                "Fiery Embrace",
                "Combustion",
                "Consume",
                "Blazing Bolt",
                "Blaze",
            ],
            "Icy Assault": [
                "Ice Bolt",
                "Ice Sword",
                "Ice Sword Circle",
                "Ice Blast",
                "Power Boost",
                "Frost Breath",
                "Chilling Embrace",
                "Greater Ice Sword",
                "Bitter Ice Blast",
            ],
            "Psionic Assault": [
                "Psionic Dart",
                "Mind Probe",
                "Telekinetic Thrust",
                "Mental Blast",
                "Psychic Scream",
                "Drain Psyche",
                "Subdue",
                "Psionic Lance",
                "Psychic Shockwave",
            ],
            "Thorny Assault": [
                "Thorny Darts",
                "Skewer",
                "Impale",
                "Aim",
                "Thorn Burst",
                "Thorntrops",
                "Ripper",
                "Thorn Barrage",
                "Fling Thorns",
            ],
        },
    },
    'Mastermind': {
        'Faction': 'V',
        "Epic": {
            "Mace Mastery": [
                "Web Envelope",
                "Scorpion Shield",
                "Mace Beam Volley",
                "Web Cocoon",
            ],
            "Leviathan Mastery": [
                "School of Sharks",
                "Chum Spray",
                "Spirit Shark Jaws",
            ],
            "Soul Mastery": [
                "Dark Embrace",
                "Night Fall",
                "Soul Storm",
                "Soul Tentacles",
            ],
            "Mu Mastery": [
                "Static Discharge",
                "Charged Armor",
                "Electric Shackles",
                "Electrifying Fences",
            ],
        },
        "Primary": {
            "Mercenaries": [
                "Burst",
                "Soldiers",
                "Slug",
                "Equip Mercenary",
                "M30 Grenade",
                "Spec Ops",
                "Serum",
                "Commando",
                "Tactical Upgrade",
            ],
            "Necromancy": [
                "Dark Blast",
                "Gloom",
                "Life Drain",
                "Zombie Horde",
                "Enchant Undead",
                "Grave Knight",
                "Soul Extraction",
                "Lich",
                "Dark Empowerment",
            ],
            "Ninjas": [
                "Snap Shot",
                "Aimed Shot",
                "Fistful of Arrows",
                "Call Genin",
                "Train Ninjas",
                "Call Jounin",
                "Smoke Flash",
                "Oni",
                "Kuji In Zen",
            ],
            "Robotics": [
                "Pulse Rifle Blast",
                "Pulse Rifle Burst",
                "Photon Grenade",
                "Battle Drones",
                "Equip Robot",
                "Protector Bots",
                "Repair",
                "Assault Bot",
                "Upgrade Robot",
            ],
            "Thugs": [
                "Pistols",
                "Call Thugs",
                "Dual Wield",
                "Equip Thugs",
                "Empty Clips",
                "Call Enforcer",
                "Gang War",
                "Call Bruiser",
                "Upgrade Equipment",
            ],
            "Demon Summoning": [
                "Corruption",
                "Summon Demonlings",
                "Lash",
                "Enchant Weapon",
                "Crack Whip",
                "Summon Demons",
                "Hell on Earth",
                "Summon Demon Prince",
                "Abyssal Empowerment",
            ],
        },
        "Secondary": {
            "Dark Miasma": [
                "Twilight Grasp",
                "Tar Patch",
                "Darkest Night",
                "Howling Twilight",
                "Shadow Fall",
                "Fearsome Stare",
                "Petrifying Gaze",
                "Black Hole",
                "Dark Servant",
            ],
            "Force Field": [
                "Force Bolt",
                "Deflection Shield",
                "Insulation Shield",
                "Detention Field",
                "Dispersion Bubble",
                "Force Bubble",
                "Personal Force Field",
                "Repulsion Field",
                "Repulsion Bomb",
            ],
            "Pain Domination": [
                "Nullify Pain",
                "Soothe",
                "Share Pain",
                "Conduit Of Pain",
                "Enforced Morale",
                "Suppress Pain",
                "World of Pain",
                "Anguishing Cry",
                "Painbringer",
            ],
            "Poison": [
                "Alkaloid",
                "Envenom",
                "Weaken",
                "Neurotoxic Breath",
                "Elixir of Life",
                "Antidote",
                "Paralytic Poison",
                "Poison Trap",
                "Noxious Gas",
            ],
            "Storm Summoning": [
                "Gale",
                "O2 Boost",
                "Snow Storm",
                "Steamy Mist",
                "Freezing Rain",
                "Hurricane",
                "Thunder Clap",
                "Tornado",
                "Lightning Storm",
            ],
            "Traps": [
                "Detonator",
                "Acid Mortar",
                "Caltrops",
                "Poison Trap",
                "Seeker Drones",
                "Triage Beacon",
                "Trip Mine",
                "Web Grenade",
                "Force Field Generator",
            ],
            "Thermal Radiation": [
                "Warmth",
                "Fire Shield",
                "Cauterize",
                "Plasma Shield",
                "Power of the Phoenix",
                "Thaw",
                "Forge",
                "Heat Exhaustion",
                "Melt Armor",
            ],
            "Trick Arrow": [
                "Poison Gas Arrow",
                "Entangling Arrow",
                "Flash Arrow",
                "Glue Arrow",
                "Ice Arrow",
                "Acid Arrow",
                "Disruption Arrow",
                "Oil Slick Arrow",
                "EMP Arrow",
            ],
        },
    },
    'Peacebringer': {
        'Faction': 'H',
        "Dependent": {
            "Bright Nova": [
                "Bright Nova Bolt",
                "Bright Nova Blast",
                "Bright Nova Scatter",
                "Bright Nova Detonation",
            ],
            "White Dwarf": [
                "White Dwarf Strike",
                "White Dwarf Smite",
                "White Dwarf Flare",
                "White Dwarf Sublimation",
                "White Dwarf Antagonize",
                "White Dwarf Step",
            ],
        },
        "Inherent": {
            "Inherent": [
                "Combat Flight",
                "Energy Flight",
            ],
        },
        "Primary": {
            "Luminous Blast": [
                "Gleaming Bolt",
                "Glinting Eye",
                "Gleaming Blast",
                "Bright Nova",
                "Radiant Strike",
                "Proton Scatter",
                "Build Up",
                "Luminous Detonation",
                "Incandescent Strike",
                "Pulsar",
                "Glowing Touch",
                "Solar Flare",
                "Photon Seekers",
                "Dawn Strike",
            ],
        },
        "Secondary": {
            "Luminous Aura": [
                "Shining Shield",
                "Essence Boost",
                "Thermal Shield",
                "Quantum Shield",
                "Group Energy Flight",
                "White Dwarf",
                "Reform Essence",
                "Conserve Energy",
                "Quantum Flight",
                "Restore Essence",
                "Light Form",
            ],
        },
    },
    'Scrapper': {
        'Faction': 'H',
        "Epic": {
            "Body Mastery": [
                "Conserve Power",
                "Focused Accuracy",
                "Laser Beam Eyes",
                "Energy Torrent",
            ],
            "Darkness Mastery": [
                "Torrent",
                "Petrifying Gaze",
                "Dark Blast",
                "Tenebrous Tentacles",
            ],
            "Weapon Mastery": [
                "Web Grenade",
                "Caltrops",
                "Shuriken",
                "Exploding Shurken",
            ],
        },
        "Primary": {
            "Broad Sword": [
                "Hack",
                "Slash",
                "Slice",
                "Build Up",
                "Parry",
                "Confront",
                "Whirling Sword",
                "Disembowel",
                "Head Splitter",
            ],
            "Claws": [
                "Swipe",
                "Strike",
                "Slash",
                "Spin",
                "Confront",
                "Follow Up",
                "Focus",
                "Eviscerate",
                "Shockwave",
            ],
            "Dark Melee": [
                "Shadow Punch",
                "Smite",
                "Shadow Maul",
                "Touch of Fear",
                "Siphon Life",
                "Confront",
                "Dark Consumption",
                "Soul Drain",
                "Midnight Grasp",
            ],
            "Dual Blades": [
                "Nimble Slash",
                "Power Slice",
                "Ablating Strike",
                "Typhoon's Edge",
                "Blinding Feint",
                "Confront",
                "Vengeful Slice",
                "Sweeping Strike",
                "One Thousand Cuts",
            ],
            "Electrical Melee": [
                "Charged Brawl",
                "Havoc Punch",
                "Jacobs Ladder",
                "Build Up",
                "Thunder Strike",
                "Taunt",
                "Chain Induction",
                "Lightning Clap",
                "Lightning Rod",
            ],
            "Fiery Melee": [
                "Scorch",
                "Fire Sword",
                "Cremate",
                "Build Up",
                "Breath of Fire",
                "Confront",
                "Fire Sword Circle",
                "Incinerate",
                "Greater Fire Sword",
            ],
            "Katana": [
                "Sting of the Wasp",
                "Gambler's Cut",
                "Flashing Steel",
                "Build Up",
                "Divine Avalanche",
                "Calling the Wolf",
                "The Lotus Drops",
                "Soaring Dragon",
                "Golden Dragonfly",
            ],
            "Martial Arts": [
                "Thunder Kick",
                "Storm Kick",
                "Cobra Strike",
                "Focus Chi",
                "Crane Kick",
                "Warrior's Challenge",
                "Crippling Axe Kick",
                "Dragon's Tail",
                "Eagle's Claw",
            ],
            "Spines": [
                "Barb Swipe",
                "Lunge",
                "Spine Burst",
                "Build Up",
                "Impale",
                "Confront",
                "Quills",
                "Ripper",
                "Throw Spines",
            ],
        },
        "Secondary": {
            "Dark Armor": [
                "Dark Embrace",
                "Death Shroud",
                "Murky Cloud",
                "Obsidian Shield",
                "Dark Regeneration",
                "Cloak Of Darkness",
                "Cloak Of Fear",
                "Oppressive Gloom",
                "Soul Transfer",
            ],
            "Electric Armor": [
                "Charged Armor",
                "Lightning Field",
                "Conductive Shield",
                "Static Shield",
                "Grounded",
                "Energize",
                "Lightning Reflexes",
                "Power Sink",
                "Power Surge",
            ],
            "Fiery Aura": [
                "Blazing Aura",
                "Fire Shield",
                "Healing Flames",
                "Consume",
                "Plasma Shield",
                "Burn",
                "Fiery Embrace",
                "Rise of the Phoenix",
            ],
            "Invulnerability": [
                "Temp Invulnerability",
                "Dull Pain",
                "Unyielding",
                "Invincibility",
                "Unstoppable",
            ],
            "Regeneration": [
                "Reconstruction",
                "Quick Recovery",
                "Dull Pain",
                "Integration",
                "Instant Healing",
                "Revive",
                "Moment Of Glory",
            ],
            "Shield Defense": [
                "Deflection",
                "Battle Agility",
                "Active Defense",
                "Against All Odds",
                "Grant Cover",
                "Shield Charge",
                "One With the Shield",
            ],
            "Super Reflexes": [
                "Focused Fighting",
                "Focused Senses",
                "Practiced Brawler",
                "Evasion",
                "Elude",
            ],
            "Willpower": [
                "Mind Over Body",
                "Indomitable Will",
                "Rise To The Challenge",
                "Heightened Senses",
                "Resurgence",
                "Strength of Will",
            ],
        },
    },
    'Stalker': {
        'Faction': 'V',
        "Epic": {
            "Mace Mastery": [
                "Summon Blaster",
                "Mace Blast",
                "Mace Beam",
                "Web Cocoon",
            ],
            "Leviathan Mastery": [
                "Spirit Shark",
                "Summon Guardian",
                "Water Spout",
                "Spirit Shark Jaws",
            ],
            "Soul Mastery": [
                "Dark Blast",
                "Moonbeam",
                "Soul Storm",
                "Summon Widow",
            ],
            "Mu Mastery": [
                "Mu Bolts",
                "Zapp",
                "Electric Shackles",
                "Summon Adept",
            ],
        },
        "Primary": {
            "Broad Sword": [
                "Hack",
                "Slash",
                "Slice",
                "Assassin's Slash",
                "Build Up",
                "Placate",
                "Parry",
                "Disembowel",
                "Head Splitter",
            ],
            "Claws": [
                "Swipe",
                "Strike",
                "Slash",
                "Assassin's Claw",
                "Build Up",
                "Placate",
                "Focus",
                "Eviscerate",
                "Shockwave",
            ],
            "Dark Melee": [
                "Shadow Punch",
                "Smite",
                "Shadow Maul",
                "Assassin's Eclipse",
                "Build Up",
                "Placate",
                "Siphon Life",
                "Touch of Fear",
                "Midnight Grasp",
            ],
            "Dual Blades": [
                "Nimble Slash",
                "Power Slice",
                "Ablating Strike",
                "Assassin's Blades",
                "Build Up",
                "Placate",
                "Vengeful Slice",
                "Sweeping Strike",
                "One Thousand Cuts",
            ],
            "Electric Melee": [
                "Charged Brawl",
                "Havoc Punch",
                "Jacobs Ladder",
                "Assassin's Shock",
                "Build Up",
                "Placate",
                "Chain Induction",
                "Lighning Clap",
                "Lightning Rod",
            ],
            "Energy Melee": [
                "Barrage",
                "Energy Punch",
                "Bone Smasher",
                "Assassin's Strike",
                "Build Up",
                "Placate",
                "Stun",
                "Energy Transfer",
                "Total Focus",
            ],
            "Martial Arts": [
                "Thunder Kick",
                "Storm Kick",
                "Crippling Axe Kick",
                "Focus Chi",
                "Placate",
                "Cobra Strike",
                "Crane Kick",
                "Eagle's Claw",
                "Assassin's Blow",
            ],
            "Ninja Blade": [
                "Sting of the Wasp",
                "Gambler's Cut",
                "Flashing Steel",
                "Assassin's Blade",
                "Build Up",
                "Placate",
                "Divine Avalanche",
                "Soaring Dragon",
                "Golden Dragonfly",
            ],
            "Spines": [
                "Barb Swipe",
                "Lunge",
                "Spine Burst",
                "Build Up",
                "Impale",
                "Ripper",
                "Throw Spines",
                "Assassin's Impaler",
                "Placate",
            ],
        },
        "Secondary": {
            "Dark Armor": [
                "Hide",
                "Dark Embrace",
                "Murky Cloud",
                "Obsidian Shield",
                "Dark Regeneration",
                "Cloak Of Fear",
                "Oppressive Gloom",
                "Soul Transfer",
            ],
            "Electric Armor": [
                "Hide",
                "Charged Armor",
                "Conductive Shield",
                "Static Shield",
                "Conserve Power",
                "Power Sink",
                "Power Surge ",
            ],
            "Energy Aura": [
                "Hide",
                "Kinetic Shield",
                "Power Shield",
                "Entropy Shield",
                "Energy Drain",
                "Conserve Power",
                "Overload",
                "Repulse",
            ],
            "Ninjitsu": [
                "Hide",
                "Ninja Reflexes",
                "Danger Sense",
                "Caltrops",
                "Kuji-In Rin",
                "Kuji-In Sha",
                "Smoke Flash",
                "Blinding Powder",
                "Kuji-In Retsu",
            ],
            "Regeneration": [
                "Reconstruction",
                "Dull Pain",
                "Integration",
                "Instant Healing",
                "Revive",
                "Moment Of Glory",
                "Hide",
            ],
            "Super Reflexes": [
                "Focused Fighting",
                "Focused Senses",
                "Practiced Brawler",
                "Evasion",
                "Elude",
                "Hide",
            ],
            "Willpower": [
                "Hide",
                "Reconstruction",
                "Mind Over Body",
                "Indomitable Will",
                "Heightened Senses",
                "Resurgence",
                "Strength of Will",
            ],
        },
    },
    'Tanker': {
        'Faction': 'H',
        "Epic": {
            "Arctic Mastery": [
                "Chilblain",
                "Block of Ice",
                "Ice Blast",
                "Ice Storm",
            ],
            "Earth Mastery": [
                "Salt Crystals",
                "Fossilize",
                "Stalagmites",
                "Stone Prison",
            ],
            "Energy Mastery": [
                "Conserve Power",
                "Focused Accuracy",
                "Laser Beam Eyes",
                "Energy Torrent",
            ],
            "Pyre Mastery": [
                "Ring of Fire",
                "Char",
                "Fire Blast",
                "Fire Ball",
            ],
        },
        "Primary": {
            "Dark Armor": [
                "Dark Embrace",
                "Death Shroud",
                "Murky Cloud",
                "Obsidian Shield",
                "Dark Regeneration",
                "Cloak Of Darkness",
                "Cloak Of Fear",
                "Oppressive Gloom",
                "Soul Transfer",
            ],
            "Electric Armor": [
                "Charged Armor",
                "Lightning Field",
                "Conductive Shield",
                "Static Shield",
                "Grounded",
                "Energize",
                "Lightning Reflexes",
                "Power Sink",
                "Power Surge",
            ],
            "Fiery Aura": [
                "Blazing Aura",
                "Fire Shield",
                "Healing Flames",
                "Consume",
                "Plasma Shield",
                "Burn",
                "Fiery Embrace",
                "Rise of the Phoenix",
            ],
            "Ice Armor": [
                "Frozen Armor",
                "Hoarfrost",
                "Chilling Embrace",
                "Wet Ice",
                "Icicles",
                "Glacial Armor",
                "Energy Absorbtion",
                "Hibernate",
            ],
            "Invulnerability": [
                "Temp Invulnerability",
                "Dull Pain",
                "Unyielding",
                "Invincibility",
                "Unstoppable",
            ],
            "Shield Defense": [
                "Deflection",
                "Battle Agility",
                "Active Defense",
                "Against All Odds",
                "Grant Cover",
                "Shield Charge",
                "One With the Shield",
            ],
            "Stone Armor": [
                "Rock Armor",
                "Earth's Embrace",
                "Mud Pots",
                "Rooted",
                "Brimstone Armor",
                "Crystal Armor",
                "Mineral Armor",
                "Granite Armor",
            ],
            "Willpower": [
                "Mind Over Body",
                "Indomitable Will",
                "Rise To The Challenge",
                "Heightened Senses",
                "Resurgence",
                "Strength of Will",
            ],
        },
        "Secondary": {
            "Battle Axe": [
                "Gash",
                "Chop",
                "Taunt",
                "Beheader",
                "Build Up",
                "Swoop",
                "Whirling Axe",
                "Cleave",
                "Pendulum",
            ],
            "Dark Melee": [
                "Shadow Punch",
                "Smite",
                "Shadow Maul",
                "Taunt",
                "Siphon Life",
                "Touch of Fear",
                "Soul Drain",
                "Dark Consumption",
                "Midnight Grasp",
            ],
            "Dual Blades": [
                "Nimble Slash",
                "Power Slice",
                "Ablating Strike",
                "Taunt",
                "Typhoon's Edge",
                "Blinding Feint",
                "Vengeful Slice",
                "Sweeping Strike",
                "One Thousand Cuts",
            ],
            "Electrical Melee": [
                "Charged Brawl",
                "Havoc Punch",
                "Jacobs Ladder",
                "Taunt",
                "Thunder Strike",
                "Build Up",
                "Chain Induction",
                "Lightning Clap",
                "Lightning Rod",
            ],
            "Energy Melee": [
                "Barrage",
                "Energy Punch",
                "Taunt",
                "Bone Smasher",
                "Whirling Hands",
                "Stun",
                "Build Up",
                "Energy Transfer",
                "Total Focus",
            ],
            "Fiery Melee": [
                "Scorch",
                "Fire Sword",
                "Cremate",
                "Build Up",
                "Breath of Fire",
                "Taunt",
                "Fire Sword Circle",
                "Incinerate",
                "Greater Fire Sword",
            ],
            "Ice Melee": [
                "Frozen Fists",
                "Ice Sword",
                "Taunt",
                "Frost",
                "Build Up",
                "Ice Patch",
                "Freezing Touch",
                "Greater Ice Sword",
                "Frozen Aura",
            ],
            "Stone Melee": [
                "Stone Fist",
                "Stone Mallet",
                "Taunt",
                "Heavy Mallet",
                "Build Up",
                "Fault",
                "Hurl Boulder",
                "Tremor",
                "Seismic Smash",
            ],
            "Super Strength": [
                "Jab",
                "Punch",
                "Taunt",
                "Haymaker",
                "Hand Clap",
                "Knockout Blow",
                "Rage",
                "Hurl",
                "Foot Stomp",
            ],
            "War Mace": [
                "Bash",
                "Pulverize",
                "Taunt",
                "Clobber",
                "Build Up",
                "Jawbreaker",
                "Whirling Mace",
                "Shatter",
                "Crowd Control",
            ],
        },
    },
    'Warshade': {
        'Faction': 'H',
        "Dependent": {
            "Black Dwarf": [
                "Black Dwarf Strike",
                "Black Dwarf Smite",
                "Black Dwarf Mire",
                "Black Dwarf Drain",
                "Black Dwarf Step",
                "Black Dwarf Antagonize",
            ],
            "Dark Nova": [
                "Dark Nova Blast",
                "Dark Nova Bolt",
                "Dark Nova Detonation",
                "Dark Nova Emmanation",
            ],
        },
        "Inherent": {
            "Inherent": [
                "Shadow Recall",
                "Shadow Step",
            ],
        },
        "Primary": {
            "Umbral Blast": [
                "Shadow Bolt",
                "Ebon Eye",
                "Gravimetric Snare",
                "Dark Nova",
                "Shadow Blast",
                "Sunless Mire",
                "Dark Matter Detonation",
                "Gravity Well",
                "Essence Drain",
                "Gravity Emanation",
                "Unchain Essence",
                "Dark Extraction",
                "Quasar",
                "Starless Step",
            ],
        },
        "Secondary": {
            "Umbral Aura": [
                "Gravity Shield",
                "Orbiting Death",
                "Penumbral Shield",
                "Shadow Cloak",
                "Twilight Shield",
                "Black Dwarf",
                "Stygian Circle",
                "Nebulous Form",
                "Inky Aspect",
                "Stygian Return",
                "Eclipse",
            ],
        },
    },
};

MiscPowers = {
# -- TODO!!! split accolades by hero / villain
    "Badge": {
        "Accolade": [
            "Eye of the Magus",
            "Crey CBX-9 Pistol",
            "Demonic Aura",
            "Elusive Mind",
            "Force of Nature",
            "Geas of the Kind Ones",
            "Portable Workbench",
            "Stolen Immobilizer Ray",
            "Megalomaniac",
            "Vanguard Medal",
        ],
    },
    "General": {
        "General": [
            "Sprint",
            "Brawl",
            "Rest",
            "Prestige Power Slide",
            "Prestige Power Rush",
            "Prestige Power Dash",
            "Prestige Power Surge ",
            "Prestige Power Quick",
        ],
    },
    "Pool": {
        "Concealment": [
            "Stealth",
            "Grant Invisibility",
            "Invisibility",
            "Phase Shift",
        ],
        "Fighting": [
            "Boxing",
            "Kick",
            "Tough",
            "Weave",
        ],
        "Flight": [
            "Hover",
            "Air Superiority",
            "Fly",
            "Group Fly",
        ],
        "Leadership": [
            "Maneuvers",
            "Assault",
            "Tactics",
            "Vengeance",
        ],
        "Leaping": [
            "Jump Kick",
            "Combat Jumping",
            "Super Jump",
            "Acrobatics",
        ],
        "Medicine": [
            "Aid Other",
            "Stimulant",
            "Aid Self",
            "Resuscitate",
        ],
        "Presence": [
            "Challenge",
            "Provoke",
            "Intimidate",
            "Invoke Panic",
        ],
        "Speed": [
            "Flurry",
            "Hasten",
            "Super Speed",
            "Whirlwind",
        ],
        "Teleportation": [
            "Recall Friend",
            "Teleport Foe",
            "Teleport",
            "Team Teleport",
        ],
    },
}


Inspirations = {
    'Accuracy'     : {
        'color': wx.YELLOW,
        'tiers': ['Insight'        , 'Keen Insight'         , 'Uncanny Insight'] ,
    },
    'Health'       : {
        'color': wx.GREEN,
        'tiers': ['Respite'        , 'Dramatic Improvement' , 'Resurgance']      ,
    },
    'Damage'       : {
        'color': wx.RED,
        'tiers': ['Enrage'         , 'Focused Rage'         , 'Righteous Rage']  ,
    },
    'Endurance'    : {
        'color': wx.BLUE,
        'tiers': ['Catch a Breath' , 'Take a Breather'      , 'Second Wind']     ,
    },
    'Defense'      : {
        'color': (128, 0, 153),  # purple
        'tiers': ['Luck'           , 'Good Luck'            , 'Phenomenal Luck'] ,
    },
    'ResistDamage' : {
        'color': (230, 80, 0),   # orange
        'tiers': ['Sturdy'         , 'Rugged'               , 'Robust']          ,
    },
    'BreakFree'    : {
        'color': (110, 76, 200), # light purple
        'tiers': ['Break Free'     , 'Emerge'               , 'Escape']          ,
    },
    'Resurrection' : {
        'color': (50, 180, 160), # cyan
        'tiers': ['Awaken'         , 'Bounce Back'          , 'Restoration']     ,
    },
}

Emotes = {
        'emotes': [
            { 'Converse' : [
                { 'Greetings' : [
                    'Hi%emwave$$local Hi!',
                    'Hello <$target>%em wave$$local Hello, $target',
                    'Introduce <self>%em wave$$local Pleased to meet you! I am $name, a level $level $origin $archetype.',
                    'Looking for Team%local level $level $archetype$$local Looking for team.',
                    'Welcome%em welcome$$local Welcome!',
                ] },
                { 'Combat   ' : [
                    'On my mark...%em stop$$local On my mark...',
                    'ATTACK!%em attack$$local ATTACK!',
                    'Don\'t attack!%em no$$local Don\'t attack!',
                    'Stop!%em stop$$local Stop!',
                    'Come get some!%em taunt1$$local Come get some!',
                ] },
                { 'Travel'    : [
                    'Lead On!%em thumbsup$$local Lead On!',
                    'Onward!%em points$$local Onward!',
                    'Follow me!%em point$$local Follow me!',
                    'Stop!%em stop$$local Stop!',
                    'Wait Here%em stop$$local Wait here.',
                    'Let\'s go!%em thumbsup$$local Let\'s go!',
                    'On my way%local On my way.',
                    'Over here!%em bigwave%%local Over here!',
                    'Where to?%em shrug$$local Where to?',
                    'Ready?%local Ready?',
                    'Get a mission?%local Get a mission?',
                ] },
                { 'Speech'    : [
                    'Yes%em thumbsup$$local Yes',
                    'Yes sir!%em salute$$local Yes sir!',
                    'No%em no$$No',
                    'Huh?%em shrug$$local Huh?'
                    'Good job!%em thumbsup$$Good job!',
                    'Sorry%em bow$$local Sorry',
                    'Thank You%em thanks$$local Thank You',
                    'You\'re Welcome%em yourewelcome$$local You\'re Welcome',
                    'No Problem%em thumbsup$$No Problem',
                    'Grrrrrrrr!%em beatchest$$local Grrrrrrrr!',
                    'Arrrrggggh!%em frustrated$$local Arrrrggggh!',
                    'Excellent!%em clap$$local Excellent!',
                    'Mua Ha Ha Ha!%em evillaugh$$local Mua ha ha ha!',
                ] },
                '---',
                'Chat|Talk', 'Lecture', 'Explain',
                '---',
                'Nod', 'Thumbs Up|yes', 'Shrug|huh', 'Thanks', 'Welcome', 'You\'re Welcome|YoureWelcome',
                '---',
                'Disagree|no', 'Shake Head|No', 'Yada Yada Yada|Yata', 'Talk to the Hand|TalkToHand',
            ]},
            { 'Interact' : [
                'Salute', 'Military Salute', 'Praetorian Salute', 'At Ease',
                '---',
                'Bow', 'Fancy Bow', 'Clap', 'Praise', 'Camera',
                '---',
                'You bow down!|bowdown', 'Surrender', 'Get Some', 'Go Away', 'Taunt 1', 'Taunt 2',
                'Chicken', 'Slash Throat', 'Bring it!', 'Threaten|threathand', 'Hands Up', 'Smack',
                'Slap', 'Slap React', 'Alakazam!', 'Alakazam! React', 'Bat Smash',
                'Bat Smash React', 'Ultimate Power', 'Facepalm', 'Double Facepalm',
                '---',
                { 'Judge' : [
                    'Score 1', 'Score 2', 'Score 3', 'Score 4', 'Score 5',
                    'Score 6', 'Score 7', 'Score 8', 'Score 9', 'Score 10', 
                ] },
                { 'Decide' : [
                    'Coin Toss|coin', 'Roll Dice|dice', 'Observe Dice', 'High Roller|dice7',
                    '---',
                    'Rock', 'Paper', 'Scissors',
                ] },
                { 'Environment' : [
                    'Peer In', 'Touch Screen|screen', 'Type', 'Research', 'Research Low',  'Dig',
                    'Jackhammer', 'Spraypaint', 'Warm Hands', 'Pick Lock', 'Throw Snowflakes|snowflakes',
                    '---',
                    'Sit Chair 1', 'Sit Chair 2', 'Sit Chair 3', 'Sit Bench 1', 'Sit Bench 2',
                    'Sit Bench 3', 'Sit Bench 4', 'Sit Executive Chair', 'Sit Stool',
                    'Sit Table 1', 'Sit Table 2', 'Sit Ledge|ledgesit',
                    '---',
                    'Wall Lean', 'Assume the Position|assumepositionwall',
                ]},
            ]},
            { 'Actions'  : [
                'Wave', 'Big Wave', 'Raise Hand', 'Point', 'Attack',
                '---',
                'Cheer', 'Wave Fist', 'Crack Knuckles|crack', 'Whistle', 'Victory', 'Winner', 'The Wave',
                '---',
                'Angry', 'Frustrated', 'Curse You', 'Roar', 'Howl', 'Tarzan', 'Growl', 'Show Off',
                '---',
                'Dust Off', 'Read Book', 'Burp',
                '---',
                'Laughs|laugh', 'Giggle|laugh2', 'Drat', 'Shucks', 'Grief', 'Flipping Coin', 'Drink Enriche',
                'Open Gift', 'Ghoul Flex', 'Tantrum', 'Collapse', 'Swoon',
                '---',
                { 'Athletics' : [
                    'Backflip', 'Flex 1', 'Flex 2', 'Flex 3', 'Jumping Jacks', 'Kata', 'Pushups',
                ] },
                { 'Wedding' : [
                    'Propose, Throw Rice', 'Throw Confetti', 'Throw Rose Petals',
                ] },
                { 'Animal': [
                    'Hiss', 'Sniff', 'Savage',
                ] },
                { 'Holiday' : [
                    'Throw Snowflakes|snowflakes', 'Offer Gift', 'Receive Gift',
                ] },
                { 'Steam Punk': [
                    'Inspiration', 'Hot Temper', 'Train Whistle',
                ]},
            ]},
            { 'Idle'     : [
                'Afraid', 'Fish|fishing', 'Binoculars', 'Flashlight', 'Flashlight (Up)', 'Flashlight (Down)', 'Clipboard',
                'Invent', 'Panhandle', 'Stunned|wounded', 'Plotting|plot', 'Floating Books|floatbooks',
                'Pamphlet', 'Vendor', 'Protest', 'Listen to Policeband|ListenPoliceBand',
                'Protest Loyalists|protestloyalist', 'Protest Resistance',
                '---',
                'Robot Power Up|powerup', 'Robot Power Down|powerdown',
                'Listen to Stolen Policeband|ListenStolenPoliceBand', 'Tablet Write|matablet',
                'Calculate Theories|calculate', 'Mix Formula', 'Talk Pool|pool', 'Soccer Kick|soccer',
                'Basketball Dribble|basketball', 'Catch Breath',
                '---',
                'Drink', 'Eat Food', 'Eat Donut', 'Drink Tea|teabag',
                { 'Away' : [
                    'Cellphone', 'Crouch', 'Kneel', 'Use Laptop|laptop', 'Lotus', 'Read Newspaper|newspaper',
                    'AFK Sleep|sleep', 'Sit on Ground|sit', 'Wait|waiting',
                ]},
                { 'Evil' : [
                    'Hold Bat|batlookout', 'Evil Laugh', 'Hold Torch', 'Scheme',
                ]},
                { 'Magic': [
                    'Card Trick', 'Juggle', 'Juggle Magic', 'Juggle Fire', 'Juggle Electricity',
                ]},
                { 'Stances' : [
                    'Center Stance|idle2', 'Cross Arms', 'Hands on Hips|akimbo', 'Neutral Stance|idle1',
                    'Hero Stance 1|stancehero1', 'Hero Stance 2|stancehero2',
                    'Villain Stance 1|stancevillain1', 'Villain Stance 2|stancevillain2',
                ]},
                { 'Loyalty': [
                    'Hero Loyal', 'Vigilante Loyal', 'Villain Loyal', 'Rogue Loyal',
                ]}
            ] },
            { 'Music'    : [
                'Boombox',
                { 'Tracklist': [
                    'Track - Altitude|BBAltitude',
                    'Track - Beat|BBBeat',
                    'Track - Catch Me|BBCatchMe',
                    'Track - Dance|BBDance',
                    'Track - Electro Vibe|BBElectroVibe',
                    'Track - Disco Freak|BBDiscoFreak',
                    'Track - Dog Walk|BBDogWalk',
                    'Track - Heavy Dude|BBHeavyDude',
                    'Track - Info Overload|BBInfoOverload',
                    'Track - Jumpy|BBJumpy',
                    'Track - Kick It|BBKickIt',
                    'Track - Looker|BBLooker',
                    'Track - Meaty|BBMeaty',
                    'Track - Notorious|BBNotorious',
                    'Track - Move On|BBMoveOn',
                    'Track - Peace|BBPeace',
                    'Track - Quickie|BBQuickie',
                    'Track - Raver|BBRaver',
                    'Track - Shuffle|BBShuffle',
                    'Track - Technoid|BBTechnoid',
                    'Track - Wind It Up|BBWindItUp',
                    'Track - Venus|BBVenus',
                    'Track - Wah Wah|BBWahWah',
                    'Track - Yellow|BBYellow',
                    'Track - Spaz|BBSpaz',
                ] },
                '---',
                'Dance', 'Shuffle|dance1', 'Rock It|dance2', 'The Washer|dance3', 'Raise the Roof|dance4',
                'Bounce|dance5', 'The Monkey|dance6', 'Drum Dance|drum', 'Robot Dance', 'Karate Dance',
                'Pop Dance', 'Air Guitar', 'Disco Dance',
                '---',
                'Big Drum|drum', 'Small Drum|drumlow',
            ] },
        ],
        'costumechange' : [
            'Backflip',
            'Cast',
            'Confetti Throw',
            'Dimension Shift',
            'Drink Formula',
            'Energy Morph',
            'Evil Laugh',
            'Feather Burst',
            'Feather Spin',
            'Fireworks',
            'Fur Burst',
            'Fur Spin',
            'Gift Burst',
            'Howl',
            'Ice Block',
            'Inner Will',
            'Light Magic',
            'Lightning',
            'Murder Of Crows',
            'Ninja Leap',
            'Nuke',
            'Oil Strike',
            'Peacebringer',
            'Pressure Release',
            'Presto Chango',
            'Pure Energy',
            'Rainbow',
            'Rapid Boil',
            'Salute',
            'Smoke Bomb',
            'Spin',
            'Stone Block',
            'Super Serum',
            'Vanguard Sigil',
            'Vanguard Sigil',
            'Warshade',
        ],
}



# TODO -- these emotes seem not to be in the in-game picker.  Really really investigate
"""
            'Cameraphone',
            'Despair',
            'FireworkBloom',
            'FireworkRocket',
            'FireworkSparkle',
            'Flypose1',
            'Flypose2',
            'Flypose3',
            'Flypose4',
            'Hi',
            'Hmmm',
            'HotTemper',
            'Liedown',
            'Lookup',
            'None',
            'Shocked',
            'Slrcamera',
            'Smartphone',
            'Text',
            'WalkieTalkie',
            'Welcome',
            'YataYata',
"""
