import wx # for wx.Colour values

Origins = ['Magic','Mutation','Natural','Science','Technology']

Archetypes = {
    "Arachnos Soldier": {
        'Faction': 'V',
        "Epic": {
            "Leviathan Mastery" : [ "Spirit Shark", "School of Sharks", "Arctic Breath", "Bile Spray", "Summon Guardian", ],
            "Mace Mastery"      : [ "Mace Blast", "Web Envelope", "Disruptor Blast", "Shatter Armor", "Summon Blaster", ],
            "Mu Mastery"        : [ "Mu Lightning", "Electrifying Fences", "Ball Lightning", "Static Discharge", "Summon Striker", ],
            "Soul Mastery"      : [ "Gloom", "Soul Tentacles", "Darkest Night", "Dark Obliteration", "Summon Widow", ],
        },
        "Primary": {
            "Crab Spider Soldier" : [ "Single Shot", "Pummel", "Burst", "Wide Area Web Grenade", "Heavy Burst", "Bayonet", "Venom Grenade", "Frag Grenade",
                                      "Channelgun", "Slice", "Longfang", "Aim", "Suppression", "Arm Lash", "Venom Grenade", "Frag Grenade", "Frenzy", "Omega Maneuver", ],
            "Bane Spider Soldier" : [ "Single Shot", "Pummel", "Burst", "Wide Area Web Grenade", "Heavy Burst", "Bayonet", "Venom Grenade", "Frag Grenade",
                                      "Bash", "Mace Beam", "Mace Beam Blast", "Build Up", "Mace Beam Volley", "Poisonous Ray", "Pulverize", "Shatter", "Placate", "Crowd Control", ],
        },
        "Secondary": {
            "Crab Spider Training": [ "Wolf Spider Armor", "Combat Training: Defensive", "Combat Training: Offensive", "Tactical Training: Maneuvers",
                                     "Tactical Training: Assault", "Tactical Training: Leadership", "Mental Training", "Call Reinforcements",
                                      "Crab Spider Armor Upgrade", "Fortification", "Serum", "Summon Spiderlings", ],
            "Bane Spider Training": [ "Wolf Spider Armor", "Combat Training: Defensive", "Combat Training: Offensive", "Tactical Training: Maneuvers",
                                     "Tactical Training: Assault", "Tactical Training: Leadership", "Mental Training", "Call Reinforcements",
                                      "Bane Spider Armor Upgrade", "Cloaking Device", "Surveillance", "Web Cocoon", ],
        },
    },
    "Arachnos Widow": {
        'Faction': 'V',
        "Epic": {
            "Leviathan Mastery" : [ "Spirit Shark", "School of Sharks", "Arctic Breath", "Bile Spray", "Summon Guardian", ],
            "Mace Mastery"      : [ "Mace Blast", "Web Envelope", "Disruptor Blast", "Shatter Armor", "Summon Blaster", ],
            "Mu Mastery"        : [ "Mu Lightning", "Electrifying Fences", "Ball Lightning", "Static Discharge", "Summon Striker", ],
            "Soul Mastery"      : [ "Gloom", "Soul Tentacles", "Darkest Night", "Dark Obliteration", "Summon Widow", ],
        },
        "Primary": {
            "Night Widow Training" : [ "Poison Dart", "Swipe", "Strike", "Dart Burst", "Follow Up", "Spin", "Lunge", "Confront",
                                       "Mental Blast", "Build Up", "Smoke Grenade", "Slash", "Eviscerate", "Psychic Scream", ],
            "Fortunata Training"   : [ "Poison Dart", "Swipe", "Strike", "Dart Burst", "Follow Up", "Spin", "Lunge", "Confront",
                                       "Mental Blast", "Telekinetic Blast", "Subdue", "Aim", "Psychic Scream", "Dominate",
                                       "Psionic Tornado", "Scramble Thoughts", "Total Domination", "Psychic Wail", ],
        },
        "Secondary": {
            "Widow Teamwork"     : [ "Combat Training: Defensive", "Combat Training: Offensive", "Tactical Training: Maneuvers", "Indomitable Will",
                                     "Tactical Training: Assault", "Tactical Training: Leadership", "Foresight",
                                     "Mask Presence", "Mental Training", "Mind Link", "Placate", "Tactical Training: Vengeance", "Elude", ],
            "Fortunata Teamwork" : [ "Combat Training: Defensive", "Combat Training: Offensive", "Tactical Training: Maneuvers", "Indomitable Will",
                                     "Tactical Training: Assault", "Tactical Training: Leadership", "Foresight",
                                     "Mask Presence", "Mind Link", "Confuse", "Tactical Training: Vengeance", "Aura of Confusion", ],
        },
    },
    "Blaster": {
        'Faction': 'H',
        "Epic": {
            "Cold Mastery"      : [ "Snow Storm", "Flash Freeze", "Frozen Armor", "Hoarfrost", "Hibernate", ],
            "Electric Mastery"  : [ "Static Discharge", "Shocking Bolt", "Charged Armor", "Surge of Power", "EMP Pulse", ],
            "Flame Mastery"     : [ "Bonfire", "Char", "Fire Shield", "Melt Armor", "Rise of the Phoenix", ],
            "Force Mastery"     : [ "Personal Force Field", "Repulsion Field", "Repulsion Bomb", "Temp Invulnerability", "Force of Nature", ],
            "Munitions Mastery" : [ "Body Armor", "Cryo Freeze Ray", "Sleep Grenade", "Surveillance", "LRM Rocket", ],

            "Leviathan Mastery" : [ "School of Sharks", "Bile Spray", "Knockout Blow", "Shark Skin", "Spirit Shark Jaws", ],
            "Mace Mastery"      : [ "Web Envelope", "Scorpion Shield", "Mace Beam Volley", "Summon Spiderlings", "Web Cocoon", ],
            "Mu Mastery"        : [ "Static Discharge", "Charged Armor", "Electrifying Fences", "Summon Adept", "Electric Shackles", ],
            "Soul Mastery"      : [ "Night Fall", "Dark Embrace", "Oppressive Gloom", "Soul Tentacles", "Soul Storm", ],
        },
        "Primary": {
            "Archery"          : [ "Snap Shot", "Aimed Shot", "Fistful of Arrows", "Blazing Arrow", "Aim", "Explosive Arrow", "Ranged Shot", "Stunning Shot", "Rain of Arrows", ],
            "Assault Rifle"    : [ "Burst", "Slug", "Buckshot", "M30 Grenade", "Beanbag", "Sniper Rifle", "Flamethrower", "Ignite", "Full Auto", ],
            "Beam Rifle"       : [ "Single Shot", "Charged Shot", "Cutting Beam", "Disintegrate", "Aim", "Lancer Shot", "Penetrating Ray", "Piercing Beam", "Overcharge", ],
            "Dark Blast"       : [ "Dark Blast", "Gloom", "Umbral Torrent", "Aim", "Moonbeam", "Tenebrous Tentacles", "Abyssal Gaze", "Life Drain", "Blackstar", ],
            "Dual Pistols"     : [ "Pistols", "Dual Wield", "Empty Clips", "Swap Ammo", "Bullet Rain", "Suppressive Fire", "Executioner's Shot", "Piercing Rounds", "Hail of Bullets",
                                  "Cryo Ammunition", "Incendiary Ammunition", "Chemical Ammunition", ],
            "Electrical Blast" : [ "Charged Bolts", "Lightning Bolt", "Ball Lightning", "Short Circuit", "Charge Up", "Zapp", "Tesla Cage", "Voltaic Sentinel", "Thunderous Blast", ],
            "Energy Blast"     : [ "Power Bolt", "Power Blast", "Energy Torrent", "Power Burst", "Sniper Blast", "Aim", "Power Push", "Explosive Blast", "Nova", ],
            "Fire Blast"       : [ "Flares", "Fire Blast", "Fire Ball", "Rain of Fire", "Fire Breath", "Aim", "Blaze", "Blazing Bolt", "Inferno", ],
            "Ice Blast"        : [ "Ice Bolt", "Ice Blast", "Frost Breath", "Aim", "Freeze Ray", "Ice Storm", "Bitter Ice Blast", "Bitter Freeze Ray", "Blizzard", ],
            "Psychic Blast"    : [ "Psionic Dart", "Mental Blast", "Telekinetic Blast", "Psychic Focus", "Will Domination", "Psionic Lance", "Psionic Tornado", "Scramble Thoughts", "Psychic Wail", ],
            "Radiation Blast"  : [ "Neutrino Bolt", "X-Ray Beam", "Irradiate", "Electron Haze", "Aim", "Proton Volley", "Cosmic Burst", "Neutron Bomb", "Atomic Blast", ],
            "Seismic Blast"    : [ "Encase", "Shatter", "Rock Shards", "Entomb", "Seismic Force", "Upthrust", "Tombstone", "Stalagmite", "Meteor", ],
            "Sonic Attack"     : [ "Shriek", "Scream", "Howl", "Shockwave", "Shout", "Amplify", "Siren's Song", "Screech", "Dreadful Wail", ],
            "Water Blast"      : [ "Aqua Bolt", "Hydro Blast", "Water Burst", "Whirlpool", "Tidal Forces", "Dehydrate", "Water Jet", "Steam Spray", "Geyser", ],
        },
        "Secondary": {
            "Atomic Manipulation"      : [ "Electron Shackles", "Negatron Slam", "Positron Cell", "Ionize", "Beta Decay", "Metabolic Acceleration", "Atom Smasher", "Radioactive Cloud", "Positronic Fist", ],
            "Darkness Manipulation"    : ["Penumbral Grasp", "Smite", "Death Shroud", "Shadow Maul", "Soul Drain", "Touch of the Beyond", "Dark Consumption", "Dark Pit", "Midnight Grasp" ],
            "Devices"                  : [ "Toxic Web Grenade", "Caltrops", "Taser", "Targeting Drone", "Smoke Grenade", "Field Operative", "Trip Mine", "Time Bomb", "Gun Drone", ],
            "Earth Manipulation"       : [ "Stone Prison", "Heavy Mallet", "Salt Crystals", "Build Up", "Tremor", "Mud Bath", "Beryl Crystals", "Fracture", "Seismic Smash", ],
            "Electricity Manipulation" : [ "Electric Fence", "Charged Brawl", "Build Up", "Havoc Punch", "Thunder Strike", "Dynamo", "Power Sink", "Force of Thunder", "Shocking Grasp", ],
            "Energy Manipulation"      : [ "Power Thrust", "Energy Punch", "Build Up", "Bone Smasher", "Energize", "Stun", "Power Boost", "Boost Range", "Total Focus", ],
            "Fire Manipulation"        : [ "Ring of Fire", "Fire Sword", "Combustion", "Fire Sword Circle", "Build Up", "Cauterizing Aura", "Consume", "Burn", "Hot Feet", ],
            "Ice Manipulation"         : [ "Chilblain", "Frozen Fists", "Ice Sword", "Frigid Protection", "Build Up", "Ice Patch", "Shiver", "Freezing Touch", "Frozen Aura", ],
            "Martial Combat"           : [ "Ki Push", "Storm Kick", "Reach for the Limit", "Burst of Speed", "Dragon's Tail", "Reaction Time", "Inner Will", "Throw Sand", "Eagles Claw", ],
            "Mental Manipulation"      : [ "Subdual", "Mind Probe", "World of Confusion", "Psychic Scream", "Concentration", "Drain Psyche", "Scare", "Psychic Shockwave", "Telekinetic Thrust", ],
            "Ninja Training"           : [ "Immobilizing Dart", "Sting of the Wasp", "Choking Powder", "Shinobi", "The Lotus Drops", "Kuji-In Toh", "Smoke Flash", "Blinding Powder", "Golden Dragonfly", ],
            "Plant Manipulation"       : [ "Entangle", "Skewer", "Strangler", "Toxins", "Spore Cloud", "Wild Fortress", "Ripper", "Vines", "Thorn Burst", ],
            "Sonic Manipulation"       : [ "Sonic Thrust", "Strident Echo", "Echo Chamber", "Sound Booster", "Deafening Wave", "Sound Barrier", "Disruption Aura", "Sound Cannon", "Earsplitter", ],
            "Tactical Arrow"           : [ "Electrified Net Arrow", "Glue Arrow", "Ice Arrow", "Upshot", "Flash Arrow", "Eagle Eye", "Gymnastics", "ESD Arrow", "Oil Slick Arrow", ],
            "Temporal Manipulation"    : [ "Time Wall", "Aging Touch", "Time Stop", "Chronos", "End of Time", "Temporal Healing", "Future Pain", "Time Shift", "Time Lord", ],
        },
    },
    'Brute': {
        'Faction': 'V',
        "Epic": {
            "Arctic Mastery"    : [ "Chilblain", "Block of Ice", "Ice Blast", "Shiver", "Ice Storm", ],
            "Earth Mastery"     : [ "Stone Prison", "Salt Crystals", "Fossilize", "Quicksand", "Stalagmites", ],
            "Energy Mastery"    : [ "Superior Conditioning", "Focused Accuracy", "Laser Beam Eyes", "Physical Perfection", "Energy Torrent", ],
            "Pyre Mastery"      : [ "Ring of Fire", "Char", "Fire Blast", "Melt Armor", "Fire Ball", ],

            "Leviathan Mastery" : [ "Spirit Shark", "School of Sharks", "Arctic Breath", "Bile Spray", "Summon Guardian", ],
            "Mace Mastery"      : [ "Mace Blast", "Web Envelope", "Disruptor Blast", "Focused Accuracy", "Summon Blaster", ],
            "Mu Mastery"        : [ "Mu Lightning", "Electrifying Fences", "Ball Lightning", "Static Discharge", "Summon Striker", ],
            "Soul Mastery"      : [ "Gloom", "Soul Tentacles", "Darkest Night", "Dark Obliteration", "Summon Widow", ],
        },
        "Primary": {
            "Battle Axe"      : [ "Beheader", "Chop", "Gash", "Build Up", "Swoop", "Taunt", "Whirling Axe", "Cleave", "Pendulum", ],
            "Broad Sword"     : [ "Hack", "Slash", "Slice", "Build Up", "Parry", "Taunt", "Whirling Sword", "Disembowel", "Head Splitter", ],
            "Claws"           : [ "Swipe", "Strike", "Slash", "Spin", "Follow Up", "Taunt", "Focus", "Eviscerate", "Shockwave", ],
            "Dark Melee"      : [ "Shadow Punch", "Smite", "Shadow Maul", "Touch of Fear", "Siphon Life", "Taunt", "Dark Consumption", "Soul Drain", "Midnight Grasp", ],
            "Dual Blades"     : [ "Nimble Slash", "Power Slice", "Ablating Strike", "Typhoon's Edge", "Blinding Feint", "Taunt", "Vengeful Slice", "Sweeping Strike", "One Thousand Cuts", ],
            "Electric Melee"  : [ "Charged Brawl", "Havoc Punch", "Jacobs Ladder", "Build Up", "Thunder Strike", "Taunt", "Chain Induction", "Lightning Clap", "Lightning Rod", ],
            "Energy Melee"    : [ "Barrage", "Energy Punch", "Bone Smasher", "Build Up", "Whirling Hands", "Taunt", "Total Focus", "Power Crash", "Energy Transfer", ],
            "Fiery Melee"     : [ "Scorch", "Fire Sword", "Cremate", "Build Up", "Incinerate", "Taunt", "Breath of Fire", "Fire Sword Circle", "Greater Fire Sword", ],
            "Ice Melee"       : [ "Frozen Fists", "Ice Sword", "Frost", "Build Up", "Ice Patch", "Taunt", "Greater Ice Sword", "Freezing Touch", "Frozen Aura",],
            "Katana"          : [ "Sting of the Wasp", "Gambler's Cut", "Flashing Steel", "Build Up", "Divine Avalanche", "Dragon's Roar", "The Lotus Drops", "Soaring Dragon", "Golden Dragonfly", ],
            "Kinetic Melee"   : [ "Quick Strike", "Body Blow", "Smashing Blow", "Power Siphon", "Repulsing Torrent", "Taunt", "Burst", "Focused Burst", "Concentrated Strike", ],
            "Martial Arts"    : [ "Thunder Kick", "Storm Kick", "Cobra Strike", "Focus Chi", "Crane Kick", "Warrior's Provocation", "Crippling Axe Kick", "Dragon's Tail", "Eagle's Claw", ],
            "Psionic Melee"   : [ "Mental Strike", "Psi Blade", "Telekinetic Blow", "Concentration", "Psi Blade Sweep", "Taunt", "Boggle", "Greater Psi Blade", "Mass Levitate", ],
            "Radiation Melee" : [ "Contaminated Strike", "Radioactive Smash", "Proton Sweep", "Fusion", "Radiation Siphon", "Taunt", "Irradiated Ground", "Devastating Blow", "Atom Smasher", ],
            "Savage Melee"    : [ "Savage Strike", "Maiming Slash", "Shred", "Blood Thirst", "Vicious Slash", "Taunt", "Rending Flurry", "Hemorrhage", "Savage Leap", ],
            "Spines"          : [ "Barb Swipe", "Lunge", "Spine Burst", "Build Up", "Impale", "Taunt", "Quills", "Ripper", "Throw Spines", ],
            "Staff Fighting"  : [ "Mercurial Blow", "Precise Strike", "Guarded Spin", "Eye of the Storm", "Staff Mastery", "Taunt", "Serpent's Reach", "Innocuous Strikes", "Sky Splitter", 'Form of the Body', 'Form of the Mind', 'Form of the Soul', ],
            "Stone Melee"     : [ "Stone Fist", "Stone Mallet", "Heavy Mallet", "Build Up", "Fault", "Taunt", "Seismic Smash", "Hurl Boulder", "Tremor", ],
            "Street Justice"  : [ "Initial Strike", "Heavy Blow", "Sweeping Cross", "Combat Readiness", "Rib Cracker", "Taunt", "Spinning Strike", "Shin Breaker", "Crushing Uppercut", ],
            "Super Strength"  : [ "Jab", "Punch", "Haymaker", "Hand Clap", "Knockout Blow", "Taunt", "Rage", "Hurl", "Foot Stomp", ],
            "Titan Weapons"   : [ "Defensive Sweep", "Crushing Blow", "Titan Sweep", "Build Momentum", "Follow Through", "Taunt", "Rend Armor", "Whirling Smash", "Arc of Destruction", ],
            "War Mace"        : [ "Bash", "Pulverize", "Jawbreaker", "Build Up", "Clobber", "Taunt", "Whirling Mace", "Shatter", "Crowd Control", ],
        },
        "Secondary": {
            "Bio Armor"       : [ "Hardened Carapace", "Inexhaustible", "Environmental Modification", "Adaptation", "Ablative Carapace", "Evolving Armor", "DNA Siphon", "Genetic Contamination", "Parasitic Aura", "Efficient Adaptation", "Defensive Adaptation", "Offensive Adaptation", ],
            "Dark Armor"      : [ "Dark Embrace", "Death Shroud", "Murky Cloud", "Obsidian Shield", "Dark Regeneration", "Cloak of Darkness", "Cloak of Fear", "Oppressive Gloom", "Soul Transfer", ],
            "Electric Armor"  : [ "Charged Armor", "Lightning Field", "Conductive Shield", "Static Shield", "Grounded", "Lightning Reflexes", "Energize", "Power Sink", "Power Surge ", ],
            "Energy Aura"     : [ "Kinetic Shield", "Dampening Field", "Power Shield", "Entropic Aura", "Energy Protection", "Energy Cloak", "Energy Drain", "Energize", "Overload", ],
            "Fiery Aura"      : [ "Fire Shield", "Blazing Aura", "Healing Flames", "Temperature Protection", "Plasma Shield", "Consume", "Burn", "Fiery Embrace", "Rise of the Phoenix", ],
            "Ice Armor"       : [ "Frozen Armor", "Hoarfrost", "Chilling Embrace", "Wet Ice", "Glacial Armor", "Energy Absorption", "Permafrost", "Icicles", "Hibernate", ],
            "Invulnerability" : [ "Resist Physical Damage", "Temp Invulnerability", "Dull Pain", "Resist Elements", "Unyielding", "Resist Energies", "Invincibility", "Tough Hide", "Unstoppable", ],
            "Radiation Armor" : [ "Alpha Barrier", "Gamma Boost", "Proton Armor", "Fallout Shelter", "Radiation Therapy", "Beta Decay", "Particle Shielding", "Ground Zero", "Meltdown", ],
            "Regeneration"    : [ "Fast Healing", "Reconstruction", "Quick Recovery", "Dull Pain", "Integration", "Resilience", "Instant Healing", "Revive", "Moment of Glory", ],
            "Shield Defense"  : [ "Deflection", "Battle Agility", "True Grit", "Active Defense", "Against All Odds", "Phalanx Fighting", "Grant Cover", "Shield Charge", "One with the Shield", ],
            "Stone Armor"     : [ "Rock Armor", "Stone Skin", "Earth's Embrace", "Mud Pots", "Rooted", "Brimstone Armor", "Crystal Armor", "Minerals", "Granite Armor", ],
            "Super Reflexes"  : [ "Focused Fighting", "Focused Senses", "Agile", "Practiced Brawler", "Dodge", "Evasion", "Lucky", "Quickness", "Elude", ],
            "Willpower"       : [ "High Pain Tolerance", "Mind Over Body", "Fast Healing", "Indomitable Will", "Rise to the Challenge", "Quick Recovery", "Heightened Senses", "Resurgence", "Strength of Will", ],
        },
    },
    'Controller': {
        'Faction': 'H',
        "Epic": {
            "Fire Mastery"          : [ "Fire Blast", "Fire Ball", "Fire Shield", "Rise of the Phoenix", "Consume", ],
            "Ice Mastery"           : [ "Ice Blast", "Hibernate", "Frozen Armor", "Frost Breath", "Ice Storm", ],
            "Primal Forces Mastery" : [ "Power Blast", "Conserve Power", "Temp Invulnerability", "Energy Torrent", "Power Boost", ],
            "Psionic Mastery"       : [ "Mental Blast", "Indomitable Will", "Mind Over Body", "World of Confusion", "Psionic Tornado", ],
            "Stone Mastery"         : [ "Hurl Boulder", "Fissure", "Rock Armor", "Seismic Smash", "Earth's Embrace", ],

            "Leviathan Mastery"     : [ "Water Spout", "Bile Spray", "Hibernate", "Shark Skin", "Summon Coralax", ],
            "Mace Mastery"          : [ "Poisonous Ray", "Scorpion Shield", "Disruptor Blast", "Focused Accuracy", "Summon Tarantula", ],
            "Mu Mastery"            : [ "Power Sink", "Charged Armor", "Ball Lightning", "Surge of Power", "Summon Guardian", ],
            "Soul Mastery"          : [ "Dark Consumption", "Dark Embrace", "Dark Obliteration", "Soul Drain", "Summon Seer", ]
        },
        "Primary": {
            "Darkness Control" : [ "Shadowy Binds", "Dark Grasp", "Living Shadows", "Possess", "Fearsome Stare", "Heart of Darkness", "Haunt", "Shadow Field", "Umbra Beast", ],
            "Earth Control"    : [ "Stone Prison", "Fossilize", "Stone Cages", "Quicksand", "Salt Crystals", "Stalagmites", "Earthquake", "Volcanic Gasses", "Animate Stone", ],
            "Electric Control" : [ "Electric Fence", "Tesla Cage", "Chain Fences", "Jolting Chain", "Conductive Aura", "Static Field", "Paralyzing Blast", "Synaptic Overload", "Gremlins", ],
            "Fire Control"     : [ "Ring of Fire", "Char", "Fire Cages", "Smoke", "Hot Feet", "Flashfire", "Cinders", "Bonfire", "Fire Imps", ],
            "Gravity Control"  : [ "Crush", "Lift", "Gravity Distortion", "Propel", "Crushing Field", "Dimension Shift", "Gravity Distortion Field", "Wormhole", "Singularity", ],
            "Ice Control"      : [ "Chilblain", "Block of Ice", "Frostbite", "Arctic Air", "Cold Snap", "Ice Slick", "Flash Freeze", "Glacier", "Jack Frost", ],
            "Illusion Control" : [ "Spectral Wounds", "Blind", "Deceive", "Flash", "Superior Invisibility", "Group Invisibility", "Phantom Army", "Spectral Terror", "Phantasm", ],
            "Mind Control"     : [ "Mesmerize", "Levitate", "Dominate", "Confuse", "Mass Hypnosis", "Telekinesis", "Total Domination", "Terrify", "Mass Confusion", ],
            "Plant Control"    : [ "Entangle", "Strangler", "Roots", "Spore Burst", "Seeds of Confusion", "Spirit Tree", "Vines", "Carrion Creepers", "Fly Trap", ],
            "Symphony Control" : [ "Melodic Binding", "Hymn of Dissonance", "Aria of Stasis", "Impassioned Serenade", "Dreadful Discord", "Enfeebling Lullaby", "Confounding Chant", "Chords of Despair", "Reverberant", ],
            # "Wind Control"     : [ "Updraft", "Downdraft", "Breathless", "Wind Shear", "Thundergust", "Microburst", "Keening Winds", "Vacuum", "Vortex", ],
        },
        "Secondary": {
            "Cold Domination"     : [ "Infrigidate", "Ice Shield", "Snow Storm", "Glacial Shield", "Frostwork", "Arctic Fog", "Benumb", "Sleet", "Heat Loss", ],
            "Darkness Affinity"   : [ "Twilight Grasp", "Tar Patch", "Darkest Night", "Howling Twilight", "Shadow Fall", "Fade", "Soul Absorption", "Black Hole", "Dark Servant", ],
            "Electrical Affinity" : [ "Shock", "Rejuvenating Circuit", "Galvanic Sentinel", "Energizing Circuit", "Faraday Cage", "Empowering Circuit", "Defibrillate", "Insulating Circuit", "Amp Up", ],
            "Empathy"             : [ "Healing Aura", "Heal Other", "Absorb Pain", "Resurrect", "Clear Mind", "Fortitude", "Recovery Aura", "Regeneration Aura", "Adrenalin Boost", ],
            "Force Field"         : [ "Personal Force Field", "Deflection Shield", "Force Bolt", "Insulation Shield", "Detention Field", "Dispersion Bubble", "Repulsion Field", "Repulsion Bomb", "Force Bubble", ],
            "Kinetics"            : [ "Transfusion", "Siphon Power", "Repel", "Siphon Speed", "Increase Density", "Speed Boost", "Inertial Reduction", "Transference", "Fulcrum Shift", ],
            "Nature Affinity"     : [ "Corrosive Enzymes", "Regrowth", "Wild Growth", "Spore Cloud", "Lifegiving Spores", "Wild Bastion", "Rebirth", "Entangling Aura", "Overgrowth", ],
            "Pain Domination"     : [ "Nullify Pain", "Soothe", "Share Pain", "Conduit of Pain", "Enforced Morale", "Soothing Aura", "World of Pain", "Anguishing Cry", "Painbringer", ],
            "Poison"              : [ "Alkaloid", "Envenom", "Weaken", "Neurotoxic Breath", "Elixir of Life", "Antidote", "Paralytic Poison", "Poison Trap", "Venomous Gas", ],
            "Radiation Emission"  : [ "Radiant Aura", "Radiation Infection", "Accelerate Metabolism", "Enervating Field", "Mutation", "Lingering Radiation", "Choking Cloud", "Fallout", "EM Pulse", ],
            "Sonic Resonance"     : [ "Sonic Siphon", "Sonic Barrier", "Sonic Haven", "Sonic Cage", "Disruption Field", "Sonic Dispersion", "Sonic Repulsion", "Clarity", "Liquefy", ],
            "Storm Summoning"     : [ "Gale", "O2 Boost", "Snow Storm", "Steamy Mist", "Freezing Rain", "Hurricane", "Thunder Clap", "Tornado", "Lightning Storm", ],
            "Thermal Radiation"   : [ "Warmth", "Thermal Shield", "Cauterize", "Plasma Shield", "Power of the Phoenix", "Thaw", "Forge", "Heat Exhaustion", "Melt Armor", ],
            "Time Manipulation"   : [ "Time Crawl", "Temporal Mending", "Time's Juncture", "Temporal Selection", "Distortion Field", "Time Stop", "Farsight", "Slowed Response", "Chrono Shift", ],
            "Traps"               : [ "Web Grenade", "Caltrops", "Triage Beacon", "Acid Mortar", "Force Field Generator", "Poison Trap", "Seeker Drones", "Trip Mine", "Time Bomb", ],
            "Trick Arrow"         : [ "Entangling Arrow", "Flash Arrow", "Glue Arrow", "Ice Arrow", "Poison Gas Arrow", "Acid Arrow", "Disruption Arrow", "Oil Slick Arrow", "EMP Arrow", ],
        },
    },
    'Corruptor': {
        'Faction': 'V',
        "Epic": {
            "Dark Mastery"        : [ "Oppressive Gloom", "Dark Consumption", "Dark Embrace", "Soul Transfer", "Soul Drain", ],
            "Electricity Mastery" : [ "Electric Fence", "Thunder Strike", "Charged Armor", "Shocking Bolt", "Power Sink", ],
            "Power Mastery"       : [ "Conserve Power", "Power Build Up", "Temp Invulnerability", "Force of Nature", "Total Focus", ],
            "Psychic Mastery"     : [ "Dominate", "Mass Hypnosis", "Mind Over Body", "World of Confusion", "Telekinesis", ],
            "Flame Mastery"       : [ "Consume", "Char", "Fire Shield", "Rise of the Phoenix", "Greater Fire Sword", ],

            "Leviathan Mastery"   : [ "School of Sharks", "Shark Skin", "Hibernate", "Spirit Shark Jaws", "Summon Coralax", ],
            "Mace Mastery"        : [ "Web Envelope", "Scorpion Shield", "Focused Accuracy", "Web Cocoon", "Summon Disruptor", ],
            "Mu Mastery"          : [ "Power Sink", "Charged Armor", "Conserve Power", "Electric Shackles", "Summon Adept", ],
            "Soul Mastery"        : [ "Soul Drain", "Dark Embrace", "Power Boost", "Soul Storm", "Summon Mistress", ],
        },
        "Primary": {
            "Archery"          : [ "Snap Shot", "Aimed Shot", "Fistful of Arrows", "Blazing Arrow", "Aim", "Explosive Arrow", "Ranged Shot", "Stunning Shot", "Rain of Arrows", ],
            "Assault Rifle"    : [ "Burst", "Slug", "Buckshot", "M30 Grenade", "Beanbag", "Sniper Rifle", "Flamethrower", "Ignite", "Full Auto", ],
            "Beam Rifle"       : [ "Single Shot", "Charged Shot", "Cutting Beam", "Disintegrate", "Aim", "Lancer Shot", "Penetrating Ray", "Piercing Beam", "Overcharge", ],
            "Dark Blast"       : [ "Dark Blast", "Gloom", "Moonbeam", "Dark Pit", "Tenebrous Tentacles", "Night Fall", "Torrent", "Life Drain", "Blackstar", ],
            "Dual Pistols"     : [ "Pistols", "Dual Wield", "Empty Clips", "Swap Ammo", "Bullet Rain", "Suppressive Fire", "Executioner's Shot", "Piercing Rounds", "Hail of Bullets",
                                  "Cryo Ammunition", "Incendiary Ammunition", "Chemical Ammunition", ],
            "Electrical Blast" : [ "Charged Bolts", "Lightning Bolt", "Ball Lightning", "Short Circuit", "Charge Up", "Zapp", "Tesla Cage", "Voltaic Sentinel", "Thunderous Blast", ],
            "Energy Blast"     : [ "Power Bolt", "Power Blast", "Energy Torrent", "Power Burst", "Sniper Blast", "Aim", "Power Push", "Explosive Blast", "Nova", ],
            "Fire Blast"       : [ "Flares", "Fire Blast", "Fire Ball", "Rain of Fire", "Fire Breath", "Aim", "Blaze", "Blazing Bolt", "Inferno", ],
            "Ice Blast"        : [ "Ice Bolt", "Ice Blast", "Frost Breath", "Aim", "Freeze Ray", "Ice Storm", "Bitter Ice Blast", "Bitter Freeze Ray", "Blizzard", ],
            "Psychic Blast"    : [ "Psionic Dart", "Mental Blast", "Telekinetic Blast", "Psychic Focus", "Will Domination", "Psionic Lance", "Psionic Tornado", "Scramble Thoughts", "Psychic Wail", ],
            "Radiation Blast"  : [ "Neutrino Bolt", "X-Ray Beam", "Irradiate", "Electron Haze", "Proton Volley", "Aim", "Cosmic Burst", "Neutron Bomb", "Atomic Blast", ],
            "Sonic Attack"     : [ "Shriek", "Scream", "Howl", "Shockwave", "Shout", "Amplify", "Siren's Song", "Screech", "Dreadful Wail", ],
            "Water Blast"      : [ "Aqua Bolt", "Hydro Blast", "Water Burst", "Whirlpool", "Tidal Forces", "Dehydrate", "Water Jet", "Steam Spray", "Geyser", ],
        },
        "Secondary": {
            "Cold Domination"     : [ "Infrigidate", "Ice Shield", "Snow Storm", "Glacial Shield", "Frostwork", "Arctic Fog", "Benumb", "Sleet", "Heat Loss", ],
            "Dark Miasma"         : [ "Twilight Grasp", "Tar Patch", "Darkest Night", "Howling Twilight", "Shadow Fall", "Fearsome Stare", "Petrifying Gaze", "Black Hole", "Dark Servant", ],
            "Electrical Affinity" : [ "Shock", "Rejuvenating Circuit", "Galvanic Sentinel", "Energizing Circuit", "Faraday Cage", "Empowering Circuit", "Defibrillate", "Insulating Circuit", "Amp Up", ],
            "Empathy"             : [ "Healing Aura", "Heal Other", "Absorb Pain", "Resurrect", "Clear Mind", "Fortitude", "Recovery Aura", "Regeneration Aura", "Adrenalin Boost", ],
            "Force Field"         : [ "Personal Force Field", "Deflection Shield", "Force Bolt", "Insulation Shield", "Detention Field", "Dispersion Bubble", "Repulsion Field", "Repulsion Bomb", "Force Bubble", ],
            "Kinetics"            : [ "Transfusion", "Siphon Power", "Repel", "Siphon Speed", "Increase Density", "Speed Boost", "Inertial Reduction", "Transference", "Fulcrum Shift", ],
            "Nature Affinity"     : [ "Corrosive Enzymes", "Regrowth", "Wild Growth", "Spore Cloud", "Lifegiving Spores", "Wild Bastion", "Rebirth", "Entangling Aura", "Overgrowth", ],
            "Pain Domination"     : [ "Nullify Pain", "Soothe", "Share Pain", "Conduit of Pain", "Enforced Morale", "Soothing Aura", "World of Pain", "Anguishing Cry", "Painbringer", ],
            "Poison"              : [ "Alkaloid", "Envenom", "Weaken", "Neurotoxic Breath", "Elixir of Life", "Antidote", "Paralytic Poison", "Poison Trap", "Venomous Gas", ],
            "Radiation Emission"  : [ "Radiant Aura", "Radiation Infection", "Accelerate Metabolism", "Enervating Field", "Mutation", "Lingering Radiation", "Choking Cloud", "Fallout", "EM Pulse", ],
            "Sonic Resonance"     : [ "Sonic Siphon", "Sonic Barrier", "Sonic Haven", "Sonic Cage", "Disruption Field", "Sonic Dispersion", "Sonic Repulsion", "Clarity", "Liquefy", ],
            "Storm Summoning"     : [ "Gale", "O2 Boost", "Snow Storm", "Steamy Mist", "Freezing Rain", "Hurricane", "Thunder Clap", "Tornado", "Lightning Storm", ],
            "Thermal Radiation"   : [ "Warmth", "Fire Shield", "Cauterize", "Plasma Shield", "Power of the Phoenix", "Thaw", "Forge", "Heat Exhaustion", "Melt Armor", ],
            "Time Manipulation"   : [ "Time Crawl", "Temporal Mending", "Time's Juncture", "Temporal Selection", "Distortion Field", "Time Stop", "Farsight", "Slowed Response", "Chrono Shift", ],
            "Traps"               : [ "Web Grenade", "Caltrops", "Triage Beacon", "Acid Mortar", "Force Field Generator", "Poison Trap", "Seeker Drones", "Trip Mine", "Time Bomb", ],
            "Trick Arrow"         : [ "Entangling Arrow", "Flash Arrow", "Glue Arrow", "Ice Arrow", "Poison Gas Arrow", "Acid Arrow", "Disruption Arrow", "Oil Slick Arrow", "EMP Arrow", ],
        },
    },
    'Defender': {
        'Faction': 'H',
        "Epic": {
            "Dark Mastery"        : [ "Oppressive Gloom", "Dark Consumption", "Dark Embrace", "Soul Transfer", "Soul Drain", ],
            "Electricity Mastery" : [ "Electric Fence", "Thunder Strike", "Charged Armor", "Shocking Bolt", "Power Sink", ],
            "Power Mastery"       : [ "Conserve Power", "Power Build Up", "Temp Invulnerability", "Force of Nature", "Total Focus", ],
            "Psychic Mastery"     : [ "Dominate", "Mass Hypnosis", "Mind Over Body", "World of Confusion", "Telekinesis", ],
            "Flame Mastery"       : [ "Consume", "Char", "Fire Shield", "Rise of the Phoenix", "Greater Fire Sword", ],

            "Leviathan Mastery"   : [ "School of Sharks", "Shark Skin", "Hibernate", "Spirit Shark Jaws", "Summon Coralax", ],
            "Mace Mastery"        : [ "Web Envelope", "Scorpion Shield", "Focused Accuracy", "Web Cocoon", "Summon Disruptor", ],
            "Mu Mastery"          : [ "Power Sink", "Charged Armor", "Conserve Power", "Electric Shackles", "Summon Adept", ],
            "Soul Mastery"        : [ "Soul Drain", "Dark Embrace", "Power Boost", "Soul Storm", "Summon Mistress", ],
        },
        "Primary": {
            "Cold Domination"     : [ "Infrigidate", "Ice Shield", "Snow Storm", "Glacial Shield", "Frostwork", "Arctic Fog", "Benumb", "Sleet", "Heat Loss", ],
            "Dark Miasma"         : [ "Twilight Grasp", "Tar Patch", "Darkest Night", "Howling Twilight", "Shadow Fall", "Fearsome Stare", "Petrifying Gaze", "Black Hole", "Dark Servant", ],
            "Electrical Affinity" : [ "Shock", "Rejuvenating Circuit", "Galvanic Sentinel", "Energizing Circuit", "Faraday Cage", "Empowering Circuit", "Defibrillate", "Insulating Circuit", "Amp Up", ],
            "Empathy"             : [ "Healing Aura", "Heal Other", "Absorb Pain", "Resurrect", "Clear Mind", "Fortitude", "Recovery Aura", "Adrenalin Boost", "Regeneration Aura", ],
            "Force Field"         : [ "Personal Force Field", "Deflection Shield", "Force Bolt", "Insulation Shield", "Detention Field", "Dispersion Bubble", "Repulsion Field", "Repulsion Bomb", "Force Bubble", ],
            "Kinetics"            : [ "Transfusion", "Siphon Power", "Repel", "Siphon Speed", "Increase Density", "Speed Boost", "Inertial Reduction", "Transference", "Fulcrum Shift", ],
            "Nature Affinity"     : [ "Corrosive Enzymes", "Regrowth", "Wild Growth", "Spore Cloud", "Lifegiving Spores", "Wild Bastion", "Rebirth", "Entangling Aura", "Overgrowth", ],
            "Pain Domination"     : [ "Nullify Pain", "Soothe", "Share Pain", "Conduit of Pain", "Enforced Morale", "Soothing Aura", "World of Pain", "Anguishing Cry", "Painbringer", ],
            "Poison"              : [ "Alkaloid", "Envenom", "Weaken", "Neurotoxic Breath", "Elixir of Life", "Antidote", "Paralytic Poison", "Poison Trap", "Venomous Gas", ],
            "Radiation Emission"  : [ "Radiant Aura", "Radiation Infection", "Accelerate Metabolism", "Enervating Field", "Mutation", "Lingering Radiation", "Choking Cloud", "Fallout", "EM Pulse", ],
            "Sonic Resonance"     : [ "Sonic Siphon", "Sonic Barrier", "Sonic Haven", "Sonic Cage", "Disruption Field", "Sonic Dispersion", "Sonic Repulsion", "Clarity", "Liquefy", ],
            "Storm Summoning"     : [ "Gale", "O2 Boost", "Snow Storm", "Steamy Mist", "Freezing Rain", "Hurricane", "Thunder Clap", "Tornado", "Lightning Storm", ],
            "Thermal Radiation"   : [ "Warmth", "Fire Shield", "Cauterize", "Plasma Shield", "Power of the Phoenix", "Thaw", "Forge", "Heat Exhaustion", "Melt Armor", ],
            "Time Manipulation"   : [ "Time Crawl", "Temporal Mending", "Time's Juncture", "Temporal Selection", "Distortion Field", "Time Stop", "Farsight", "Slowed Response", "Chrono Shift", ],
            "Traps"               : [ "Web Grenade", "Caltrops", "Triage Beacon", "Acid Mortar", "Force Field Generator", "Poison Trap", "Seeker Drones", "Trip Mine", "Time Bomb", ],
            "Trick Arrow"         : [ "Entangling Arrow", "Flash Arrow", "Glue Arrow", "Ice Arrow", "Poison Gas Arrow", "Acid Arrow", "Disruption Arrow", "Oil Slick Arrow", "EMP Arrow", ],
        },
        "Secondary": {
            "Archery"          : [ "Snap Shot", "Aimed Shot", "Fistful of Arrows", "Blazing Arrow", "Aim", "Explosive Arrow", "Ranged Shot", "Stunning Shot", "Rain of Arrows", ],
            "Assault Rifle"    : [ "Burst", "Slug", "Buckshot", "M30 Grenade", "Beanbag", "Sniper Rifle", "Flamethrower", "Ignite", "Full Auto", ],
            "Beam Rifle"       : [ "Single Shot", "Charged Shot", "Cutting Beam", "Disintegrate", "Aim", "Lancer Shot", "Penetrating Ray", "Piercing Beam", "Overcharge", ],
            "Dark Blast"       : [ "Dark Blast", "Gloom", "Moonbeam", "Dark Pit", "Tenebrous Tentacles", "Night Fall", "Torrent", "Life Drain", "Blackstar", ],
            "Dual Pistols"     : [ "Pistols", "Dual Wield", "Empty Clips", "Swap Ammo", "Bullet Rain", "Suppressive Fire", "Executioner's Shot", "Piercing Rounds", "Hail of Bullets",
                                  "Cryo Ammunition", "Incendiary Ammunition", "Chemical Ammunition", ],
            "Electrical Blast" : [ "Charged Bolts", "Lightning Bolt", "Ball Lightning", "Short Circuit", "Charge Up", "Zapp", "Tesla Cage", "Voltaic Sentinel", "Thunderous Blast", ],
            "Energy Blast"     : [ "Power Bolt", "Power Blast", "Energy Torrent", "Power Burst", "Sniper Blast", "Aim", "Power Push", "Explosive Blast", "Nova", ],
            "Fire Blast"       : [ "Flares", "Fire Blast", "Fire Ball", "Rain of Fire", "Fire Breath", "Aim", "Blaze", "Blazing Bolt", "Inferno", ],
            "Ice Blast"        : [ "Ice Bolt", "Ice Blast", "Frost Breath", "Aim", "Freeze Ray", "Ice Storm", "Bitter Ice Blast", "Bitter Freeze Ray", "Blizzard", ],
            "Psychic Blast"    : [ "Psionic Dart", "Mental Blast", "Telekinetic Blast", "Psychic Focus", "Will Domination", "Psionic Lance", "Psionic Tornado", "Scramble Thoughts", "Psychic Wail", ],
            "Radiation Blast"  : [ "Neutrino Bolt", "X-Ray Beam", "Irradiate", "Electron Haze", "Proton Volley", "Aim", "Cosmic Burst", "Neutron Bomb", "Atomic Blast", ],
            "Seismic Blast"    : [ "Encase", "Shatter", "Rock Shards", "Entomb", "Seismic Force", "Upthrust", "Tombstone", "Stalagmite", "Meteor", ],
            "Sonic Attack"     : [ "Shriek", "Scream", "Howl", "Shockwave", "Shout", "Amplify", "Siren's Song", "Screech", "Dreadful Wail", ],
            "Water Blast"      : [ "Aqua Bolt", "Hydro Blast", "Water Burst", "Whirlpool", "Tidal Forces", "Dehydrate", "Water Jet", "Steam Spray", "Geyser", ],
        },
    },
    'Dominator': {
        'Faction': 'V',
        "Epic": {
            "Fire Mastery"          : [ "Rain of Fire", "Fire Ball", "Fire Shield", "Rise of the Phoenix", "Melt Armor", ],
            "Ice Mastery"           : [ "Sleet", "Hibernate", "Frozen Armor", "Hoarfrost", "Ice Storm", ],
            "Primal Forces Mastery" : [ "Energy Transfer", "Conserve Power", "Temp Invulnerability", "Energy Torrent", "Explosive Blast", ],
            "Psionic Mastery"       : [ "Link Minds", "Indomitable Will", "Mind Over Body", "World of Confusion", "Psionic Tornado", ],

            "Leviathan Mastery"     : [ "Water Spout", "Bile Spray", "Hibernate", "Shark Skin", "Summon Coralax", ],
            "Mace Mastery"          : [ "Poisonous Ray", "Scorpion Shield", "Disruptor Blast", "Personal Force Field", "Summon Tarantula", ],
            "Mu Mastery"            : [ "Power Sink", "Charged Armor", "Ball Lightning", "Surge of Power", "Summon Guardian", ],
            "Soul Mastery"          : [ "Dark Consumption", "Dark Embrace", "Dark Obliteration", "Soul Drain", "Summon Seer", ]
        },
        "Primary": {
            "Darkness Control" : [ "Shadowy Binds", "Dark Grasp", "Living Shadows", "Possess", "Fearsome Stare", "Heart of Darkness", "Haunt", "Shadow Field", "Umbra Beast", ],
            "Earth Control"    : [ "Stone Prison", "Fossilize", "Stone Cages", "Quicksand", "Salt Crystals", "Stalagmites", "Earthquake", "Volcanic Gasses", "Animate Stone", ],
            "Electric Control" : [ "Electric Fence", "Tesla Cage", "Chain Fences", "Jolting Chain", "Conductive Aura", "Static Field", "Paralyzing Blast", "Synaptic Overload", "Gremlins", ],
            "Fire Control"     : [ "Ring of Fire", "Char", "Fire Cages", "Smoke", "Hot Feet", "Flashfire", "Cinders", "Bonfire", "Fire Imps", ],
            "Gravity Control"  : [ "Crush", "Lift", "Gravity Distortion", "Propel", "Crushing Field", "Dimension Shift", "Gravity Distortion Field", "Wormhole", "Singularity", ],
            "Ice Control"      : [ "Chilblain", "Block of Ice", "Frostbite", "Arctic Air", "Cold Snap", "Ice Slick", "Flash Freeze", "Glacier", "Jack Frost", ],
            "Mind Control"     : [ "Mesmerize", "Levitate", "Dominate", "Confuse", "Mass Hypnosis", "Telekinesis", "Total Domination", "Terrify", "Mass Confusion", ],
            "Plant Control"    : [ "Entangle", "Strangler", "Roots", "Spore Burst", "Seeds of Confusion", "Spirit Tree", "Vines", "Carrion Creepers", "Fly Trap", ],
            "Symphony Control" : [ "Melodic Binding", "Hymn of Dissonance", "Aria of Stasis", "Impassioned Serenade", "Dreadful Discord", "Enfeebling Lullaby", "Confounding Chant", "Chords of Despair", "Reverberant", ],
            # "Wind Control"     : [ "Updraft", "Downdraft", "Breathless", "Wind Shear", "Thundergust", "Microburst", "Keening Winds", "Vacuum", "Vortex", ],
        },
        "Secondary": {
            "Dark Assault"        : [ "Dark Blast", "Smite", "Gloom", "Night Fall", "Gather Shadows", "Engulfing Darkness", "Life Drain", "Moon Beam", "Midnight Grasp", ],
            "Earth Assault"       : [ "Stone Spears", "Stone Mallet", "Tremor", "Hurl Boulder", "Power Up", "Heavy Mallet", "Seismic Smash", "Mud Pots", "Fissure", ],
            "Electricity Assault" : [ "Charged Bolts", "Charged Brawl", "Lightning Bolt", "Havoc Punch", "Build Up", "Zapp", "Static Discharge", "Thunder Strike", "Voltaic Sentinel", ],
            "Energy Assault"      : [ "Power Bolt", "Bone Smasher", "Power Push", "Power Blast", "Power Up", "Whirling Hands", "Total Focus", "Sniper Blast", "Power Burst", ],
            "Fiery Assault"       : [ "Flares", "Incinerate", "Fire Breath", "Fire Blast", "Embrace of Fire", "Combustion", "Consume", "Blazing Bolt", "Blaze", ],
            "Icy Assault"         : [ "Ice Bolt", "Ice Sword", "Ice Sword Circle", "Ice Blast", "Power Up", "Frost Breath", "Chilling Embrace", "Ice Slash", "Bitter Ice Blast", ],
            "Martial Assault"     : [ "Shuriken Throw", "Thunder Kick", "Trick Shot", "Spinning Kick", "Envenomed Blades", "Dragon's Tail", "Caltrops", "Masterful Throw", "Explosive Shuriken", ],
            "Psionic Assault"     : [ "Psionic Dart", "Mind Probe", "Telekinetic Thrust", "Mental Blast", "Psychic Scream", "Drain Psyche", "Subdue", "Psionic Lance", "Psychic Shockwave", ],
            "Radioactive Assault" : [ "Neutrino Bolt", "Contaminated Strike", "X-Ray Beam", "Electron Haze", "Fusion", "Radiation Siphon", "Atom Smasher", "Proton Volley", "Devastating Blow", ],
            "Savage Assault"      : [ "Call Swarm", "Maiming Slash", "Vicious Slash", "Unkindness", "Spot Prey", "Rending Flurry", "Blood Craze", "Call Hawk", "Feral Charge", ],
            "Sonic Assault"       : [ "Shriek", "Strident Echo", "Scream", "Shockwave", "Bass Boost", "Deafening Wave", "Disruption Aura", "Shout", "Earsplitter", ],
            "Thorny Assault"      : [ "Thorny Darts", "Skewer", "Fling Thorns", "Impale", "Build Up", "Thorn Burst", "Thorntrops", "Ripper", "Thorn Barrage", ],
        },
    },
    'Mastermind': {
        'Faction': 'V',
        "Epic": {
            "Chill Mastery"     : [ "Ice Blast", "Flash Freeze", "Hoarfrost", "Frozen Armor", "Hibernate", ],
            "Charge Mastery"    : [ "Static Discharge", "Electric Shackles", "Thunder Strike", "Surge of Power", "EM Pulse", ],
            "Heat Mastery"      : [ "Bonfire", "Fire Blast", "Fire Ball", "Char", "Rise of the Phoenix", ],
            "Field Mastery"     : [ "Invulnerability", "Power Blast", "Energy Torrent", "Explosive Blast", "Force of Nature", ],

            "Leviathan Mastery" : [ "School of Sharks", "Bile Spray", "Knockout Blow", "Shark Skin", "Spirit Shark Jaws", ],
            "Mace Mastery"      : [ "Web Envelope", "Scorpion Shield", "Mace Beam Volley", "Power Boost", "Web Cocoon", ],
            "Mu Mastery"        : [ "Static Discharge", "Charged Armor", "Electrifying Fences", "Thunder Strike", "Electric Shackles", ],
            "Soul Mastery"      : [ "Night Fall", "Dark Embrace", "Oppressive Gloom", "Soul Tentacles", "Soul Storm", ],
        },
        "Primary": {
            "Beast Mastery"   : [ "Call Swarm", "Summon Wolves", "Call Hawk", "Train Beasts", "Call Ravens", "Summon Lions", "Fortify Pack", "Summon Dire Wolf", "Tame Beasts", ],
            "Demon Summoning" : [ "Corruption", "Summon Demonlings", "Lash", "Enchant Demon", "Crack Whip", "Summon Demons", "Hell on Earth", "Summon Demon Prince", "Abyssal Empowerment", ],
            "Mercenaries"     : [ "Burst", "Soldiers", "Slug", "Equip Mercenary", "M30 Grenade", "Spec Ops", "Serum", "Commando", "Tactical Upgrade", ],
            "Necromancy"      : [ "Dark Blast", "Zombie Horde", "Gloom", "Enchant Undead", "Life Drain", "Grave Knight", "Soul Extraction", "Lich", "Dark Empowerment", ],
            "Ninjas"          : [ "Snap Shot", "Call Genin", "Aimed Shot", "Train Ninjas", "Fistful of Arrows", "Call Jounin", "Smoke Flash", "Oni", "Kuji In Zen", ],
            "Robotics"        : [ "Pulse Rifle Blast", "Battle Drones", "Pulse Rifle Burst", "Equip Robot", "Photon Grenade", "Protector Bots", "Repair", "Assault Bot", "Upgrade Robot", ],
            "Thugs"           : [ "Pistols", "Call Thugs", "Dual Wield", "Equip Thugs", "Empty Clips", "Call Enforcer", "Gang War", "Call Bruiser", "Upgrade Equipment", ],
        },
        "Secondary": {
            "Cold Domination"     : [ "Infrigidate", "Ice Shield", "Snow Storm", "Glacial Shield", "Frostwork", "Arctic Fog", "Benumb", "Sleet", "Heat Loss", ],
            "Dark Miasma"         : [ "Twilight Grasp", "Tar Patch", "Darkest Night", "Howling Twilight", "Shadow Fall", "Fearsome Stare", "Petrifying Gaze", "Black Hole", "Dark Servant", ],
            "Electrical Affinity" : [ "Shock", "Rejuvenating Circuit", "Discharge", "Energizing Circuit", "Faraday Cage", "Empowering Circuit", "Defibrillate", "Insulating Circuit", "Amp Up", ],
            "Empathy"             : [ "Healing Aura", "Heal Other", "Absorb Pain", "Resurrect", "Clear Mind", "Fortitude", "Recovery Aura", "Regeneration Aura", "Adrenalin Boost", ],
            "Force Field"         : [ "Force Bolt", "Deflection Shield", "Force Bolt", "Insulation Shield", "Detention Field", "Dispersion Bubble", "Repulsion Field", "Repulsion Bomb", "Force Bubble", ],
            "Kinetics"            : [ "Transfusion", "Siphon Power", "Repel", "Siphon Speed", "Increase Density", "Speed Boost", "Inertial Reduction", "Transference", "Fulcrum Shift", ],
            "Nature Affinity"     : [ "Corrosive Enzymes", "Regrowth", "Wild Growth", "Spore Cloud", "Lifegiving Spores", "Wild Bastion", "Rebirth", "Entangling Aura", "Overgrowth", ],
            "Pain Domination"     : [ "Nullify Pain", "Soothe", "Share Pain", "Conduit Of Pain", "Enforced Morale", "Suppress Pain", "World of Pain", "Anguishing Cry", "Painbringer", ],
            "Poison"              : [ "Alkaloid", "Envenom", "Weaken", "Neurotoxic Breath", "Elixir of Life", "Antidote", "Paralytic Poison", "Poison Trap", "Noxious Gas", ],
            "Radiation Emission"  : [ "Radiant Aura", "Radiation Infection", "Accelerate Metabolism", "Enervating Field", "Mutation", "Lingering Radiation", "Choking Cloud", "Fallout", "EM Pulse", ],
            "Sonic Resonance"     : [ "Sonic Siphon", "Sonic Barrier", "Sonic Haven", "Sonic Cage", "Disruption Field", "Sonic Dispersion", "Sonic Repulsion", "Clarity", "Liquefy", ],
            "Storm Summoning"     : [ "Gale", "O2 Boost", "Snow Storm", "Steamy Mist", "Freezing Rain", "Hurricane", "Thunder Clap", "Tornado", "Lightning Storm", ],
            "Thermal Radiation"   : [ "Warmth", "Fire Shield", "Cauterize", "Plasma Shield", "Power of the Phoenix", "Thaw", "Forge", "Heat Exhaustion", "Melt Armor", ],
            "Time Manipulation"   : [ "Time Crawl", "Temporal Mending", "Time's Juncture", "Temporal Selection", "Distortion Field", "Time Stop", "Farsight", "Slowed Response", "Chrono Shift", ],
            "Traps"               : [ "Web Grenade", "Caltrops", "Triage Beacon", "Acid Mortar", "Force Field Generator", "Poison Trap", "Seeker Drones", "Trip Mine", "Detonator", ],
            "Trick Arrow"         : [ "Entangling Arrow", "Flash Arrow", "Glue Arrow", "Ice Arrow", "Poison Gas Arrow", "Acid Arrow", "Disruption Arrow", "Oil Slick Arrow", "EMP Arrow", ],
        },
    },
    'Peacebringer': {
        'Faction': 'H',
        "Epic": {},
        "Dependent": {
            "Bright Nova": [ "Bright Nova Bolt", "Bright Nova Blast", "Bright Nova Scatter", "Bright Nova Detonation", ],
            "White Dwarf": [ "White Dwarf Strike", "White Dwarf Smite", "White Dwarf Flare", "White Dwarf Sublimation", "White Dwarf Antagonize", "White Dwarf Step", ],
        },
        "Inherent": {
            "Inherent": [ "Combat Flight", "Energy Flight", "Quantum Acceleration",],
        },
        "Primary": {
            "Luminous Blast": [ "Gleaming Bolt", "Glinting Eye", "Gleaming Blast", "Bright Nova", "Radiant Strike", "Proton Scatter", "Inner Light",
                                "Luminous Detonation", "Incandescent Strike", "Pulsar", "Glowing Touch", "Solar Flare", "Dawn Strike", "Photon Seekers",
                                "Bright Nova Bolt", "Bright Nova Blast", "Bright Nova Scatter", "Bright Nova Detonation", ],
        },
        "Secondary": {
            "Luminous Aura": [ "Incandescence", "Shining Shield", "Essence Boost", "Thermal Shield", "Quantum Shield", "Group Energy Flight", "White Dwarf",
                               "Reform Essence", "Conserve Energy", "Quantum Maneuvers", "Quantum Flight", "Restore Essence", "Light Form",
                               "White Dwarf Strike", "White Dwarf Smite", "White Dwarf Flare", "White Dwarf Sublimation", "White Dwarf Antagonize", "White Dwarf Step", ],
        },
    },
    'Scrapper': {
        'Faction': 'H',
        "Epic": {
            "Blaze Mastery"     : [ "Ring of Fire", "Char", "Fire Blast", "Melt Armor", "Fire Ball", ],
            "Body Mastery"      : [ "Conserve Power", "Focused Accuracy", "Laser Beam Eyes", "Physical Perfection", "Energy Torrent", ],
            "Darkness Mastery"  : [ "Torrent", "Petrifying Gaze", "Dark Blast", "Night Fall", "Tenebrous Tentacles", ],
            "Weapon Mastery"    : [ "Web Grenade", "Caltrops", "Shuriken", "Targeting Drone", "Exploding Shurken", ],

            "Leviathan Mastery" : [ "Spirit Shark", "Water Spout", "Hibernate", "Spirit Shark Jaws", "Summon Guardian", ],
            "Mace Mastery"      : [ "Mace Blast", "Mace Beam", "Disruptor Blast", "Web Cocoon", "Summon Spiderlings", ],
            "Mu Mastery"        : [ "Mu Bolts", "Zapp", "Ball Lightning", "Electric Shackles", "Summon Adept", ],
            "Soul Mastery"      : [ "Dark Blast", "Moonbeam", "Shadow Meld", "Soul Storm", "Summon Widow", ],
        },
        "Primary": {
            "Battle Axe"       : [ "Beheader", "Chop", "Gash", "Build Up", "Swoop", "Taunt", "Whirling Axe", "Cleave", "Pendulum", ],
            "Broad Sword"      : [ "Hack", "Slash", "Slice", "Build Up", "Parry", "Confront", "Whirling Sword", "Disembowel", "Head Splitter", ],
            "Claws"            : [ "Swipe", "Strike", "Slash", "Spin", "Confront", "Follow Up", "Focus", "Eviscerate", "Shockwave", ],
            "Dark Melee"       : [ "Shadow Punch", "Smite", "Shadow Maul", "Touch of Fear", "Siphon Life", "Confront", "Dark Consumption", "Soul Drain", "Midnight Grasp", ],
            "Dual Blades"      : [ "Nimble Slash", "Power Slice", "Ablating Strike", "Typhoon's Edge", "Blinding Feint", "Confront", "Vengeful Slice", "Sweeping Strike", "One Thousand Cuts", ],
            "Electrical Melee" : [ "Charged Brawl", "Havoc Punch", "Jacobs Ladder", "Build Up", "Thunder Strike", "Confront", "Chain Induction", "Lightning Clap", "Lightning Rod", ],
            "Energy Melee"     : [ "Barrage", "Energy Punch", "Bone Smasher", "Build Up", "Power Crash", "Confront", "Whirling Hands", "Total Focus", "Energy Transfer", ],
            "Fiery Melee"      : [ "Scorch", "Fire Sword", "Cremate", "Build Up", "Breath of Fire", "Confront", "Fire Sword Circle", "Incinerate", "Greater Fire Sword", ],
            "Ice Melee"        : [ "Frozen Fists", "Ice Sword", "Frost", "Build Up", "Ice Patch", "Confront", "Greater Ice Sword", "Freezing Touch", "Frozen Aura", ],
            "Katana"           : [ "Sting of the Wasp", "Gambler's Cut", "Flashing Steel", "Build Up", "Divine Avalanche", "Calling the Wolf", "The Lotus Drops", "Soaring Dragon", "Golden Dragonfly", ],
            "Kinetic Melee"    : [ "Quick Strike", "Body Blow", "Smashing Blow", "Power Siphon", "Repulsing Torrent", "Confront", "Burst", "Focused Burst", "Concentrated Strike", ],
            "Martial Arts"     : [ "Thunder Kick", "Storm Kick", "Cobra Strike", "Focus Chi", "Crane Kick", "Warrior's Challenge", "Crippling Axe Kick", "Dragon's Tail", "Eagle's Claw", ],
            "Psionic Melee"    : [ "Mental Strike", "Psi Blade", "Telekinetic Blow", "Concentration", "Psi Blade Sweep", "Confront", "Boggle", "Greater Psi Blade", "Mass Levitate", ],
            "Radiation Melee"  : [ "Contaminated Strike", "Radioactive Smash", "Proton Sweep", "Fusion", "Radiation Siphon", "Confront", "Irradiated Ground", "Devastating Blow", "Atom Smasher", ],
            "Savage Melee"     : [ "Maiming Slash", "Savage Strike", "Shred", "Blood Thirst", "Vicious Slash", "Confront", "Rending Flurry", "Hemorrhage", "Savage Leap", ],
            "Spines"           : [ "Barb Swipe", "Lunge", "Spine Burst", "Build Up", "Impale", "Confront", "Quills", "Ripper", "Throw Spines", ],
            "Staff Fighting"   : [ "Mercurial Blow", "Precise Strike", "Guarded Spin", "Eye of the Storm", "Staff Mastery", "Confront", "Serpent's Reach", "Innocuous Strikes", "Sky Splitter", 'Form of the Body', 'Form of the Mind', 'Form of the Soul',  ],
            "Stone Melee"      : [ "Stone Fist", "Stone Mallet", "Heavy Mallet", "Build Up", "Fault", "Confront", "Seismic Smash", "Hurl Boulder", "Tremor", ],
            "Street Justice"   : [ "Initial Strike", "Heavy Blow", "Sweeping Cross", "Combat Readiness", "Rib Cracker", "Confront", "Spinning Strike", "Shin Breaker", "Crushing Uppercut", ],
            "Titan Weapons"    : [ "Defensive Sweep", "Crushing Blow", "Titan Sweep", "Follow Through", "Build Momentum", "Confront", "Rend Armor", "Whirling Smash", "Arc of Destruction", ],
            "War Mace"         : [ "Bash", "Pulverize", "Jawbreaker", "Build Up", "Clobber", "Confront", "Whirling Mace", "Shatter", "Crowd Control", ],
        },
        "Secondary": {
            "Bio Armor"       : [ "Hardened Carapace", "Inexhaustible", "Environmental Modification", "Adaptation", "Ablative Carapace", "Evolving Armor", "DNA Siphon", "Genetic Contamination", "Parasitic Aura", "Efficient Adaptation", "Defensive Adaptation", "Offensive Adaptation", ],
            "Dark Armor"      : [ "Dark Embrace", "Death Shroud", "Murky Cloud", "Obsidian Shield", "Dark Regeneration", "Cloak of Darkness", "Cloak of Fear", "Oppressive Gloom", "Soul Transfer", ],
            "Electric Armor"  : [ "Charged Armor", "Lightning Field", "Conductive Shield", "Static Shield", "Grounded", "Energize", "Lightning Reflexes", "Power Sink", "Power Surge", ],
            "Energy Aura"     : [ "Kinetic Shield", "Dampening Field", "Power Shield", "Entropic Aura", "Energy Protection", "Energy Cloak", "Energize", "Energy Drain", "Overload", ],
            "Fiery Aura"      : [ "Fire Shield", "Blazing Aura", "Healing Flames", "Temperature Protection", "Plasma Shield", "Consume", "Burn", "Fiery Embrace", "Rise of the Phoenix", ],
            "Ice Armor"       : [ "Frozen Armor", "Hoarfrost", "Chilling Embrace", "Wet Ice", "Glacial Armor", "Energy Absorption", "Permafrost", "Icicles", "Icy Bastion", ],
            "Invulnerability" : [ "Resist Physical Damage", "Temp Invulnerability", "Dull Pain", "Resist Elements", "Unyielding", "Resist Energies", "Invincibility", "Tough Hide", "Unstoppable", ],
            "Ninjitsu"        : [ "Hide", "Ninja Reflexes", "Danger Sense", "Caltrops", "Kuji-In Rin", "Kuji-In Sha", "Smoke Flash", "Blinding Powder", "Kuji-In Retsu", ],
            "Radiation Armor" : [ "Alpha Barrier", "Gamma Boost", "Proton Armor", "Fallout Shelter", "Radiation Therapy", "Beta Decay", "Particle Shielding", "Ground Zero", "Meltdown", ],
            "Regeneration"    : [ "Fast Healing", "Reconstruction", "Quick Recovery", "Dull Pain", "Integration", "Resilience", "Instant Healing", "Revive", "Moment of Glory", ],
            "Shield Defense"  : [ "Deflection", "Battle Agility", "True Grit", "Active Defense", "Against All Odds", "Phalanx Fighting", "Grant Cover", "Shield Charge", "One with the Shield", ],
            "Stone Armor"     : [ "Rock Armor", "Stone Skin", "Earth's Embrace", "Mud Pots", "Rooted", "Crystal Armor", "Minerals", "Brimstone Armor", "Geode", ],
            "Super Reflexes"  : [ "Focused Fighting", "Focused Senses", "Agile", "Practiced Brawler", "Dodge", "Quickenss", "Lucky", "Evasion", "Elude", ],
            "Willpower"       : [ "High Pain Tolerance", "Mind Over Body", "Fast Healing", "Indomitable Will", "Rise to the Challenge", "Quick Recovery", "Heightened Senses", "Resurgence", "Strength of Will", ],
        },
    },
    'Sentinel': {
        'Primary': {
            'Archery'          : ['Snap Shot', 'Aimed Shot', 'Fistful of Arrows', 'Stunning Shot', 'Aim', 'Explosive Arrow', 'Blazing Arrow', 'Perfect Shot', 'Rain of Arrows'],
            'Assault Rifle'    : ['Burst', 'Disorienting Shot', 'Buckshot', 'Slug', 'Aim', 'M30 Grenade', 'Flamethrower', 'Incinerator', 'Full Auto'],
            'Beam Rifle'       : ['Single Shot', 'Charged Shot', 'Cutting Beam', 'Disintegrate', 'Aim', 'Lancer Shot', 'Refractor Beam', 'Piercing Beam', 'Overcharge'],
            'Dark Blast'       : ['Dark Blast', 'Gloom', 'Umbral Torrent', 'Abyssal Gaze', 'Aim', 'Dark Obliteration', 'Antumbral Beam', 'Life Drain', 'Blackstar'],
            'Dual Pistols'     : [ 'Pistols', 'Dual Wield', 'Empty Clips', 'Suppressive Fire', 'Swap Ammo', 'Bullet Rain', "Executioner's Shot", 'Piercing Rounds', 'Hail of Bullets',
                                  "Cryo Ammunition", "Incendiary Ammunition", "Chemical Ammunition"],
            'Electrical Blast' : ['Charged Bolts', 'Lightning Bolt', 'Ball Lightning', 'Zapping Bolt', 'Charge Up', 'Tesla Cage', 'Voltaic Sentinel', 'Short Circuit', 'Thunderous Blast'],
            'Energy Blast'     : ['Power Bolt', 'Power Blast', 'Energy Torrent', 'Power Burst', 'Aim', 'Power Push', 'Explosive Blast', 'Focused Power Bolt', 'Nova'],
            'Fire Blast'       : ['Flares', 'Fire Blast', 'Fire Ball', 'Blaze', 'Aim', 'Fire Breath', 'Blazing Blast', 'Rain of Fire', 'Inferno'],
            'Ice Blast'        : ['Ice Bolt', 'Ice Blast', 'Frost Breath', 'Chilling Ray', 'Aim', 'Ice Storm', 'Bitter Ice Blast', 'Bitter Freeze Ray', 'Blizzard'],
            'Psychic Blast'    : ['Mental Blast', 'Telekinetic Blast', 'Psychic Scream', 'Will Domination', 'Psychic Focus', 'Psionic Strike', 'Psionic Tornado', 'Scramble Thoughts', 'Psychic Wail'],
            'Radiation Blast'  : ['Neutrino Bolt', 'X-Ray Beam', 'Irradiate', 'Cosmic Burst', 'Aim', 'Electron Haze', 'Proton Stream', 'Neutron Bomb', 'Atomic Blast'],
            'Sonic Attack'     : ['Shriek', 'Scream', 'Howl', 'Shout', 'Amplify', 'Shockwave', 'Sirens Song', 'Screech', 'Dreadful Wail'],
            'Water Blast'      : ['Aqua Bolt', 'Hydro Blast', 'Water Burst', 'Dehydrate', 'Tidal Forces', 'Whirlpool', 'Water Jet', 'Steam Spray', 'Geyser']
        },
        'Secondary': {
             'Bio Armor'       : [ 'Hardened Carapace', 'Inexhaustible', 'Environmental Adaptation', 'Adaptation', 'Ablative Carapace', 'Rebuild DNA', 'Athletic Regulation', 'Genomic Evolution', 'Parasitic Leech', "Efficient Adaptation", "Defensive Adaptation", "Offensive Adaptation", ],
             'Dark Armor'      : ['Dark Embrace', 'Tenebrous Regeneration', 'Murky Cloud', 'Obsidian Shield', 'Obscure Sustenance', 'Cloak of Darkness', 'Cloak of Fear', 'Oppressive Gloom', 'Soul Transfer'],
             'Electric Armor'  : ['Charged Armor', 'Charged Shield', 'Conductive Shield', 'Energize', 'Static Shield', 'Grounded', 'Lightning Reflexes', 'Power Sink', 'Power Surge'],
             'Energy Aura'     : ['Kinetic Shield', 'Kinetic Dampening', 'Power Shield', 'Energize', 'Entropy Shield', 'Power Armor', 'Repelling Force', 'Power Drain', 'Overload'],
             'Fiery Aura'      : ['Fire Shield', 'Molten Embrace', 'Healing Flames', 'Temperature Protection', 'Plasma Shield', 'Consume', 'Burn', 'Cauterizing Blaze', 'Rise of the Phoenix'],
             'Ice Armor'       : ['Frozen Armor', 'Hoarfrost', 'Wet Ice', 'Frigid Shield', 'Moisture Absorption', 'Glacial Armor', 'Permafrost', 'Frost Protection', 'Icy Bastion'],
             'Invulnerability' : ['Temp Invulnerability', 'Resist Physical Damage', 'Durability', 'Dull Pain', 'Unyielding', 'Environmental Resistance', 'Invincible', 'Tough Hide', 'Unstoppable'],
             'Ninjitsu'        : ['Ninja Reflexes', 'Danger Sense', 'Shinobi-Iri', 'Kuji-In Rin', 'Seishinteki Kyoyo', 'Kuji-In Sha', 'Bo Ryaku', 'Blinding Powder', 'Kuji-In Retsu'],
             'Radiation Armor' : ['Alpha Barrier', 'Gamma Boost', 'Proton Armor', 'Fallout Shelter', 'Proton Therapy', 'Particle Acceleration', 'Particle Shielding', 'Ground Zero', 'Meltdown'],
             'Regeneration'    : ['Fast Healing', 'Reconstruction', 'Quick Recovery', 'Instant Regeneration', 'Dismiss Pain', 'Integration', 'Resilience', 'Second Wind', 'Moment of Glory'],
             'Super Reflexes'  : ['Focused Fighting', 'Focused Senses', 'Agile', 'Master Brawler', 'Practiced Brawler', 'Enduring', 'Dodge', 'Quickness', 'Evasion', 'Elude'],
             'Willpower'       : ['High Pain Tolerance', 'Mind Over Body', 'Fast Healing', 'Indomitable Will', 'Up to the Challenge', 'Quick Recovery', 'Heightened Senses', 'Resurgence', 'Strength of Will']
         },
        'Epic': {
            "Dark Mastery"        : [ "Netherworld Tentacles", "Smite", "Netherworld Grasp", "Engulfing Darkness", "Darkest Night", ],
            "Fire Mastery"        : [ "Fire Cages", "Cremate", "Char", "Fire Sword Circle", "Warmth", ],
            "Electricity Mastery" : [ "Chain Fences", "Havoc Punch", "Paralyzing Jolt", "Lightning Field", "Rehabilitating Circuit", ],
            "Ice Mastery"         : [ "Frostbite", "Ice Sword", "Block of Ice", "Frozen Aura", "Snow Storm", ],
            "Ninja Tool Mastery"  : [ "Tashibishi", "Sting of the Wasp", "Paralyzing Dart", "The Lotus Drops", "Kemuridama", ],
            "Psionic Mastery"     : [ "Mass Hypnosis", "Mind Probe", "Dominate", "Psychic Shockwave", "Link Minds", ],

            "Leviathan Mastery"   : [ "School of Sharks", "Knockout Blow", "Arctic Breath", "Spirit Shark Jaws", "Summon Coralax", ],
            "Mace Mastery"        : [ "Web Envelope", "Pulverize", "Coordinated Targeting", "Web Cocoon", "Summon Tarantula", ],
            "Mu Mastery"          : [ "Electrifying Fences", "Thunder Strike", "Electric Shackles", "Static Discharge", "Summon Adept", ],
            "Soul Mastery"        : [ "Midnight Grasp", "Soul Tentacles", "Darkest Night", "Soul Storm", "Summon Mistress", ],
        },
    },
    'Stalker': {
        'Faction': 'V',
        "Epic": {
            "Blaze Mastery"     : [ "Ring of Fire", "Char", "Fire Blast", "Melt Armor", "Fire Ball", ],
            "Body Mastery"      : [ "Superior Conditioning", "Focused Accuracy", "Laser Beam Eyes", "Physical Perfection", "Energy Torrent", ],
            "Darkness Mastery"  : [ "Torrent", "Petrifying Gaze", "Dark Blast", "Night Fall", "Tenebrous Tentacles", ],
            "Weapon Mastery"    : [ "Web Grenade", "Physical Perfection", "Shuriken", "Targeting Drone", "Exploding Shurken", ],

            "Leviathan Mastery" : [ "Spirit Shark", "Water Spout", "Hibernate", "Spirit Shark Jaws", "Summon Guardian", ],
            "Mace Mastery"      : [ "Mace Blast", "Mace Beam", "Disruptor Blast", "Web Cocoon", "Summon Spiderlings", ],
            "Mu Mastery"        : [ "Mu Bolts", "Zapp", "Ball Lightning", "Electric Shackles", "Summon Adept", ],
            "Soul Mastery"      : [ "Dark Blast", "Moonbeam", "Shadow Meld", "Soul Storm", "Summon Widow", ],
        },
        "Primary": {
            "Broad Sword"     : [ "Hack", "Slash", "Slice", "Assassin's Slash", "Build Up", "Placate", "Parry", "Disembowel", "Head Splitter", ],
            "Claws"           : [ "Swipe", "Strike", "Slash", "Assassin's Claw", "Build Up", "Placate", "Focus", "Eviscerate", "Shockwave", ],
            "Dark Melee"      : [ "Shadow Punch", "Smite", "Shadow Maul", "Assassin's Eclipse", "Build Up", "Placate", "Siphon Life", "Touch of Fear", "Midnight Grasp", ],
            "Dual Blades"     : [ "Nimble Slash", "Power Slice", "Ablating Strike", "Assassin's Blades", "Build Up", "Placate", "Vengeful Slice", "Sweeping Strike", "One Thousand Cuts", ],
            "Electric Melee"  : [ "Charged Brawl", "Havoc Punch", "Jacobs Ladder", "Assassin's Shock", "Build Up", "Placate", "Chain Induction", "Lightning Clap", "Lightning Rod", ],
            "Energy Melee"    : [ "Barrage", "Energy Punch", "Bone Smasher", "Assassin's Strike", "Build Up", "Placate", "Power Crash", "Total Focus", "Energy Transfer", ],
            "Fiery Melee"     : [ "Scorch", "Fire Sword", "Cremate", "Assassin's Blaze", "Build Up", "Placate", "Breath of Fire", "Fire Sword Circle", "Greater Fire Sword", ],
            "Ice Melee"       : [ "Frozen Fists", "Ice Sword", "Frost", "Assassin's Ice Sword", "Placate", "Build Up", "Ice Patch", "Freezing Touch", "Frozen Aura", ],
            "Kinetic Melee"   : [ "Quick Strike", "Body Blow", "Smashing Blow", "Assassin's Strike", "Build Up", "Placate", "Burst", "Focused Burst", "Concentrated Strike", ],
            "Martial Arts"    : [ "Thunder Kick", "Storm Kick", "Crippling Axe Kick", "Assassin's Blow", "Focus Chi", "Placate", "Cobra Strike", "Crane Kick", "Eagle's Claw", ],
            "Ninja Blade"     : [ "Sting of the Wasp", "Gambler's Cut", "Flashing Steel", "Assassin's Blade", "Build Up", "Placate", "Divine Avalanche", "Soaring Dragon", "Golden Dragonfly", ],
            "Psionic Melee"   : [ "Mental Strike", "Psi Blade", "Telekinetic Blow", "Assassin's Psi Blade", "Concentration", "Placate", "Boggle", "Greater Psi Blade", "Mass Levitate", ],
            "Radiation Melee" : [ "Contamination Strike", "Radioactive Smash", "Proton Sweep", "Assassin's Corruption", "Build Up", "Placate", "Radiation Siphon", "Devastating Blow", "Atom Smasher", ],
            "Savage Melee"    : [ "Savage Strike", "Maiming Slash", "Shred", "Assassin's Frenzy", "Build Up", "Placate", "Rending Flurry", "Hemorrhage", "Savage Leap", ],
            "Spines"          : [ "Barb Swipe", "Lunge", "Spine Burst", "Assassin's Impaler", "Build Up", "Placate", "Impale", "Ripper", "Throw Spines", ],
            "Staff Fighting"  : [ "Mercurial Blow", "Precise Strike", "Guarded Spin", "Assassin's Staff", "Build Up", "Placate", "Eye of the Storm", "Serpent's Reach", "Sky Splitter", ],
            "Stone Melee"     : [ "Stone Fist", "Stone Mallet", "Fault", "Assassin's Smash", "Build Up", "Placate", "Seismic Mallet", "Hurl Boulder", "Tremor", ],
            "Street Justice"  : [ "Initial Strike", "Heavy Blow", "Sweeping Cross", "Assassin's Strike", "Build Up", "Placate", "Spinning Strike", "Shin Breaker", "Crushing Uppercut", ],
        },
        "Secondary": {
            "Bio Armor"       : [ "Hide", "Hardened Carapace", "Boundless Energy", "Environmental Modification", "Adaptation", "Ablative Carapace", "DNA Siphon", "Genetic Corruption", "Parasitic Aura",  "Parasitic Aura", "Efficient Adaptation", "Defensive Adaptation", "Offensive Adaptation", ],
            "Dark Armor"      : [ "Hide", "Dark Embrace", "Murky Cloud", "Shadow Dweller", "Obsidian Shield", "Dark Regeneration", "Cloak of Fear", "Oppressive Gloom", "Soul Transfer", ],
            "Electric Armor"  : [ "Hide", "Charged Armor", "Conductive Shield", "Static Shield", "Grounded", "Lightning Reflexes", "Energize", "Power Sink", "Power Surge ", ],
            "Energy Aura"     : [ "Hide", "Kinetic Shield", "Power Shield", "Entropy Shield", "Kinetic Dampening", "Disrupt", "Energy Drain", "Energize", "Overload", ],
            "Fiery Aura"      : [ "Hide", "Fire Shield", "Healing Flames", "Temperature Protection", "Plasma Shield", "Consume", "Burn", "Cauterizing Blaze", "Rise of the Phoenix", ],
            "Ice Armor"       : [ "Hide", "Frozen Armor", "Hoarfrost", "Wet Ice", "Chilling Embrace", "Permafrost", "Glacial Armor", "Energy Absorption", "Icy Bastion", ],
            "Invulnerability" : [ "Hide", "Resist Physical Damage", "Temp Invulnerability", "Dull Pain", "Unyielding", "Environmental Resistance", "Invincible", "Tough Hide", "Unstoppable", ],
            "Ninjitsu"        : [ "Hide", "Ninja Reflexes", "Danger Sense", "Caltrops", "Kuji-In Rin", "Kuji-In Sha", "Smoke Flash", "Blinding Powder", "Kuji-In Retsu", ],
            "Radiation Armor" : [ "Hide", "Alpha Barrier", "Gamma Boost", "Proton Armor", "Fallout Shelter", "Radiation Therapy", "Particle Shielding", "Ground Zero", "Meltdown", ],
            "Regeneration"    : [ "Hide", "Fast Healing", "Reconstruction", "Dull Pain", "Integration", "Resilience", "Instant Healing", "Revive", "Moment Of Glory", ],
            "Shield Defense"  : [ "Hide", "Deflection", "Battle Agility", "True Grit", "Active Defense", "Against All Odds", "Grant Cover", "Shield Charge", "One with the Shield", ],
            "Stone Armor"     : [ "Hide", "Rock Armor", "Stone Skin", "Earth's Embrace", "Rooted", "Crystal Armor", "Brimstone Armor", "Minerals", "Geode", ],
            "Super Reflexes"  : [ "Hide", "Focused Fighting", "Focused Senses", "Agile", "Practiced Brawler", "Dodge", "Quickness", "Evasion", "Elude", ],
            "Willpower"       : [ "Hide", "High Pain Tolerance", "Reconstruction", "Mind Over Body", "Indomitable Will", "Heightened Senses", "Fast Healing", "Resurgence", "Strength of Will", ],
        },
    },
    'Tanker': {
        'Faction': 'H',
        "Epic": {
            "Arctic Mastery"    : [ "Chilblain", "Block of Ice", "Ice Blast", "Shiver", "Ice Storm", ],
            "Earth Mastery"     : [ "Stone Prison", "Salt Crystals", "Fossilize", "Quicksand", "Stalagmites", ],
            "Energy Mastery"    : [ "Conserve Power", "Focused Accuracy", "Laser Beam Eyes", "Physical Perfection", "Energy Torrent", ],
            "Pyre Mastery"      : [ "Ring of Fire", "Char", "Fire Blast", "Melt Armor", "Fire Ball", ],

            "Leviathan Mastery" : [ "Spirit Shark", "School of Sharks", "Arctic Breath", "Bile Spray", "Summon Guardian", ],
            "Mace Mastery"      : [ "Mace Blast", "Web Envelope", "Disruptor Blast", "Focused Accuracy", "Summon Blaster", ],
            "Mu Mastery"        : [ "Mu Lightning", "Electrifying Fences", "Ball Lightning", "Static Discharge", "Summon Striker", ],
            "Soul Mastery"      : [ "Gloom", "Soul Tentacles", "Darkest Night", "Dark Obliteration", "Summon Widow", ],
        },
        "Primary": {
            "Bio Armor"       : [ "Hardened Carapace", "Inexhaustible", "Environmental Modification", "Adaptation", "Ablative Carapace", "Evolving Armor", "DNA Siphon", "Genetic Contamination", "Parasitic Aura",  "Parasitic Aura", "Efficient Adaptation", "Defensive Adaptation", "Offensive Adaptation", ],
            "Dark Armor"      : [ "Death Shroud", "Dark Embrace", "Murky Cloud", "Obsidian Shield", "Dark Regeneration", "Cloak of Darkness", "Cloak of Fear", "Oppressive Gloom", "Soul Transfer", ],
            "Electric Armor"  : [ "Charged Armor", "Lightning Field", "Conductive Shield", "Static Shield", "Grounded", "Energize", "Lightning Reflexes", "Power Sink", "Power Surge", ],
            "Fiery Aura"      : [ "Blazing Aura", "Fire Shield", "Healing Flames", "Temperature Protection", "Consume", "Plasma Shield", "Burn", "Fiery Embrace", "Rise of the Phoenix", ],
            "Ice Armor"       : [ "Frozen Armor", "Hoarfrost", "Chilling Embrace", "Wet Ice", "Permafrost", "Icicles", "Glacial Armor", "Energy Absorption", "Hibernate", ],
            "Invulnerability" : [ "Resist Physical Damage", "Temp Invulnerability", "Dull Pain", "Resist Elements", "Unyielding", "Resist Energies", "Invincibility", "Tough Hide", "Unstoppable", ],
            "Radiation Armor" : [ "Alpha Barrier", "Gamma Boost", "Proton Armor", "Fallout Shelter", "Radiation Therapy", "Beta Decay", "Particle Shielding", "Ground Zero", "Meltdown", ],
            "Shield Defense"  : [ "Deflection", "Battle Agility", "True Grit", "Active Defense", "Against All Odds", "Phalanx Fighting", "Grant Cover", "Shield Charge", "One with the Shield", ],
            "Stone Armor"     : [ "Rock Armor", "Stone Skin", "Earth's Embrace", "Mud Pots", "Rooted", "Crystal Armor", "Minerals", "Brimstone Armor", "Granite Armor", ],
            "Super Reflexes"  : [ "Focused Fighting", "Focused Senses", "Agile", "Practiced Brawler", "Dodge", "Evasion", "Lucky", "Quickness", "Elude", ],
            "Willpower"       : [ "High Pain Tolerance", "Mind Over Body", "Fast Healing", "Indomitable Will", "Rise to the Challenge", "Quick Recovery", "Heightened Senses", "Resurgence", "Strength of Will", ],
        },
        "Secondary": {
            "Battle Axe"       : [ "Beheader", "Chop", "Gash", "Taunt", "Build Up", "Whirling Axe", "Swoop", "Cleave", "Pendulum", ],
            "Broad Sword"      : [ "Hack", "Slash", "Slice", "Taunt", "Parry", "Build Up", "Whirling Sword", "Disembowel", "Head Splitter", ],
            "Claws"            : [ "Swipe", "Strike", "Slash", "Taunt", "Spin", "Follow Up", "Focus", "Eviscerate", "Shockwave", ],
            "Dark Melee"       : [ "Shadow Punch", "Smite", "Shadow Maul", "Taunt", "Siphon Life", "Touch of Fear", "Soul Drain", "Dark Consumption", "Midnight Grasp", ],
            "Dual Blades"      : [ "Nimble Slash", "Power Slice", "Ablating Strike", "Taunt", "Typhoon's Edge", "Blinding Feint", "Vengeful Slice", "Sweeping Strike", "One Thousand Cuts", ],
            "Electrical Melee" : [ "Charged Brawl", "Havoc Punch", "Jacobs Ladder", "Taunt", "Thunder Strike", "Build Up", "Chain Induction", "Lightning Clap", "Lightning Rod", ],
            "Energy Melee"     : [ "Barrage", "Energy Punch", "Bone Smasher", "Taunt", "Whirling Hands", "Total Focus", "Build Up", "Power Crash", "Energy Transfer", ],
            "Fiery Melee"      : [ "Scorch", "Fire Sword", "Combustion", "Taunt", "Breath of Fire", "Build Up", "Fire Sword Circle", "Incinerate", "Greater Fire Sword", ],
            "Ice Melee"        : [ "Frozen Fists", "Ice Sword", "Frost", "Taunt", "Build Up", "Ice Patch", "Freezing Touch", "Greater Ice Sword", "Frozen Aura", ],
            "Katana"           : [ "Sting of the Wasp", "Gambler's Cut", "Flashing Steel", "Dragon's Roar", "Divine Avalanche", "Build Up", "The Lotus Drops", "Soaring Dragon", "Golden Dragonfly", ],
            "Kinetic Melee"    : [ "Quick Strike", "Body Blow", "Smashing Blow", "Taunt", "Repulsing Torrent", "Power Siphon", "Burst", "Focused Burst", "Concentrated Strike", ],
            "Martial Arts"     : [ "Thunder Kick", "Storm Kick", "Cobra Strike", "Warrior's Provocation", "Crane Kick", "Dragon's Tail", "Focus Chi", "Crippling Axe Kick", "Eagle's Claw", ],
            "Psionic Melee"    : [ "Mental Strike", "Psi Blade", "Telekinetic Blow", "Taunt", "Psi Blade Sweep", "Concentration", "Boggle", "Greater Psi Blade", "Mass Levitate", ],
            "Radiation Melee"  : [ "Contaminated Strike", "Radioactive Smash", "Proton Sweep", "Taunt", "Radiation Siphon", "Fusion", "Irradiated Ground", "Devastating Blow", "Atom Smasher", ],
            "Savage Melee"     : [ "Savage Strike", "Maiming Slash", "Shred", "Taunt", "Vicious Slash", "Blood Thirst", "Rending Flurry", "Hemorrhage", "Savage Leap", ],
            "Spines"           : [ "Barb Swipe", "Lunge", "Spine Burst", "Taunt", "Ripper", "Build Up", "Impale", "Quills", "Throw Spines", ],
            "Staff Fighting"   : [ "Mercurial Blow", "Precise Strike", "Guarded Spin", "Taunt", "Eye of the Storm", "Staff Mastery", "Serpent's Reach", "Innocuous Strikes", "Sky Splitter",  'Form of the Body', 'Form of the Mind', 'Form of the Soul', ],
            "Stone Melee"      : [ "Stone Fist", "Stone Mallet", "Heavy Mallet", "Taunt", "Build Up", "Fault", "Tremor", "Hurl Boulder", "Seismic Smash", ],
            "Street Justice"   : [ "Initial Strike", "Heavy Blow", "Sweeping Cross", "Taunt", "Combat Readiness", "Rib Cracker", "Spinning Strike", "Shin Breaker", "Crushing Uppercut", ],
            "Super Strength"   : [ "Jab", "Punch", "Haymaker", "Taunt", "Hand Clap", "Knockout Blow", "Rage", "Hurl", "Foot Stomp", ],
            "Titan Weapons"    : [ "Defensive Sweep", "Crushing Blow", "Titan Sweep", "Taunt", "Follow Through", "Build Momentum", "Rend Armor", "Whirling Smash", "Arc of Destruction", ],
            "War Mace"         : [ "Bash", "Pulverize", "Jawbreaker", "Taunt", "Build Up", "Whirling Mace", "Clobber", "Shatter", "Crowd Control", ],
        },
    },
    'Warshade': {
        'Faction': 'H',
        "Epic": {},
        "Dependent": {
            "Black Dwarf": [ "Black Dwarf Strike", "Black Dwarf Smite", "Black Dwarf Mire", "Black Dwarf Drain", "Black Dwarf Step", "Black Dwarf Antagonize", ],
            "Dark Nova": [ "Dark Nova Blast", "Dark Nova Bolt", "Dark Nova Detonation", "Dark Nova Emmanation", ],
        },
        "Inherent": {
            "Inherent": [ "Shadow Recall", "Shadow Step", ],
        },
        "Primary": {
            "Umbral Blast": [ "Shadow Bolt", "Ebon Eye", "Gravimetric Snare", "Dark Nova", "Shadow Blast", "Sunless Mire","Dark Detonation",
                              "Gravity Well", "Essence Drain", "Gravitic Emanation", "Unchain Essence", "Dark Extraction", "Quasar",
                              "Dark Nova Blast", "Dark Nova Bolt", "Dark Nova Detonation", "Dark Nova Emanation", ],
        },
        "Secondary": {
            "Umbral Aura": [ "Absorption", "Gravity Shield", "Orbiting Death", "Penumbral Shield", "Shadow Cloak", "Twilight Shield",
                             "Black Dwarf", "Stygian Circle", "Nebulous Form", "Inky Aspect", "Stygian Return", "Eclipse",
                             "Black Dwarf Strike", "Black Dwarf Smite", "Black Dwarf Mire", "Black Dwarf Drain", "Black Dwarf Step", "Black Dwarf Antagonize", ],
        },
    },
};

MiscPowers = {
    "Badge": {
        "Accolade": [
            "Eye of the Magus",
            "Crey CBX-9 Pistol",
            "Demonic Aura",
            "Elusive Mind",
            "Force of Nature",
            "Geas of the Kind Ones",
            "Portable Workbench",
            "Stolen Immobilizer Ray",
            "Megalomaniac",
            "Vanguard Medal",
        ],
    },
    "General": {
        "Inherent": [
            "Brawl",
            "Rest",
            "Sprint",
            "Walk",
            "Prestige Power Slide",
        ],
        "P2W": [
            "Prestige Power Rush",
            "Prestige Power Dash",
            "Prestige Power Surge ",
            "Prestige Power Quick",
            "Shadowy Presence",
            "Jump Pack",
            "Pocket D VIP Pass",
            "Mission Transporter",
            "Athletic Run",
            "Beast Run",
            "Inner Inspiration",
            "Mystic Fortune",
            "Ninja Run",
            "Secondary Mutation",
            "Self Destruction",
            "Steam Jump",
            "Apprentice Charm",
            "Mutagen",
            "Taser Dart",
            "Throwing Knives",
            "Tranq Dart",
        ],
    },
    "Pool": {
        "Concealment"   : [ "Stealth", "Grant Invisibility", "Infiltration", "Misdirection", "Phase Shift", ],
        "Fighting"      : [ "Boxing", "Kick", "Tough", "Weave", "Cross Punch", ],
        "Flight"        : [ "Hover", "Air Superiority", "Fly", "Group Fly", "Evasive Maneuvers", "Afterburner" ],
        "Leadership"    : [ "Maneuvers", "Assault", "Tactics", "Vengeance", "Victory Rush", ],
        "Leaping"       : [ "Jump Kick", "Super Jump", "Combat Jumping", "Acrobatics", "Spring Attack", "Double Jump", ],
        "Medicine"      : [ "Aid Other", "Injection", "Aid Self", "Field Medic", "Resuscitate", ],
        "Presence"      : [ "Pacify", "Provoke", "Intimidate", "Invoke Panic", "Unrelenting", ],
        "Speed"         : [ "Flurry", "Hasten", "Super Speed", "Burnout", "Whirlwind", "Speed Phase", ],
        "Teleportation" : [ "Teleport Target", "Teleport", "Combat Teleport", "Fold Space", "Team Teleport", ],
    },
    "Incarnate": {
        'Alpha': {
            'Types': [ 'Agility', 'Cardiac', 'Intuition', 'Musculature', 'Nerve' ,'Resilient', 'Spiritual', 'Vigor' ],
            'Powers': [ 'Boost', 'Core Boost', 'Radial Boost', 'Total Core Revamp', 'Partial Core Revamp',
                       'Partial Radial Revamp', 'Total Radial Revamp', 'Core Paragon', 'Radial Paragon', ],
        },
        'Judgement': {
            'Types': [ 'Cryonic', 'Ion', 'Mighty', 'Pyronic', 'Void', 'Vorpal', ],
            'Powers': [ 'Judgement', 'Core Judgement', 'Radial Judgement', 'Total Core Judgement', 'Partial Core Judgement',
                       'Partial Radial Judgement', 'Total Radial Judgement', 'Core Final Judgement', 'Radial Final Judgement' ],
        },
        'Interface': {
            'Types': [ 'Cognitive', 'Degenerative', 'Diamagnetic', 'Gravitic', 'Paralytic', 'Preemptive', 'Reactive', 'Spectral', ],
            'Powers': [ 'Interface', 'Core Interface', 'Radial Interface', 'Total Core Conversion', 'Partial Core Conversion',
                       'Partial Radial Conversion', 'Total Radial Conversion', 'Core Flawless Interface', 'Radial Flawless Interface', ],
        },
        'Lore': {
            'Types': [ 'Arachnos', 'Banished Pantheon', 'Carnival of Shadows', 'Cimerorans', 'Clockwork', 'Demons', 'IDF',
                      'Knives of Vengeance', 'Longbow', 'Nemesis', 'Phantom', 'Polar Lights', 'Rikti', 'Robotic Drones',
                      'Rularuu', 'Seers', 'Storm Elementals', 'Talons of Vengeance', 'Tsoo', 'Vanguard', 'Warworks', ],
            'Powers': [ 'Ally', 'Core Ally', 'Radial Ally', 'Total Core Improved Ally', 'Partial Core Improved Ally',
                       'Partial Radial Improved Ally', 'Total Radial Improved Ally', 'Core Superior Ally', 'Radial Superior Ally', ],
        },
        'Destiny': {
            'Types': [ 'Ageless', 'Barrier', 'Clarion', 'Incandescence', 'Rebirth', ],
            'Powers': [ 'Invocation', 'Core Invocation', 'Radial Invocation', 'Total Core Invocation', 'Partial Core Invocation',
                       'Partial Radial Invocation', 'Total Radial Invocation', 'Core Epiphany', 'Radial Epiphany', ],
        },
        'Hybrid': {
            'Types': [ 'Assault', 'Control', 'Melee', 'Support', ],
            'Powers': [ 'Genome', 'Core Genome', 'Radial Genome', 'Total Core Graft', 'Partial Core Graft',
                       'Partial Radial Graft', 'Total Radial Graft', 'Core Embodiment', 'Radial Embodiment', ],
        },
    }
}

SprintPowers = [
    "Sprint",
    "Prestige Power Slide",
    "Prestige Power Dash",
    "Prestige Power Quick",
    "Prestige Power Rush",
    "Prestige Power Slide",
]

Inspirations = {
    'Accuracy'     : {
        'color': wx.YELLOW,
        'tiers': ['Insight'        , 'Keen Insight'         , 'Uncanny Insight'] ,
    },
    'Health'       : {
        'color': wx.GREEN,
        'tiers': ['Respite'        , 'Dramatic Improvement' , 'Resurgance']      ,
    },
    'Damage'       : {
        'color': wx.RED,
        'tiers': ['Enrage'         , 'Focused Rage'         , 'Righteous Rage']  ,
    },
    'Endurance'    : {
        'color': wx.BLUE,
        'tiers': ['Catch a Breath' , 'Take a Breather'      , 'Second Wind']     ,
    },
    'Defense'      : {
        'color': (128, 0, 153),  # purple
        'tiers': ['Luck'           , 'Good Luck'            , 'Phenomenal Luck'] ,
    },
    'ResistDamage' : {
        'color': (230, 80, 0),   # orange
        'tiers': ['Sturdy'         , 'Rugged'               , 'Robust']          ,
    },
    'BreakFree'    : {
        'color': (110, 76, 200), # light purple
        'tiers': ['Break Free'     , 'Emerge'               , 'Escape']          ,
    },
    'Resurrection' : {
        'color': (50, 180, 160), # cyan
        'tiers': ['Awaken'         , 'Bounce Back'          , 'Restoration']     ,
    },
}

Emotes = {
        'emotes': [
            { 'Converse' : [
                { 'Greetings' : [
                    'Hi%emwave$$local Hi!',
                    'Hello <$target>%em wave$$local Hello, $target',
                    'Introduce <self>%em wave$$local Pleased to meet you! I am $name, a level $level $origin $archetype.',
                    'Looking for Team%local level $level $archetype$$local Looking for team.',
                    'Welcome%em welcome$$local Welcome!',
                ] },
                { 'Combat   ' : [
                    'On my mark...%em stop$$local On my mark...',
                    'ATTACK!%em attack$$local ATTACK!',
                    'Don\'t attack!%em no$$local Don\'t attack!',
                    'Stop!%em stop$$local Stop!',
                    'Come get some!%em taunt1$$local Come get some!',
                ] },
                { 'Travel'    : [
                    'Lead On!%em thumbsup$$local Lead On!',
                    'Onward!%em points$$local Onward!',
                    'Follow me!%em point$$local Follow me!',
                    'Stop!%em stop$$local Stop!',
                    'Wait Here%em stop$$local Wait here.',
                    'Let\'s go!%em thumbsup$$local Let\'s go!',
                    'On my way%local On my way.',
                    'Over here!%em bigwave%%local Over here!',
                    'Where to?%em shrug$$local Where to?',
                    'Ready?%local Ready?',
                    'Get a mission?%local Get a mission?',
                ] },
                { 'Speech'    : [
                    'Yes%em thumbsup$$local Yes',
                    'Yes sir!%em salute$$local Yes sir!',
                    'No%em no$$No',
                    'Huh?%em shrug$$local Huh?'
                    'Good job!%em thumbsup$$Good job!',
                    'Sorry%em bow$$local Sorry',
                    'Thank You%em thanks$$local Thank You',
                    'You\'re Welcome%em yourewelcome$$local You\'re Welcome',
                    'No Problem%em thumbsup$$No Problem',
                    'Grrrrrrrr!%em beatchest$$local Grrrrrrrr!',
                    'Arrrrggggh!%em frustrated$$local Arrrrggggh!',
                    'Excellent!%em clap$$local Excellent!',
                    'Mua Ha Ha Ha!%em evillaugh$$local Mua ha ha ha!',
                ] },
                '---',
                'Chat|Talk', 'Lecture', 'Explain',
                '---',
                'Nod', 'Thumbs Up|yes', 'Shrug|huh', 'Thanks', 'Welcome', 'You\'re Welcome|YoureWelcome',
                '---',
                'Disagree|no', 'Shake Head|No', 'Yada Yada Yada|Yata', 'Talk to the Hand|TalkToHand',
            ]},
            { 'Interact' : [
                'Salute', 'Military Salute', 'Praetorian Salute', 'At Ease',
                '---',
                'Bow', 'Fancy Bow', 'Clap', 'Praise', 'Camera',
                '---',
                'You bow down!|bowdown', 'Surrender', 'Get Some', 'Go Away', 'Taunt 1', 'Taunt 2',
                'Chicken', 'Slash Throat', 'Bring it!', 'Threaten|threathand', 'Hands Up', 'Smack',
                'Slap', 'Slap React', 'Alakazam!', 'Alakazam! React', 'Bat Smash',
                'Bat Smash React', 'Ultimate Power', 'Facepalm', 'Double Facepalm',
                '---',
                { 'Judge' : [
                    'Score 1', 'Score 2', 'Score 3', 'Score 4', 'Score 5',
                    'Score 6', 'Score 7', 'Score 8', 'Score 9', 'Score 10',
                ] },
                { 'Decide' : [
                    'Coin Toss|coin', 'Roll Dice|dice', 'Observe Dice', 'High Roller|dice7',
                    '---',
                    'Rock', 'Paper', 'Scissors',
                ] },
                { 'Environment' : [
                    'Peer In', 'Touch Screen|screen', 'Type', 'Research', 'Research Low',  'Dig',
                    'Jackhammer', 'Spraypaint', 'Warm Hands', 'Pick Lock', 'Throw Snowflakes|snowflakes',
                    '---',
                    'Sit Chair 1', 'Sit Chair 2', 'Sit Chair 3', 'Sit Bench 1', 'Sit Bench 2',
                    'Sit Bench 3', 'Sit Bench 4', 'Sit Executive Chair', 'Sit Stool',
                    'Sit Table 1', 'Sit Table 2', 'Sit Ledge|ledgesit',
                    '---',
                    'Wall Lean', 'Assume the Position|assumepositionwall',
                ]},
            ]},
            { 'Actions'  : [
                'Wave', 'Big Wave', 'Raise Hand', 'Point', 'Attack',
                '---',
                'Cheer', 'Wave Fist', 'Crack Knuckles|crack', 'Whistle', 'Victory', 'Winner', 'The Wave',
                '---',
                'Angry', 'Frustrated', 'Curse You', 'Roar', 'Howl', 'Tarzan', 'Growl', 'Show Off',
                '---',
                'Dust Off', 'Read Book', 'Burp',
                '---',
                'Laughs|laugh', 'Giggle|laugh2', 'Drat', 'Shucks', 'Grief', 'Flipping Coin', 'Drink Enriche',
                'Open Gift', 'Ghoul Flex', 'Tantrum', 'Collapse', 'Swoon',
                '---',
                { 'Athletics' : [
                    'Backflip', 'Flex 1', 'Flex 2', 'Flex 3', 'Jumping Jacks', 'Kata', 'Pushups',
                ] },
                { 'Wedding' : [
                    'Propose, Throw Rice', 'Throw Confetti', 'Throw Rose Petals',
                ] },
                { 'Animal': [
                    'Hiss', 'Sniff', 'Savage',
                ] },
                { 'Holiday' : [
                    'Throw Snowflakes|snowflakes', 'Offer Gift', 'Receive Gift',
                ] },
                { 'Steam Punk': [
                    'Inspiration', 'Hot Temper', 'Train Whistle',
                ]},
            ]},
            { 'Idle'     : [
                'Afraid', 'Fish|fishing', 'Binoculars', 'Flashlight', 'Flashlight (Up)', 'Flashlight (Down)', 'Clipboard',
                'Invent', 'Panhandle', 'Stunned|wounded', 'Plotting|plot', 'Floating Books|floatbooks',
                'Pamphlet', 'Vendor', 'Protest', 'Listen to Policeband|ListenPoliceBand',
                'Protest Loyalists|protestloyalist', 'Protest Resistance',
                '---',
                'Robot Power Up|powerup', 'Robot Power Down|powerdown',
                'Listen to Stolen Policeband|ListenStolenPoliceBand', 'Tablet Write|matablet',
                'Calculate Theories|calculate', 'Mix Formula', 'Talk Pool|pool', 'Soccer Kick|soccer',
                'Basketball Dribble|basketball', 'Catch Breath',
                '---',
                'Drink', 'Eat Food', 'Eat Donut', 'Drink Tea|teabag',
                { 'Away' : [
                    'Cellphone', 'Crouch', 'Kneel', 'Use Laptop|laptop', 'Lotus', 'Read Newspaper|newspaper',
                    'AFK Sleep|sleep', 'Sit on Ground|sit', 'Wait|waiting',
                ]},
                { 'Evil' : [
                    'Hold Bat|batlookout', 'Evil Laugh', 'Hold Torch', 'Scheme',
                ]},
                { 'Magic': [
                    'Card Trick', 'Juggle', 'Juggle Magic', 'Juggle Fire', 'Juggle Electricity',
                ]},
                { 'Stances' : [
                    'Center Stance|idle2', 'Cross Arms', 'Hands on Hips|akimbo', 'Neutral Stance|idle1',
                    'Hero Stance 1|stancehero1', 'Hero Stance 2|stancehero2',
                    'Villain Stance 1|stancevillain1', 'Villain Stance 2|stancevillain2',
                ]},
                { 'Loyalty': [
                    'Hero Loyal', 'Vigilante Loyal', 'Villain Loyal', 'Rogue Loyal',
                ]}
            ] },
            { 'Music'    : [
                'Boombox',
                { 'Tracklist': [
                    'Track - Altitude|BBAltitude',
                    'Track - Beat|BBBeat',
                    'Track - Catch Me|BBCatchMe',
                    'Track - Dance|BBDance',
                    'Track - Electro Vibe|BBElectroVibe',
                    'Track - Disco Freak|BBDiscoFreak',
                    'Track - Dog Walk|BBDogWalk',
                    'Track - Heavy Dude|BBHeavyDude',
                    'Track - Info Overload|BBInfoOverload',
                    'Track - Jumpy|BBJumpy',
                    'Track - Kick It|BBKickIt',
                    'Track - Looker|BBLooker',
                    'Track - Meaty|BBMeaty',
                    'Track - Notorious|BBNotorious',
                    'Track - Move On|BBMoveOn',
                    'Track - Peace|BBPeace',
                    'Track - Quickie|BBQuickie',
                    'Track - Raver|BBRaver',
                    'Track - Shuffle|BBShuffle',
                    'Track - Technoid|BBTechnoid',
                    'Track - Wind It Up|BBWindItUp',
                    'Track - Venus|BBVenus',
                    'Track - Wah Wah|BBWahWah',
                    'Track - Yellow|BBYellow',
                    'Track - Spaz|BBSpaz',
                ] },
                '---',
                'Dance', 'Shuffle|dance1', 'Rock It|dance2', 'The Washer|dance3', 'Raise the Roof|dance4',
                'Bounce|dance5', 'The Monkey|dance6', 'Drum Dance|drum', 'Robot Dance', 'Karate Dance',
                'Pop Dance', 'Air Guitar', 'Disco Dance',
                '---',
                'Big Drum|drum', 'Small Drum|drumlow',
            ] },
        ],
        'costumechange' : [
            'Backflip',
            'Cast',
            'Confetti Throw',
            'Dimension Shift',
            'Drink Formula',
            'Energy Morph',
            'Evil Laugh',
            'Feather Burst',
            'Feather Spin',
            'Fireworks',
            'Fur Burst',
            'Fur Spin',
            'Gift Burst',
            'Howl',
            'Ice Block',
            'Inner Will',
            'Light Magic',
            'Lightning',
            'Murder Of Crows',
            'Ninja Leap',
            'Nuke',
            'Oil Strike',
            'Peacebringer',
            'Pressure Release',
            'Presto Chango',
            'Pure Energy',
            'Rainbow',
            'Rapid Boil',
            'Salute',
            'Smoke Bomb',
            'Spin',
            'Stone Block',
            'Super Serum',
            'Vanguard Sigil',
            'Vanguard Sigil',
            'Warshade',
        ],
}



# TODO -- these emotes seem not to be in the in-game picker.  Really really investigate
"""
            'Cameraphone',
            'Despair',
            'FireworkBloom',
            'FireworkRocket',
            'FireworkSparkle',
            'Flypose1',
            'Flypose2',
            'Flypose3',
            'Flypose4',
            'Hi',
            'Hmmm',
            'HotTemper',
            'Liedown',
            'Lookup',
            'None',
            'Shocked',
            'Slrcamera',
            'Smartphone',
            'Text',
            'WalkieTalkie',
            'Welcome',
            'YataYata',
"""
