loadup                                          = {}
loadup["atnumber"]                              = 1
loadup["archetype"]                             = "Blaster"
loadup["petaction"]                             = {}
loadup["petaction"]["selall"]                   = "LALT+V"
loadup["petaction"]["setagg"]                   = "LALT+A"
loadup["petaction"]["sayall"]                   = "Orders?"
loadup["petaction"]["setpas"]                   = "LALT+D"
loadup["petaction"]["selmin"]                   = "LALT+Z"
loadup["petaction"]["cmdmethod"]                = 3
loadup["petaction"]["sayatk"]                   = "Open Fire!"
loadup["petaction"]["cmdfol"]                   = "LALT+W"
loadup["petaction"]["saymin"]                   = "Orders?"
loadup["petaction"]["saylts"]                   = "Orders?"
loadup["petaction"]["sayfol"]                   = "Falling In."
loadup["petaction"]["primnumber"]               = 1
loadup["petaction"]["saydef"]                   = "Return Fire Only."
loadup["petaction"]["cmdsty"]                   = "LALT+E"
loadup["petaction"]["selbos"]                   = "LALT+C"
loadup["petaction"]["primary"]                  = "Mercenaries"
loadup["petaction"]["saygo"]                    = "Moving to Checkpoint."
loadup["petaction"]["selmethod"]                = 3
loadup["petaction"]["cmdgoto"]                  = "LALT+LBUTTON"
loadup["petaction"]["setdef"]                   = "LALT+S"
loadup["petaction"]["saysty"]                   = "Holding this Position."
loadup["petaction"]["sayagg"]                   = "Kill on Sight."
loadup["petaction"]["cmdatk"]                   = "LALT+Q"
loadup["petaction"]["saypas"]                   = "At Ease."
loadup["petaction"]["saybos"]                   = "Orders?"
loadup["petaction"]["sellts"]                   = "LALT+X"
loadup["binds_label"]                           = {}
loadup["binds_label"]["LALT+F6"]                = ''
loadup["binds_label"]["LSHIFT+LCTRL+T"]         = ''
loadup["binds_label"]["LSHIFT"]                 = ''
loadup["binds_label"]["LALT+V"]                 = ''
loadup["binds_label"]["LSHIFT+E"]               = ''
loadup["binds_label"]["LALT+Q"]                 = ''
loadup["binds_label"]["LALT+X"]                 = ''
loadup["binds_label"]["LSHIFT+A"]               = ''
loadup["binds_label"]["LALT+A"]                 = ''
loadup["binds_label"]["LALT+W"]                 = ''
loadup["binds_label"]["LSHIFT+SPACE"]           = ''
loadup["binds_label"]["LCTRL+M"]                = ''
loadup["binds_label"]["LSHIFT+W"]               = ''
loadup["binds_label"]["LSHIFT+LCTRL+LBUTTON"]   = ''
loadup["binds_label"]["LALT+C"]                 = ''
loadup["binds_label"]["LSHIFT+LCTRL"]           = ''
loadup["binds_label"]["LSHIFT+Q"]               = ''
loadup["binds_label"]["LSHIFT+LBUTTON"]         = ''
loadup["binds_label"]["A"]                      = ''
loadup["binds_label"]["TILDE"]                  = ''
loadup["binds_label"]["C"]                      = ''
loadup["binds_label"]["LALT+F1"]                = ''
loadup["binds_label"]["LALT+D"]                 = ''
loadup["binds_label"]["D"]                      = ''
loadup["binds_label"]["LALT+F4"]                = ''
loadup["binds_label"]["LALT+E"]                 = ''
loadup["binds_label"]["LSHIFT+D"]               = ''
loadup["binds_label"]["LCTRL+R"]                = ''
loadup["binds_label"]["LALT+S"]                 = ''
loadup["binds_label"]["LALT+F5"]                = ''
loadup["binds_label"]["LSHIFT+S"]               = ''
loadup["binds_label"]["LALT+LBUTTON"]           = ''
loadup["binds_label"]["LALT+F2"]                = ''
loadup["binds_label"]["LALT+F3"]                = ''
loadup["binds_label"]["P"]                      = ''
loadup["binds_label"]["S"]                      = ''
loadup["binds_label"]["R"]                      = ''
loadup["binds_label"]["T"]                      = ''
loadup["binds_label"]["W"]                      = ''
loadup["binds_label"]["LALT+Z"]                 = ''
loadup["binds_label"]["X"]                      = ''
loadup["binds_label"]["F"]                      = ''
loadup["binds_label"]["SPACE"]                  = ''
loadup["binds_label"]["LCTRL+T"]                = ''
loadup["inspop"]                                = {}
loadup["inspop"]["defkey"]                      = "LSHIFT+W"
loadup["inspop"]["hpkey"]                       = "LSHIFT+S"
loadup["inspop"]["reskey"]                      = "LSHIFT+SPACE"
loadup["inspop"]["bfkey"]                       = "LSHIFT+E"
loadup["inspop"]["acckey"]                      = "LSHIFT+A"
loadup["inspop"]["endkey"]                      = "LSHIFT+Q"
loadup["inspop"]["damkey"]                      = "LSHIFT+D"
loadup["fps"]                                   = {}
loadup["fps"]["bindkey"]                        = "P"
loadup["fps"]["dialog"]                         = ''
loadup["petselect"]                             = {}
loadup["petselect"]["sel4"]                     = "LALT+F5"
loadup["petselect"]["sel1"]                     = "LALT+F2"
loadup["petselect"]["sel3"]                     = "LALT+F4"
loadup["petselect"]["sel0"]                     = "LALT+F1"
loadup["petselect"]["sel5"]                     = "LALT+F6"
loadup["petselect"]["sel2"]                     = "LALT+F3"
loadup["name"]                                  = "profile"
loadup["SoD"]                                   = {}
loadup["SoD"]["FlyModeKey"]                     = "F"
loadup["SoD"]["FollowKey"]                      = "TILDE"
loadup["SoD"]["Left"]                           = "A"
loadup["SoD"]["Back"]                           = "S"
loadup["SoD"]["JumpModeKey"]                    = "T"
loadup["SoD"]["TP"]                             = {}
loadup["SoD"]["TP"]["ComboKey"]                 = "LSHIFT"
loadup["SoD"]["TP"]["Enable"]                   = ''
loadup["SoD"]["TP"]["BindKey"]                  = "LSHIFT+LBUTTON"
loadup["SoD"]["TP"]["ResetKey"]                 = "LCTRL+T"
loadup["SoD"]["Fly"]                            = {}
loadup["SoD"]["Fly"]["Hover"]                   = ''
loadup["SoD"]["Fly"]["GFly"]                    = ''
loadup["SoD"]["Fly"]["Camdist"]                 = "60"
loadup["SoD"]["Detail"]                         = {}
loadup["SoD"]["Detail"]["MovingAmt"]            = "0.5"
loadup["SoD"]["Detail"]["NormalAmt"]            = "1.0"
loadup["SoD"]["Dwarf"]                          = {}
loadup["SoD"]["Dwarf"]["PowerTray"]             = "5"
loadup["SoD"]["Dwarf"]["ModeKey"]               = "G"
loadup["SoD"]["SS"]                             = {}
loadup["SoD"]["SS"]["SS"]                       = ''
loadup["SoD"]["Right"]                          = "D"
loadup["SoD"]["Up"]                             = "SPACE"
loadup["SoD"]["Nova"]                           = {}
loadup["SoD"]["Nova"]["PowerTray"]              = "4"
loadup["SoD"]["Nova"]["ModeKey"]                = "T"
loadup["SoD"]["Jump"]                           = {}
loadup["SoD"]["Jump"]["SJ"]                     = ''
loadup["SoD"]["Run"]                            = {}
loadup["SoD"]["Run"]["Camdist"]                 = "15"
loadup["SoD"]["Run"]["SecondaryNumber"]         = 1
loadup["SoD"]["Run"]["PrimaryNumber"]           = 1
loadup["SoD"]["Run"]["Primary"]                 = "None"
loadup["SoD"]["Run"]["Secondary"]               = "Sprint"
loadup["SoD"]["GFlyModeKey"]                    = "G"
loadup["SoD"]["Unqueue"]                        = 1
loadup["SoD"]["ToggleKey"]                      = "LCTRL+M"
loadup["SoD"]["Version"]                        = 0.3
loadup["SoD"]["TTP"]                            = {}
loadup["SoD"]["TTP"]["ComboKey"]                = "LSHIFT+LCTRL"
loadup["SoD"]["TTP"]["Enable"]                  = ''
loadup["SoD"]["TTP"]["BindKey"]                 = "LSHIFT+LCTRL+LBUTTON"
loadup["SoD"]["TTP"]["ResetKey"]                = "LSHIFT+LCTRL+T"
loadup["SoD"]["RunModeKey"]                     = "C"
loadup["SoD"]["Forward"]                        = "W"
loadup["SoD"]["Down"]                           = "X"
loadup["SoD"]["AutoRunKey"]                     = "R"
loadup["binds"]                                 = {}
loadup["binds"]["LALT+F6"]                      = "Select Sixth Pet"
loadup["binds"]["LSHIFT+LCTRL+T"]               = "TP ResetKey"
loadup["binds"]["LSHIFT"]                       = "TP ComboKey"
loadup["binds"]["LALT+V"]                       = "Select All Pets"
loadup["binds"]["LSHIFT+E"]                     = "Breakfree Key"
loadup["binds"]["LALT+Q"]                       = "Pet Order: Attack"
loadup["binds"]["LALT+X"]                       = "Select Lieutenants"
loadup["binds"]["LSHIFT+A"]                     = "Accuracy Key"
loadup["binds"]["LALT+A"]                       = "Set Aggressive"
loadup["binds"]["LALT+W"]                       = "Pet Order: Follow"
loadup["binds"]["LSHIFT+SPACE"]                 = "Resistance Key"
loadup["binds"]["LCTRL+M"]                      = "Normal/SoD Mode Toggle Key"
loadup["binds"]["LSHIFT+W"]                     = "Defense Key"
loadup["binds"]["LSHIFT+LCTRL+LBUTTON"]         = "Teleport Bind"
loadup["binds"]["LALT+C"]                       = "Select Boss"
loadup["binds"]["LSHIFT+LCTRL"]                 = "TTP ComboKey"
loadup["binds"]["LSHIFT+Q"]                     = "Endurance Key"
loadup["binds"]["LSHIFT+LBUTTON"]               = "Teleport Bind"
loadup["binds"]["A"]                            = "Left Key"
loadup["binds"]["TILDE"]                        = "Follow Key"
loadup["binds"]["C"]                            = "Speed Mode Key"
loadup["binds"]["LALT+F1"]                      = "Select First Pet"
loadup["binds"]["LALT+D"]                       = "Set Passive"
loadup["binds"]["D"]                            = "Right Key"
loadup["binds"]["LALT+F4"]                      = "Select Fourth Pet"
loadup["binds"]["LALT+E"]                       = "Pet Order: Stay"
loadup["binds"]["LSHIFT+D"]                     = "Damage Key"
loadup["binds"]["LCTRL+R"]                      = "Binds Reset Key"
loadup["binds"]["LALT+S"]                       = "Set Defense"
loadup["binds"]["LALT+F5"]                      = "Select Fifth Pet"
loadup["binds"]["LSHIFT+S"]                     = "Healing Key"
loadup["binds"]["LALT+LBUTTON"]                 = "Pet Order: Goto"
loadup["binds"]["LALT+F2"]                      = "Select Second Pet"
loadup["binds"]["LALT+F3"]                      = "Select Third Pet"
loadup["binds"]["P"]                            = "FPS Display Toggle"
loadup["binds"]["S"]                            = "Back Key"
loadup["binds"]["R"]                            = "AutoRun Key"
loadup["binds"]["T"]                            = "Jump Mode Key"
loadup["binds"]["W"]                            = "Forward Key"
loadup["binds"]["LALT+Z"]                       = "Select Minions"
loadup["binds"]["X"]                            = "Down Key"
loadup["binds"]["F"]                            = "Fly Mode Key"
loadup["binds"]["SPACE"]                        = "Up Key"
loadup["binds"]["LCTRL+T"]                      = "TP ResetKey"
loadup["binds"]["LALT+M"]                       = "Pet Action Bind Chatty Mode Toggle"
loadup["binds_tk"]                              = {}
loadup["binds_tk"]["LALT+F6"]                   = {}
loadup["binds_tk"]["LALT+F6"]["t"]              = loadup["petselect"]
loadup["binds_tk"]["LALT+F6"]["k"]              = "sel5"
loadup["binds_tk"]["LSHIFT+LCTRL+T"]            = {}
loadup["binds_tk"]["LSHIFT+LCTRL+T"]["t"]       = loadup["SoD"]["TTP"]
loadup["binds_tk"]["LSHIFT+LCTRL+T"]["k"]       = "ResetKey"
loadup["binds_tk"]["LSHIFT"]                    = {}
loadup["binds_tk"]["LSHIFT"]["t"]               = loadup["SoD"]["TP"]
loadup["binds_tk"]["LSHIFT"]["k"]               = "ComboKey"
loadup["binds_tk"]["LALT+V"]                    = {}
loadup["binds_tk"]["LALT+V"]["t"]               = loadup["petaction"]
loadup["binds_tk"]["LALT+V"]["k"]               = "selall"
loadup["binds_tk"]["LSHIFT+E"]                  = {}
loadup["binds_tk"]["LSHIFT+E"]["t"]             = loadup["inspop"]
loadup["binds_tk"]["LSHIFT+E"]["k"]             = "bfkey"
loadup["binds_tk"]["LALT+Q"]                    = {}
loadup["binds_tk"]["LALT+Q"]["t"]               = loadup["petaction"]
loadup["binds_tk"]["LALT+Q"]["k"]               = "cmdatk"
loadup["binds_tk"]["LALT+X"]                    = {}
loadup["binds_tk"]["LALT+X"]["t"]               = loadup["petaction"]
loadup["binds_tk"]["LALT+X"]["k"]               = "sellts"
loadup["binds_tk"]["LSHIFT+A"]                  = {}
loadup["binds_tk"]["LSHIFT+A"]["t"]             = loadup["inspop"]
loadup["binds_tk"]["LSHIFT+A"]["k"]             = "acckey"
loadup["binds_tk"]["LALT+A"]                    = {}
loadup["binds_tk"]["LALT+A"]["t"]               = loadup["petaction"]
loadup["binds_tk"]["LALT+A"]["k"]               = "setagg"
loadup["binds_tk"]["LALT+Z"]                    = {}
loadup["binds_tk"]["LALT+Z"]["t"]               = loadup["petaction"]
loadup["binds_tk"]["LALT+Z"]["k"]               = "selmin"
loadup["binds_tk"]["LSHIFT+SPACE"]              = {}
loadup["binds_tk"]["LSHIFT+SPACE"]["t"]         = loadup["inspop"]
loadup["binds_tk"]["LSHIFT+SPACE"]["k"]         = "reskey"
loadup["binds_tk"]["lshift+e"]                  = {}
loadup["binds_tk"]["F2"]                        = {}
loadup["binds_tk"]["LCTRL+M"]                   = {}
loadup["binds_tk"]["LCTRL+M"]["t"]              = loadup["SoD"]
loadup["binds_tk"]["LCTRL+M"]["k"]              = "ToggleKey"
loadup["binds_tk"]["F4"]                        = {}
loadup["binds_tk"]["LSHIFT+LCTRL+LBUTTON"]      = {}
loadup["binds_tk"]["LSHIFT+LCTRL+LBUTTON"]["t"] = loadup["SoD"]["TTP"]
loadup["binds_tk"]["LSHIFT+LCTRL+LBUTTON"]["k"] = "BindKey"
loadup["binds_tk"]["F6"]                        = {}
loadup["binds_tk"]["P"]                         = {}
loadup["binds_tk"]["P"]["t"]                    = loadup["fps"]
loadup["binds_tk"]["P"]["k"]                    = "bindkey"
loadup["binds_tk"]["LALT+C"]                    = {}
loadup["binds_tk"]["LALT+C"]["t"]               = loadup["petaction"]
loadup["binds_tk"]["LALT+C"]["k"]               = "selbos"
loadup["binds_tk"]["LSHIFT+LBUTTON"]            = {}
loadup["binds_tk"]["LSHIFT+LBUTTON"]["t"]       = loadup["SoD"]["TP"]
loadup["binds_tk"]["LSHIFT+LBUTTON"]["k"]       = "BindKey"
loadup["binds_tk"]["LSHIFT+Q"]                  = {}
loadup["binds_tk"]["LSHIFT+Q"]["t"]             = loadup["inspop"]
loadup["binds_tk"]["LSHIFT+Q"]["k"]             = "endkey"
loadup["binds_tk"]["LSHIFT+LCTRL"]              = {}
loadup["binds_tk"]["LSHIFT+LCTRL"]["t"]         = loadup["SoD"]["TTP"]
loadup["binds_tk"]["LSHIFT+LCTRL"]["k"]         = "ComboKey"
loadup["binds_tk"]["LSHIFT+W"]                  = {}
loadup["binds_tk"]["LSHIFT+W"]["t"]             = loadup["inspop"]
loadup["binds_tk"]["LSHIFT+W"]["k"]             = "defkey"
loadup["binds_tk"]["X"]                         = {}
loadup["binds_tk"]["X"]["t"]                    = loadup["SoD"]
loadup["binds_tk"]["X"]["k"]                    = "Down"
loadup["binds_tk"]["LALT+F1"]                   = {}
loadup["binds_tk"]["LALT+F1"]["t"]              = loadup["petselect"]
loadup["binds_tk"]["LALT+F1"]["k"]              = "sel0"
loadup["binds_tk"]["A"]                         = {}
loadup["binds_tk"]["A"]["t"]                    = loadup["SoD"]
loadup["binds_tk"]["A"]["k"]                    = "Left"
loadup["binds_tk"]["LSHIFT+D"]                  = {}
loadup["binds_tk"]["LSHIFT+D"]["t"]             = loadup["inspop"]
loadup["binds_tk"]["LSHIFT+D"]["k"]             = "damkey"
loadup["binds_tk"]["C"]                         = {}
loadup["binds_tk"]["C"]["t"]                    = loadup["SoD"]
loadup["binds_tk"]["C"]["k"]                    = "RunModeKey"
loadup["binds_tk"]["LALT+F2"]                   = {}
loadup["binds_tk"]["LALT+F2"]["t"]              = loadup["petselect"]
loadup["binds_tk"]["LALT+F2"]["k"]              = "sel1"
loadup["binds_tk"]["LALT+D"]                    = {}
loadup["binds_tk"]["LALT+D"]["t"]               = loadup["petaction"]
loadup["binds_tk"]["LALT+D"]["k"]               = "setpas"
loadup["binds_tk"]["D"]                         = {}
loadup["binds_tk"]["D"]["t"]                    = loadup["SoD"]
loadup["binds_tk"]["D"]["k"]                    = "Right"
loadup["binds_tk"]["LALT+F4"]                   = {}
loadup["binds_tk"]["LALT+F4"]["t"]              = loadup["petselect"]
loadup["binds_tk"]["LALT+F4"]["k"]              = "sel3"
loadup["binds_tk"]["LALT+E"]                    = {}
loadup["binds_tk"]["LALT+E"]["t"]               = loadup["petaction"]
loadup["binds_tk"]["LALT+E"]["k"]               = "cmdsty"
loadup["binds_tk"]["LSHIFT+S"]                  = {}
loadup["binds_tk"]["LSHIFT+S"]["t"]             = loadup["inspop"]
loadup["binds_tk"]["LSHIFT+S"]["k"]             = "hpkey"
loadup["binds_tk"]["LCTRL+R"]                   = {}
loadup["binds_tk"]["LCTRL+R"]["t"]              = loadup
loadup["binds_tk"]["LCTRL+R"]["k"]              = "ResetKey"
loadup["binds_tk"]["LALT+S"]                    = {}
loadup["binds_tk"]["LALT+S"]["t"]               = loadup["petaction"]
loadup["binds_tk"]["LALT+S"]["k"]               = "setdef"
loadup["binds_tk"]["LCTRL+T"]                   = {}
loadup["binds_tk"]["LCTRL+T"]["t"]              = loadup["SoD"]["TP"]
loadup["binds_tk"]["LCTRL+T"]["k"]              = "ResetKey"
loadup["binds_tk"]["lshift+a"]                  = {}
loadup["binds_tk"]["LALT+F5"]                   = {}
loadup["binds_tk"]["LALT+F5"]["t"]              = loadup["petselect"]
loadup["binds_tk"]["LALT+F5"]["k"]              = "sel4"
loadup["binds_tk"]["lshift+d"]                  = {}
loadup["binds_tk"]["LALT+F3"]                   = {}
loadup["binds_tk"]["LALT+F3"]["t"]              = loadup["petselect"]
loadup["binds_tk"]["LALT+F3"]["k"]              = "sel2"
loadup["binds_tk"]["F3"]                        = {}
loadup["binds_tk"]["F1"]                        = {}
loadup["binds_tk"]["S"]                         = {}
loadup["binds_tk"]["S"]["t"]                    = loadup["SoD"]
loadup["binds_tk"]["S"]["k"]                    = "Back"
loadup["binds_tk"]["R"]                         = {}
loadup["binds_tk"]["R"]["t"]                    = loadup["SoD"]
loadup["binds_tk"]["R"]["k"]                    = "AutoRunKey"
loadup["binds_tk"]["F5"]                        = {}
loadup["binds_tk"]["T"]                         = {}
loadup["binds_tk"]["T"]["t"]                    = loadup["SoD"]
loadup["binds_tk"]["T"]["k"]                    = "JumpModeKey"
loadup["binds_tk"]["W"]                         = {}
loadup["binds_tk"]["W"]["t"]                    = loadup["SoD"]
loadup["binds_tk"]["W"]["k"]                    = "Forward"
loadup["binds_tk"]["lshift+q"]                  = {}
loadup["binds_tk"]["F"]                         = {}
loadup["binds_tk"]["F"]["t"]                    = loadup["SoD"]
loadup["binds_tk"]["F"]["k"]                    = "FlyModeKey"
loadup["binds_tk"]["TILDE"]                     = {}
loadup["binds_tk"]["TILDE"]["t"]                = loadup["SoD"]
loadup["binds_tk"]["TILDE"]["k"]                = "FollowKey"
loadup["binds_tk"]["LALT+LBUTTON"]              = {}
loadup["binds_tk"]["LALT+LBUTTON"]["t"]         = loadup["petaction"]
loadup["binds_tk"]["LALT+LBUTTON"]["k"]         = "cmdgoto"
loadup["binds_tk"]["SPACE"]                     = {}
loadup["binds_tk"]["SPACE"]["t"]                = loadup["SoD"]
loadup["binds_tk"]["SPACE"]["k"]                = "Up"
loadup["binds_tk"]["lshift+s"]                  = {}
loadup["binds_tk"]["LALT+W"]                    = {}
loadup["binds_tk"]["LALT+W"]["t"]               = loadup["petaction"]
loadup["binds_tk"]["LALT+W"]["k"]               = "cmdfol"
loadup["binds_tk"]["lshift+w"]                  = {}
loadup["binds_tk"]["lshift+space"]              = {}
loadup["binds_tk"]["LALT+M"]                    = {}
loadup["binds_tk"]["LALT+M"]["t"]               = loadup["petaction"]
loadup["binds_tk"]["LALT+M"]["k"]               = "chattykey"
loadup["base"]                                  = "c:\\coh\\profile"
loadup["ResetKey"]                              = "LCTRL+R"
