from typing import Dict, Any

Archetypes: Dict[Any, Any] = {
    'Arachnos Soldier': {
        'Epic': {
            'Leviathan Mastery' : [ 'Spirit Shark', 'School of Sharks', 'Arctic Breath', 'Bile Spray', 'Summon Guardian', ],
            'Mace Mastery'      : [ 'Mace Blast', 'Web Envelope', 'Disruptor Blast', 'Shatter Armor', 'Summon Blaster', ],
            'Mu Mastery'        : [ 'Mu Lightning', 'Electrifying Fences', 'Ball Lightning', 'Static Discharge', 'Summon Striker', ],
            'Soul Mastery'      : [ 'Gloom', 'Soul Tentacles', 'Darkest Night', 'Dark Obliteration', 'Summon Widow', ],
        },
        'Primary': {
            'Crab Spider Soldier' : [ 'Single Shot', 'Pummel', 'Burst', 'Wide Area Web Grenade', 'Heavy Burst', 'Bayonet', 'Venom Grenade', 'Frag Grenade',
                                      'Channelgun', 'Slice', 'Longfang', 'Aim', 'Suppression', 'Arm Lash', 'Venom Grenade', 'Frag Grenade', 'Frenzy', 'Omega Maneuver', ],
            'Bane Spider Soldier' : [ 'Single Shot', 'Pummel', 'Burst', 'Wide Area Web Grenade', 'Heavy Burst', 'Bayonet', 'Venom Grenade', 'Frag Grenade',
                                      'Bash', 'Mace Beam', 'Mace Beam Blast', 'Build Up', 'Mace Beam Volley', 'Poisonous Ray', 'Pulverize', 'Shatter', 'Placate', 'Crowd Control', ],
        },
        'Secondary': {
            'Crab Spider Training' : [ 'Wolf Spider Armor', 'Combat Training: Defensive', 'Combat Training: Offensive', 'Tactical Training: Maneuvers',
                                       'Tactical Training: Assault', 'Tactical Training: Leadership', 'Mental Training', 'Call Reinforcements',
                                       'Crab Spider Armor Upgrade', 'Fortification', 'Serum', 'Summon Spiderlings', ],
            'Bane Spider Training' : [ 'Wolf Spider Armor', 'Combat Training: Defensive', 'Combat Training: Offensive', 'Tactical Training: Maneuvers',
                                       'Tactical Training: Assault', 'Tactical Training: Leadership', 'Mental Training', 'Call Reinforcements',
                                       'Bane Spider Armor Upgrade', 'Cloaking Device', 'Surveillance', 'Web Cocoon', ],
        },
    },
    'Arachnos Widow': {
        'Epic': {
            'Leviathan Mastery' : [ 'Spirit Shark', 'School of Sharks', 'Arctic Breath', 'Bile Spray', 'Summon Guardian', ],
            'Mace Mastery'      : [ 'Mace Blast', 'Web Envelope', 'Disruptor Blast', 'Shatter Armor', 'Summon Blaster', ],
            'Mu Mastery'        : [ 'Mu Lightning', 'Electrifying Fences', 'Ball Lightning', 'Static Discharge', 'Summon Striker', ],
            'Soul Mastery'      : [ 'Gloom', 'Soul Tentacles', 'Darkest Night', 'Dark Obliteration', 'Summon Widow', ],
        },
        'Primary': {
            'Night Widow Training' : [ 'Poison Dart', 'Swipe', 'Strike', 'Dart Burst', 'Follow Up', 'Spin', 'Lunge', 'Confront',
                                       'Mental Blast', 'Build Up', 'Smoke Grenade', 'Slash', 'Eviscerate', 'Psychic Scream', ],
            'Fortunata Training'   : [ 'Poison Dart', 'Swipe', 'Strike', 'Dart Burst', 'Follow Up', 'Spin', 'Lunge', 'Confront',
                                       'Mental Blast', 'Telekinetic Blast', 'Subdue', 'Aim', 'Psychic Scream', 'Dominate',
                                       'Psionic Tornado', 'Scramble Thoughts', 'Total Domination', 'Psychic Wail', ],
        },
        'Secondary': {
            'Widow Teamwork'     : [ 'Combat Training: Defensive', 'Combat Training: Offensive', 'Tactical Training: Maneuvers', 'Indomitable Will',
                                     'Tactical Training: Assault', 'Tactical Training: Leadership', 'Foresight',
                                     'Mask Presence', 'Mental Training', 'Mind Link', 'Placate', 'Tactical Training: Vengeance', 'Elude', ],
            'Fortunata Teamwork' : [ 'Combat Training: Defensive', 'Combat Training: Offensive', 'Tactical Training: Maneuvers', 'Indomitable Will',
                                     'Tactical Training: Assault', 'Tactical Training: Leadership', 'Foresight',
                                     'Mask Presence', 'Mind Link', 'Confuse', 'Tactical Training: Vengeance', 'Aura of Confusion', ],
        },
    },
    'Blaster': {
        'Epic': {
            'Cold Mastery'       : [ 'Snow Storm', 'Flash Freeze', 'Frozen Armor', 'Hoarfrost', 'Hibernate', ],
            'Electrical Mastery' : [ 'Static Discharge', 'Shocking Bolt', 'Charged Armor', 'Surge of Power', 'EM Pulse', ],
            'Flame Mastery'      : [ 'Bonfire', 'Char', 'Fire Shield', 'Melt Armor', 'Rise of the Phoenix', ],
            'Force Mastery'      : [ 'Personal Force Field', 'Repulsion Field', 'Repulsion Bomb', 'Temp Invulnerability', 'Force of Nature', ],
            'Leviathan Mastery' : [ 'School of Sharks', 'Bile Spray', 'Knockout Blow', 'Shark Skin', 'Spirit Shark Jaws', ],
            'Mace Mastery'      : [ 'Web Envelope', 'Scorpion Shield', 'Mace Beam Volley', 'Summon Spiderlings', 'Web Cocoon', ],
            'Mu Mastery'        : [ 'Static Discharge', 'Charged Armor', 'Electrifying Fences', 'Summon Adept', 'Electric Shackles', ],
            'Munitions Mastery' : [ 'Body Armor', 'Cryo Freeze Ray', 'Sleep Grenade', 'Surveillance', 'LRM Rocket', ],
            'Soul Mastery'      : [ 'Night Fall', 'Dark Embrace', 'Oppressive Gloom', 'Soul Tentacles', 'Soul Storm', ],
        },
        'Primary': {
            'Archery'          : [ 'Snap Shot', 'Aimed Shot', 'Fistful of Arrows', 'Blazing Arrow', 'Aim', 'Explosive Arrow', 'Ranged Shot', 'Stunning Shot', 'Rain of Arrows', ],
            'Assault Rifle'    : [ 'Burst', 'Slug', 'Buckshot', 'M30 Grenade', 'Beanbag', 'Sniper Rifle', 'Flamethrower', 'Ignite', 'Full Auto', ],
            'Beam Rifle'       : [ 'Single Shot', 'Charged Shot', 'Cutting Beam', 'Disintegrate', 'Aim', 'Lancer Shot', 'Penetrating Ray', 'Piercing Beam', 'Overcharge', ],
            'Dark Blast'       : [ 'Dark Blast', 'Gloom', 'Umbral Torrent', 'Aim', 'Moonbeam', 'Tenebrous Tentacles', 'Abyssal Gaze', 'Life Drain', 'Blackstar', ],
            'Dual Pistols'     : [ 'Pistols', 'Dual Wield', 'Empty Clips', {'Swap Ammo' : ['Cryo Ammunition', 'Incendiary Ammunition', 'Chemical Ammunition', ]}, {'Swap Ammo' : ['Cryo Ammunition', 'Incendiary Ammunition', 'Chemical Ammunition', ]}, 'Bullet Rain', 'Suppressive Fire', 'Executioner\'s Shot', 'Piercing Rounds', 'Hail of Bullets', ],
            'Electrical Blast' : [ 'Charged Bolts', 'Lightning Bolt', 'Ball Lightning', 'Short Circuit', 'Aim', 'Zapp', 'Tesla Cage', 'Voltaic Sentinel', 'Thunderous Blast', ],
            'Energy Blast'     : [ 'Power Bolt', 'Power Blast', 'Energy Torrent', 'Power Burst', 'Sniper Blast', 'Aim', 'Power Push', 'Explosive Blast', 'Nova', ],
            'Fire Blast'       : [ 'Flares', 'Fire Blast', 'Fire Ball', 'Rain of Fire', 'Fire Breath', 'Aim', 'Blaze', 'Blazing Bolt', 'Inferno', ],
            'Ice Blast'        : [ 'Ice Bolt', 'Ice Blast', 'Frost Breath', 'Aim', 'Freeze Ray', 'Ice Storm', 'Bitter Ice Blast', 'Bitter Freeze Ray', 'Blizzard', ],
            'Psychic Blast'    : [ 'Psionic Dart', 'Mental Blast', 'Telekinetic Blast', 'Psychic Focus', 'Will Domination', 'Psionic Lance', 'Psionic Tornado', 'Scramble Thoughts', 'Psychic Wail', ],
            'Radiation Blast'  : [ 'Neutrino Bolt', 'X-Ray Beam', 'Irradiate', 'Electron Haze', 'Aim', 'Proton Volley', 'Cosmic Burst', 'Neutron Bomb', 'Atomic Blast', ],
            'Sonic Attack'     : [ 'Shriek', 'Scream', 'Howl', 'Shockwave', 'Shout', 'Amplify', 'Siren\'s Song', 'Screech', 'Dreadful Wail', ],
            'Water Blast'      : [ 'Aqua Bolt', 'Hydro Blast', 'Water Burst', 'Whirlpool', 'Tidal Forces', 'Dehydrate', 'Water Jet', 'Steam Spray', 'Geyser', ],
        },
        'Secondary': {
            'Darkness Manipulation'    : [ 'Penumbral Grasp', 'Smite', 'Death Shroud', 'Shadow Maul', 'Soul Drain', 'Touch of the Beyond', 'Dark Consumption', 'Dark Pit', 'Midnight Grasp' ],
            'Devices'                  : [ 'Web Grenade', 'Caltrops', 'Taser', 'Targeting Drone', 'Smoke Grenade', 'Field Operative', 'Trip Mine', 'Time Bomb', 'Gun Drone', ],
            'Electricity Manipulation' : [ 'Electric Fence', 'Charged Brawl', 'Lightning Field', 'Havoc Punch', 'Build Up', 'Force of Thunder', 'Thunder Strike', 'Power Sink', 'Shocking Grasp', ],
            'Energy Manipulation'      : [ 'Power Thrust', 'Energy Punch', 'Build Up', 'Bone Smasher', 'Energize', 'Staggering Burst', 'Power Boost', 'Boost Range', 'Total Focus', ],
            'Fire Manipulation'        : [ 'Ring of Fire', 'Fire Sword', 'Combustion', 'Fire Sword Circle', 'Build Up', 'Cauterizing Aura', 'Consume', 'Burn', 'Hot Feet', ],
            'Ice Manipulation'         : [ 'Chilblain', 'Frozen Fists', 'Ice Sword', 'Frigid Protection', 'Build Up', 'Ice Patch', 'Shiver', 'Freezing Touch', 'Frozen Aura', ],
            'Martial Combat'           : [ 'Ki Push', 'Storm Kick', 'Reach for the Limit', 'Burst of Speed', 'Dragon\'s Tail', 'Reaction Time', 'Inner Will', 'Throw Sand', 'Eagles Claw', ],
            'Mental Manipulation'      : [ 'Subdual', 'Mind Probe', 'Telekinetic Thrust', 'Psychic Scream', 'Concentration', 'Drain Psyche', 'World of Confusion', 'Scare', 'Psychic Shockwave', ],
        },
    },
    'Brute': {
        'Epic': {
            'Arctic Mastery'    : [ 'Chilblain', 'Block of Ice', 'Ice Blast', 'Shiver', 'Ice Storm', ],
            'Earth Mastery'     : [ 'Stone Prison', 'Salt Crystals', 'Fossilize', 'Quicksand', 'Stalagmites', ],
            'Energy Mastery'    : [ 'Superior Conditioning', 'Focused Accuracy', 'Laser Beam Eyes', 'Physical Perfection', 'Energy Torrent', ],
            'Leviathan Mastery' : [ 'Spirit Shark', 'School of Sharks', 'Arctic Breath', 'Bile Spray', 'Summon Guardian', ],
            'Mace Mastery'      : [ 'Mace Blast', 'Web Envelope', 'Disruptor Blast', 'Focused Accuracy', 'Summon Blaster', ],
            'Mu Mastery'        : [ 'Mu Lightning', 'Electrifying Fences', 'Ball Lightning', 'Static Discharge', 'Summon Striker', ],
            'Psionic Mastery'   : [ 'Mesmerize', 'Dominate', 'Harmonic Mind', 'Mental Blast', 'Psionic Tornado', ],
            'Pyre Mastery'      : [ 'Ring of Fire', 'Char', 'Fire Blast', 'Melt Armor', 'Fire Ball', ],
            'Soul Mastery'      : [ 'Gloom', 'Soul Tentacles', 'Darkest Night', 'Dark Obliteration', 'Summon Widow', ],
        },
        'Primary': {
            'Battle Axe'       : [ 'Beheader', 'Chop', 'Gash', 'Build Up', 'Swoop', 'Taunt', 'Whirling Axe', 'Cleave', 'Pendulum', ],
            'Broad Sword'      : [ 'Hack', 'Slash', 'Slice', 'Build Up', 'Parry', 'Taunt', 'Whirling Sword', 'Disembowel', 'Head Splitter', ],
            'Claws'            : [ 'Swipe', 'Strike', 'Slash', 'Spin', 'Follow Up', 'Taunt', 'Focus', 'Eviscerate', 'Shockwave', ],
            'Dark Melee'       : [ 'Shadow Punch', 'Smite', 'Shadow Maul', 'Touch of Fear', 'Siphon Life', 'Taunt', 'Dark Consumption', 'Soul Drain', 'Midnight Grasp', ],
            'Dual Blades'      : [ 'Nimble Slash', 'Power Slice', 'Ablating Strike', 'Typhoon\'s Edge', 'Blinding Feint', 'Taunt', 'Vengeful Slice', 'Sweeping Strike', 'One Thousand Cuts', ],
            'Electrical Melee' : [ 'Charged Brawl', 'Havoc Punch', 'Jacobs Ladder', 'Build Up', 'Thunder Strike', 'Taunt', 'Chain Induction', 'Lightning Clap', 'Lightning Rod', ],
            'Energy Melee'     : [ 'Barrage', 'Energy Punch', 'Bone Smasher', 'Build Up', 'Whirling Hands', 'Taunt', 'Total Focus', 'Staggering Burst', 'Energy Transfer', ],
            'Fiery Melee'      : [ 'Scorch', 'Fire Sword', 'Cremate', 'Build Up', 'Incinerate', 'Taunt', 'Breath of Fire', 'Fire Sword Circle', 'Greater Fire Sword', ],
            'Katana'           : [ 'Sting of the Wasp', 'Gambler\'s Cut', 'Flashing Steel', 'Build Up', 'Divine Avalanche', 'Dragon\'s Roar', 'The Lotus Drops', 'Soaring Dragon', 'Golden Dragonfly', ],
            'Kinetic Melee'    : [ 'Quick Strike', 'Body Blow', 'Smashing Blow', 'Power Siphon', 'Repulsing Torrent', 'Taunt', 'Burst', 'Focused Burst', 'Concentrated Strike', ],
            'Psionic Melee'    : [ 'Mental Strike', 'Psi Blade', 'Telekinetic Blow', 'Concentration', 'Psi Blade Sweep', 'Taunt', 'Boggle', 'Greater Psi Blade', 'Mass Levitate', ],
            'Radiation Melee'  : [ 'Contaminated Strike', 'Radioactive Smash', 'Proton Sweep', 'Fusion', 'Radiation Siphon', 'Taunt', 'Irradiated Ground', 'Devastating Blow', 'Atom Smasher', ],
            'Savage Melee'     : [ 'Savage Strike', 'Maiming Slash', 'Shred', 'Vicious Slash', 'Rending Flurry', 'Taunt', 'Blood Thirst', 'Hemorrhage', 'Savage Leap', ],
            'Staff Fighting'   : [ 'Mercurial Blow', 'Precise Strike', 'Guarded Spin', 'Eye of the Storm', { 'Staff Mastery': [ 'Form of the Body', 'Form of the Mind', 'Form of the Soul', ]}, 'Taunt', 'Serpent\'s Reach', 'Innocuous Strikes', 'Sky Splitter', ],
            'Stone Melee'      : [ 'Stone Fist', 'Stone Mallet', 'Heavy Mallet', 'Build Up', 'Fault', 'Taunt', 'Seismic Smash', 'Hurl Boulder', 'Tremor', ],
            'Street Justice'   : [ 'Initial Strike', 'Heavy Blow', 'Sweeping Cross', 'Combat Readiness', 'Rib Cracker', 'Taunt', 'Spinning Strike', 'Shin Breaker', 'Crushing Uppercut', ],
            'Super Strength'   : [ 'Jab', 'Punch', 'Haymaker', 'Hand Clap', 'Knockout Blow', 'Taunt', 'Rage', 'Hurl', 'Foot Stomp', ],
            'Titan Weapons'    : [ 'Defensive Sweep', 'Crushing Blow', 'Titan Sweep', 'Build Momentum', 'Follow Through', 'Taunt', 'Rend Armor', 'Whirling Smash', 'Arc of Destruction', ],
            'War Mace'         : [ 'Bash', 'Pulverize', 'Jawbreaker', 'Build Up', 'Clobber', 'Taunt', 'Whirling Mace', 'Shatter', 'Crowd Control', ],
        },
        'Secondary': {
            'Bio Armor'       : [ 'Hardened Carapace', 'Inexhaustible', 'Environmental Modification', {'Adaptation' : ['Efficient Adaptation', 'Defensive Adaptation', 'Offensive Adaptation', ]}, 'Ablative Carapace', 'Evolving Armor', 'DNA Siphon', 'Genetic Contamination', 'Parasitic Aura', ],
            'Dark Armor'      : [ 'Dark Embrace', 'Death Shroud', 'Murky Cloud', 'Obsidian Shield', 'Dark Regeneration', 'Cloak of Darkness', 'Cloak of Fear', 'Oppressive Gloom', 'Soul Transfer', ],
            'Electric Armor'  : [ 'Charged Armor', 'Lightning Field', 'Conductive Shield', 'Static Shield', 'Grounded', 'Lightning Reflexes', 'Energize', 'Power Sink', 'Power Surge ', ],
            'Energy Aura'     : [ 'Kinetic Shield', 'Dampening Field', 'Power Shield', 'Entropic Aura', 'Energy Protection', 'Energy Cloak', 'Energy Drain', 'Energize', 'Overload', ],
            'Fiery Aura'      : [ 'Fire Shield', 'Blazing Aura', 'Healing Flames', 'Temperature Protection', 'Plasma Shield', 'Consume', 'Burn', 'Fiery Embrace', 'Rise of the Phoenix', ],
            'Invulnerability' : [ 'Resist Physical Damage', 'Temp Invulnerability', 'Dull Pain', 'Resist Elements', 'Unyielding', 'Resist Energies', 'Invincibility', 'Tough Hide', 'Unstoppable', ],
            'Radiation Armor' : [ 'Alpha Barrier', 'Gamma Boost', 'Proton Armor', 'Fallout Shelter', 'Radiation Therapy', 'Beta Decay', 'Particle Shielding', 'Ground Zero', 'Meltdown', ],
            'Regeneration'    : [ 'Fast Healing', 'Reconstruction', 'Quick Recovery', 'Dull Pain', 'Integration', 'Resilience', 'Instant Healing', 'Revive', 'Moment of Glory', ],
            'Shield Defense'  : [ 'Deflection', 'Battle Agility', 'True Grit', 'Active Defense', 'Against All Odds', 'Phalanx Fighting', 'Grant Cover', 'Shield Charge', 'One with the Shield', ],
            'Stone Armor'     : [ 'Rock Armor', 'Stone Skin', 'Earth\'s Embrace', 'Mud Pots', 'Rooted', 'Brimstone Armor', 'Crystal Armor', 'Minerals', 'Granite Armor', ],
            'Super Reflexes'  : [ 'Focused Fighting', 'Focused Senses', 'Agile', 'Practiced Brawler', 'Dodge', 'Evasion', 'Lucky', 'Quickness', 'Elude', ],
            'Willpower'       : [ 'High Pain Tolerance', 'Mind Over Body', 'Fast Healing', 'Indomitable Will', 'Rise to the Challenge', 'Quick Recovery', 'Heightened Senses', 'Resurgence', 'Strength of Will', ],
        },
    },
    'Controller': {
        'Epic': {
            'Fire Mastery'          : [ 'Fire Blast', 'Fire Ball', 'Fire Shield', 'Rise of the Phoenix', 'Consume', ],
            'Ice Mastery'           : [ 'Ice Blast', 'Hibernate', 'Frozen Armor', 'Frost Breath', 'Ice Storm', ],
            'Leviathan Mastery'     : [ 'Water Spout', 'Bile Spray', 'Hibernate', 'Shark Skin', 'Summon Coralax', ],
            'Mace Mastery'          : [ 'Poisonous Ray', 'Scorpion Shield', 'Disruptor Blast', 'Focused Accuracy', 'Summon Tarantula', ],
            'Mu Mastery'            : [ 'Power Sink', 'Charged Armor', 'Ball Lightning', 'Surge of Power', 'Summon Guardian', ],
            'Primal Forces Mastery' : [ 'Power Blast', 'Conserve Power', 'Energy Torrent', 'Temp Invulnerability', 'Power Boost', ],
            'Psionic Mastery'       : [ 'Mental Blast', 'Indomitable Will', 'Mind Over Body', 'World of Confusion', 'Psionic Tornado', ],
            'Soul Mastery'          : [ 'Dark Consumption', 'Dark Embrace', 'Dark Obliteration', 'Soul Drain', 'Summon Seer', ],
            'Stone Mastery'         : [ 'Fissure', 'Hurl Boulder', 'Seismic Smash', 'Rock Armor', 'Earth\'s Embrace', ],
        },
        'Primary': {
            'Darkness Control' : [ 'Shadowy Binds', 'Dark Grasp', 'Living Shadows', 'Possess', 'Fearsome Stare', 'Heart of Darkness', 'Haunt', 'Shadow Field', 'Umbra Beast', ],
            'Earth Control'    : [ 'Stone Prison', 'Fossilize', 'Stone Cages', 'Quicksand', 'Salt Crystals', 'Stalagmites', 'Earthquake', 'Volcanic Gasses', 'Animate Stone', ],
            'Electric Control' : [ 'Electric Fence', 'Tesla Cage', 'Chain Fences', 'Jolting Chain', 'Conductive Aura', 'Static Field', 'Paralyzing Blast', 'Synaptic Overload', 'Gremlins', ],
            'Fire Control'     : [ 'Ring of Fire', 'Char', 'Fire Cages', 'Smoke', 'Hot Feet', 'Flashfire', 'Cinders', 'Bonfire', 'Fire Imps', ],
            'Gravity Control'  : [ 'Crush', 'Lift', 'Gravity Distortion', 'Propel', 'Crushing Field', 'Dimension Shift', 'Gravity Distortion Field', 'Wormhole', 'Singularity', ],
            'Ice Control'      : [ 'Chilblain', 'Block of Ice', 'Frostbite', 'Arctic Air', 'Shiver', 'Ice Slick', 'Flash Freeze', 'Glacier', 'Jack Frost', ],
            'Illusion Control' : [ 'Spectral Wounds', 'Blind', 'Deceive', 'Flash', 'Superior Invisibility', 'Group Invisibility', 'Phantom Army', 'Spectral Terror', 'Phantasm', ],
            'Mind Control'     : [ 'Mesmerize', 'Levitate', 'Dominate', 'Confuse', 'Mass Hypnosis', 'Telekinesis', 'Total Domination', 'Terrify', 'Mass Confusion', ],
            'Plant Control'    : [ 'Entangle', 'Strangler', 'Roots', 'Spore Burst', 'Seeds of Confusion', 'Spirit Tree', 'Vines', 'Carrion Creepers', 'Fly Trap', ],
            'Water Control'    : [ 'Deluge', 'Suffocate', 'Hypothermia', 'Geyser Burst', 'Turbulent Aura', 'Riptide', 'Tidal Wave', 'Drowning Pool', 'Water Golem', ],
            'Wind Control'     : [ 'Updraft', 'Downdraft', 'Breathless', 'Wind Shear', 'Thundergust', 'Microburst', 'Keening Winds', 'Vacuum', 'Vortex', ],
        },
        'Secondary': {
            'Cold Domination'     : [ 'Infrigidate', 'Ice Shield', 'Snow Storm', 'Glacial Shield', 'Frostwork', 'Arctic Fog', 'Benumb', 'Sleet', 'Heat Loss', ],
            'Darkness Affinity'   : [ 'Twilight Grasp', 'Tar Patch', 'Darkest Night', 'Howling Twilight', 'Shadow Fall', 'Fade', 'Soul Absorption', 'Black Hole', 'Dark Servant', ],
            'Empathy'             : [ 'Healing Aura', 'Heal Other', 'Absorb Pain', 'Resurrect', 'Clear Mind', 'Fortitude', 'Recovery Aura', 'Regeneration Aura', 'Adrenalin Boost', ],
            'Force Field'         : [ 'Personal Force Field', 'Deflection Shield', 'Force Bolt', 'Insulation Shield', 'Barrier Field', 'Dispersion Bubble', 'Containment Shell', 'Repulsion Bomb', 'Force Bubble', ],
            'Kinetics'            : [ 'Transfusion', 'Siphon Power', 'Repel', 'Siphon Speed', 'Increase Density', 'Speed Boost', 'Inertial Reduction', 'Transference', 'Fulcrum Shift', ],
            'Nature Affinity'     : [ 'Corrosive Enzymes', 'Regrowth', 'Wild Growth', 'Spore Cloud', 'Lifegiving Spores', 'Wild Bastion', 'Rebirth', 'Entangling Aura', 'Overgrowth', ],
            'Poison'              : [ 'Alkaloid', 'Envenom', 'Weaken', 'Neurotoxic Breath', 'Elixir of Life', 'Antidote', 'Paralytic Poison', 'Poison Trap', 'Venomous Gas', ],
            'Radiation Emission'  : [ 'Radiant Aura', 'Radiation Infection', 'Accelerate Metabolism', 'Enervating Field', 'Mutation', 'Lingering Radiation', 'Choking Cloud', 'Fallout', 'EM Pulse', ],
            'Sonic Resonance'     : [ 'Sonic Siphon', 'Sonic Barrier', 'Sonic Haven', 'Sonic Cage', 'Disruption Field', 'Sonic Dispersion', 'Sonic Repulsion', 'Clarity', 'Liquefy', ],
            'Storm Summoning'     : [ 'Gale', 'O2 Boost', 'Snow Storm', 'Steamy Mist', 'Freezing Rain', 'Hurricane', 'Thunder Clap', 'Tornado', 'Lightning Storm', ],
            'Thermal Radiation'   : [ 'Warmth', 'Thermal Shield', 'Cauterize', 'Plasma Shield', 'Power of the Phoenix', 'Thaw', 'Forge', 'Heat Exhaustion', 'Melt Armor', ],
            'Time Manipulation'   : [ 'Time Crawl', 'Temporal Mending', 'Time\'s Juncture', 'Temporal Selection', 'Distortion Field', 'Time Stop', 'Farsight', 'Slowed Response', 'Chrono Shift', ],
            'Trick Arrow'         : [ 'Entangling Arrow', 'Flash Arrow', 'Glue Arrow', 'Ice Arrow', 'Poison Gas Arrow', 'Acid Arrow', 'Disruption Arrow', 'Oil Slick Arrow', 'EMP Arrow', ],
        },
    },
    'Corruptor': {
        'Epic': {
            'Dark Mastery'        : [ 'Oppressive Gloom', 'Dark Consumption', 'Dark Embrace', 'Soul Transfer', 'Spirit Drain', ],
            'Electricity Mastery' : [ 'Electric Fence', 'Thunder Strike', 'Charged Armor', 'Shocking Bolt', 'Power Sink', ],
            'Frost Mastery'       : [ 'Block of Ice', 'Frostbite', 'Frozen Armor', 'Hoarfrost', 'Hibernate', ],
            'Inferno Mastery'     : [ 'Consume', 'Char', 'Bonfire', 'Fire Shield', 'Rise of the Phoenix', ],
            'Leviathan Mastery'   : [ 'School of Sharks', 'Shark Skin', 'Hibernate', 'Spirit Shark Jaws', 'Summon Coralax', ],
            'Mace Mastery'        : [ 'Web Envelope', 'Scorpion Shield', 'Focused Accuracy', 'Web Cocoon', 'Summon Disruptor', ],
            'Mu Mastery'          : [ 'Power Sink', 'Charged Armor', 'Conserve Power', 'Electric Shackles', 'Summon Adept', ],
            'Power Mastery'       : [ 'Conserve Power', 'Power Build Up', 'Force of Nature', 'Temp Invulnerability', 'Total Focus', ],
            'Psychic Mastery'     : [ 'Dominate', 'Mass Hypnosis', 'Mind Over Body', 'World of Confusion', 'Telekinesis', ],
            'Soul Mastery'        : [ 'Soul Drain', 'Dark Embrace', 'Power Boost', 'Soul Storm', 'Summon Mistress', ],
        },
        'Primary': {
            'Archery'          : [ 'Snap Shot', 'Aimed Shot', 'Fistful of Arrows', 'Blazing Arrow', 'Aim', 'Explosive Arrow', 'Ranged Shot', 'Stunning Shot', 'Rain of Arrows', ],
            'Assault Rifle'    : [ 'Burst', 'Slug', 'Buckshot', 'M30 Grenade', 'Beanbag', 'Sniper Rifle', 'Flamethrower', 'Ignite', 'Full Auto', ],
            'Beam Rifle'       : [ 'Single Shot', 'Charged Shot', 'Cutting Beam', 'Disintegrate', 'Aim', 'Lancer Shot', 'Penetrating Ray', 'Piercing Beam', 'Overcharge', ],
            'Dark Blast'       : [ 'Dark Blast', 'Gloom', 'Moonbeam', 'Dark Pit', 'Tenebrous Tentacles', 'Night Fall', 'Torrent', 'Life Drain', 'Blackstar', ],
            'Dual Pistols'     : [ 'Pistols', 'Dual Wield', 'Empty Clips', {'Swap Ammo' : ['Cryo Ammunition', 'Incendiary Ammunition', 'Chemical Ammunition', ]}, {'Swap Ammo' : ['Cryo Ammunition', 'Incendiary Ammunition', 'Chemical Ammunition', ]}, 'Bullet Rain', 'Suppressive Fire', 'Executioner\'s Shot', 'Piercing Rounds', 'Hail of Bullets', ],
            'Electrical Blast' : [ 'Charged Bolts', 'Lightning Bolt', 'Ball Lightning', 'Short Circuit', 'Aim', 'Zapp', 'Tesla Cage', 'Voltaic Sentinel', 'Thunderous Blast', ],
            'Energy Blast'     : [ 'Power Bolt', 'Power Blast', 'Energy Torrent', 'Power Burst', 'Sniper Blast', 'Aim', 'Power Push', 'Explosive Blast', 'Nova', ],
            'Fire Blast'       : [ 'Flares', 'Fire Blast', 'Fire Ball', 'Rain of Fire', 'Fire Breath', 'Aim', 'Blaze', 'Blazing Bolt', 'Inferno', ],
            'Ice Blast'        : [ 'Ice Bolt', 'Ice Blast', 'Frost Breath', 'Aim', 'Freeze Ray', 'Ice Storm', 'Bitter Ice Blast', 'Bitter Freeze Ray', 'Blizzard', ],
            'Psychic Blast'    : [ 'Mental Blast', 'Subdue', 'Psionic Lance', 'Psychic Scream', 'Telekinetic Blast', 'Will Domination', 'Psionic Tornado', 'Scramble Thoughts', 'Psychic Wail', ],
            'Radiation Blast'  : [ 'Neutrino Bolt', 'X-Ray Beam', 'Irradiate', 'Electron Haze', 'Proton Volley', 'Aim', 'Cosmic Burst', 'Neutron Bomb', 'Atomic Blast', ],
            'Sonic Attack'     : [ 'Shriek', 'Scream', 'Howl', 'Shockwave', 'Shout', 'Amplify', 'Siren\'s Song', 'Screech', 'Dreadful Wail', ],
            'Water Blast'      : [ 'Aqua Bolt', 'Hydro Blast', 'Water Burst', 'Whirlpool', 'Tidal Forces', 'Dehydrate', 'Water Jet', 'Steam Spray', 'Geyser', ],
        },
        'Secondary': {
            'Cold Domination'     : [ 'Infrigidate', 'Ice Shield', 'Snow Storm', 'Glacial Shield', 'Frostwork', 'Arctic Fog', 'Benumb', 'Sleet', 'Heat Loss', ],
            'Dark Miasma'         : [ 'Twilight Grasp', 'Tar Patch', 'Darkest Night', 'Howling Twilight', 'Shadow Fall', 'Fearsome Stare', 'Petrifying Gaze', 'Black Hole', 'Dark Servant', ],
            'Force Field'         : [ 'Personal Force Field', 'Deflection Shield', 'Force Bolt', 'Insulation Shield', 'Barrier Field', 'Dispersion Bubble', 'Containment Shell', 'Repulsion Bomb', 'Force Bubble', ],
            'Kinetics'            : [ 'Transfusion', 'Siphon Power', 'Repel', 'Siphon Speed', 'Increase Density', 'Speed Boost', 'Inertial Reduction', 'Transference', 'Fulcrum Shift', ],
            'Nature Affinity'     : [ 'Corrosive Enzymes', 'Regrowth', 'Wild Growth', 'Spore Cloud', 'Lifegiving Spores', 'Wild Bastion', 'Rebirth', 'Entangling Aura', 'Overgrowth', ],
            'Pain Domination'     : [ 'Nullify Pain', 'Soothe', 'Share Pain', 'Conduit of Pain', 'Enforced Morale', 'Soothing Aura', 'World of Pain', 'Anguishing Cry', 'Painbringer', ],
            'Poison'              : [ 'Alkaloid', 'Envenom', 'Weaken', 'Neurotoxic Breath', 'Elixir of Life', 'Antidote', 'Paralytic Poison', 'Poison Trap', 'Venomous Gas', ],
            'Radiation Emission'  : [ 'Radiant Aura', 'Radiation Infection', 'Accelerate Metabolism', 'Enervating Field', 'Mutation', 'Lingering Radiation', 'Choking Cloud', 'Fallout', 'EM Pulse', ],
            'Sonic Resonance'     : [ 'Sonic Siphon', 'Sonic Barrier', 'Sonic Haven', 'Sonic Cage', 'Disruption Field', 'Sonic Dispersion', 'Sonic Repulsion', 'Clarity', 'Liquefy', ],
            'Storm Summoning'     : [ 'Gale', 'O2 Boost', 'Snow Storm', 'Steamy Mist', 'Freezing Rain', 'Hurricane', 'Thunder Clap', 'Tornado', 'Lightning Storm', ],
            'Thermal Radiation'   : [ 'Warmth', 'Fire Shield', 'Cauterize', 'Plasma Shield', 'Power of the Phoenix', 'Thaw', 'Forge', 'Heat Exhaustion', 'Melt Armor', ],
            'Time Manipulation'   : [ 'Time Crawl', 'Temporal Mending', 'Time\'s Juncture', 'Temporal Selection', 'Distortion Field', 'Time Stop', 'Farsight', 'Slowed Response', 'Chrono Shift', ],
            'Traps'               : [ 'Web Grenade', 'Caltrops', 'Triage Beacon', 'Acid Mortar', 'Force Field Generator', 'Poison Trap', 'Seeker Drones', 'Trip Mine', 'Time Bomb', ],
            'Trick Arrow'         : [ 'Entangling Arrow', 'Flash Arrow', 'Glue Arrow', 'Ice Arrow', 'Poison Gas Arrow', 'Acid Arrow', 'Disruption Arrow', 'Oil Slick Arrow', 'EMP Arrow', ],
        },
    },
    'Defender': {
        'Epic': {
            'Dark Mastery'        : [ 'Oppressive Gloom', 'Dark Consumption', 'Dark Embrace', 'Soul Transfer', 'Spirit Drain', ],
            'Electricity Mastery' : [ 'Electric Fence', 'Thunder Strike', 'Charged Armor', 'Shocking Bolt', 'Power Sink', ],
            'Frost Mastery'       : [ 'Block of Ice', 'Frostbite', 'Frozen Armor', 'Hoarfrost', 'Hibernate', ],
            'Inferno Mastery'     : [ 'Consume', 'Char', 'Bonfire', 'Fire Shield', 'Rise of the Phoenix', ],
            'Leviathan Mastery'   : [ 'School of Sharks', 'Shark Skin', 'Hibernate', 'Spirit Shark Jaws', 'Summon Coralax', ],
            'Mace Mastery'        : [ 'Web Envelope', 'Scorpion Shield', 'Focused Accuracy', 'Web Cocoon', 'Summon Disruptor', ],
            'Mu Mastery'          : [ 'Power Sink', 'Charged Armor', 'Conserve Power', 'Electric Shackles', 'Summon Adept', ],
            'Power Mastery'       : [ 'Conserve Power', 'Power Build Up', 'Force of Nature', 'Temp Invulnerability', 'Total Focus', ],
            'Psychic Mastery'     : [ 'Dominate', 'Mass Hypnosis', 'Mind Over Body', 'World of Confusion', 'Telekinesis', ],
            'Soul Mastery'        : [ 'Soul Drain', 'Dark Embrace', 'Power Boost', 'Soul Storm', 'Summon Mistress', ],
        },
        'Primary': {
            'Cold Domination'     : [ 'Infrigidate', 'Ice Shield', 'Snow Storm', 'Glacial Shield', 'Frostwork', 'Arctic Fog', 'Benumb', 'Sleet', 'Heat Loss', ],
            'Dark Miasma'         : [ 'Twilight Grasp', 'Tar Patch', 'Darkest Night', 'Howling Twilight', 'Shadow Fall', 'Fearsome Stare', 'Petrifying Gaze', 'Black Hole', 'Dark Servant', ],
            'Empathy'             : [ 'Healing Aura', 'Heal Other', 'Absorb Pain', 'Resurrect', 'Clear Mind', 'Fortitude', 'Recovery Aura', 'Regeneration Aura', 'Adrenalin Boost', ],
            'Force Field'         : [ 'Personal Force Field', 'Deflection Shield', 'Force Bolt', 'Insulation Shield', 'Detention Field', 'Dispersion Bubble', 'Containment Shell', 'Repulsion Bomb', 'Force Bubble', ],
            'Kinetics'            : [ 'Transfusion', 'Siphon Power', 'Repel', 'Siphon Speed', 'Increase Density', 'Speed Boost', 'Inertial Reduction', 'Transference', 'Fulcrum Shift', ],
            'Nature Affinity'     : [ 'Corrosive Enzymes', 'Regrowth', 'Wild Growth', 'Spore Cloud', 'Lifegiving Spores', 'Wild Bastion', 'Rebirth', 'Entangling Aura', 'Overgrowth', ],
            'Radiation Emission'  : [ 'Radiant Aura', 'Radiation Infection', 'Accelerate Metabolism', 'Enervating Field', 'Mutation', 'Lingering Radiation', 'Choking Cloud', 'Fallout', 'EM Pulse', ],
            'Sonic Resonance'     : [ 'Sonic Siphon', 'Sonic Barrier', 'Sonic Haven', 'Sonic Cage', 'Disruption Field', 'Sonic Dispersion', 'Sonic Repulsion', 'Clarity', 'Liquefy', ],
            'Storm Summoning'     : [ 'Gale', 'O2 Boost', 'Snow Storm', 'Steamy Mist', 'Freezing Rain', 'Hurricane', 'Thunder Clap', 'Tornado', 'Lightning Storm', ],
            'Thermal Radiation'   : [ 'Warmth', 'Thermal Shield', 'Cauterize', 'Plasma Shield', 'Power of the Phoenix', 'Thaw', 'Forge', 'Heat Exhaustion', 'Melt Armor', ],
            'Time Manipulation'   : [ 'Time Crawl', 'Temporal Mending', 'Time\'s Juncture', 'Temporal Selection', 'Distortion Field', 'Time Stop', 'Farsight', 'Slowed Response', 'Chrono Shift', ],
            'Traps'               : [ 'Web Grenade', 'Caltrops', 'Triage Beacon', 'Acid Mortar', 'Force Field Generator', 'Poison Trap', 'Seeker Drones', 'Trip Mine', 'Time Bomb', ],
            'Trick Arrow'         : [ 'Entangling Arrow', 'Flash Arrow', 'Glue Arrow', 'Ice Arrow', 'Poison Gas Arrow', 'Acid Arrow', 'Disruption Arrow', 'Oil Slick Arrow', 'EMP Arrow', ],
        },
        'Secondary': {
            'Archery'          : [ 'Snap Shot', 'Aimed Shot', 'Fistful of Arrows', 'Blazing Arrow', 'Aim', 'Explosive Arrow', 'Ranged Shot', 'Stunning Shot', 'Rain of Arrows', ],
            'Assault Rifle'    : [ 'Burst', 'Slug', 'Buckshot', 'M30 Grenade', 'Beanbag', 'Sniper Rifle', 'Flamethrower', 'Ignite', 'Full Auto', ],
            'Beam Rifle'       : [ 'Single Shot', 'Charged Shot', 'Cutting Beam', 'Disintegrate', 'Aim', 'Lancer Shot', 'Penetrating Ray', 'Piercing Beam', 'Overcharge', ],
            'Dark Blast'       : [ 'Dark Blast', 'Gloom', 'Moonbeam', 'Dark Pit', 'Tenebrous Tentacles', 'Night Fall', 'Torrent', 'Life Drain', 'Blackstar', ],
            'Dual Pistols'     : [ 'Pistols', 'Dual Wield', 'Empty Clips', {'Swap Ammo' : ['Cryo Ammunition', 'Incendiary Ammunition', 'Chemical Ammunition', ]}, 'Bullet Rain', 'Suppressive Fire', 'Executioner\'s Shot', 'Piercing Rounds', 'Hail of Bullets', ],
            'Electrical Blast' : [ 'Charged Bolts', 'Lightning Bolt', 'Ball Lightning', 'Short Circuit', 'Aim', 'Zapp', 'Tesla Cage', 'Voltaic Sentinel', 'Thunderous Blast', ],
            'Energy Blast'     : [ 'Power Bolt', 'Power Blast', 'Energy Torrent', 'Power Burst', 'Sniper Blast', 'Aim', 'Power Push', 'Explosive Blast', 'Nova', ],
            'Fire Blast'       : [ 'Flares', 'Fire Blast', 'Fire Ball', 'Rain of Fire', 'Fire Breath', 'Aim', 'Blaze', 'Blazing Bolt', 'Inferno', ],
            'Ice Blast'        : [ 'Ice Bolt', 'Ice Blast', 'Frost Breath', 'Aim', 'Freeze Ray', 'Ice Storm', 'Bitter Ice Blast', 'Bitter Freeze Ray', 'Blizzard', ],
            'Psychic Blast'    : [ 'Mental Blast', 'Subdue', 'Psionic Lance', 'Psychic Scream', 'Telekinetic Blast', 'Will Domination', 'Psionic Tornado', 'Scramble Thoughts', 'Psychic Wail', ],
            'Radiation Blast'  : [ 'Neutrino Bolt', 'X-Ray Beam', 'Irradiate', 'Electron Haze', 'Proton Volley', 'Aim', 'Cosmic Burst', 'Neutron Bomb', 'Atomic Blast', ],
            'Sonic Attack'     : [ 'Shriek', 'Scream', 'Howl', 'Shockwave', 'Shout', 'Amplify', 'Siren\'s Song', 'Screech', 'Dreadful Wail', ],
            'Water Blast'      : [ 'Aqua Bolt', 'Hydro Blast', 'Water Burst', 'Whirlpool', 'Tidal Forces', 'Dehydrate', 'Water Jet', 'Steam Spray', 'Geyser', ],
        },
    },
    'Dominator': {
        'Epic': {
            'Fire Mastery'          : [ 'Rain of Fire', 'Fire Ball', 'Fire Shield', 'Rise of the Phoenix', 'Melt Armor', ],
            'Ice Mastery'           : [ 'Hibernate', 'Sleet', 'Hoarfrost', 'Frozen Armor', 'Ice Storm', ],
            'Leviathan Mastery'     : [ 'Water Spout', 'Bile Spray', 'Hibernate', 'Shark Skin', 'Summon Coralax', ],
            'Mace Mastery'          : [ 'Poisonous Ray', 'Scorpion Shield', 'Disruptor Blast', 'Personal Force Field', 'Summon Tarantula', ],
            'Mu Mastery'            : [ 'Power Sink', 'Charged Armor', 'Ball Lightning', 'Surge of Power', 'Summon Guardian', ],
            'Primal Forces Mastery' : [ 'Energy Transfer', 'Conserve Power', 'Energy Torrent', 'Temp Invulnerability', 'Explosive Blast', ],
            'Psionic Mastery'       : [ 'Link Minds', 'Indomitable Will', 'Mind Over Body', 'World of Confusion', 'Psionic Tornado', ],
            'Soul Mastery'          : [ 'Dark Consumption', 'Dark Embrace', 'Dark Obliteration', 'Soul Drain', 'Summon Seer', ]
        },
        'Primary': {
            'Darkness Control' : [ 'Shadowy Binds', 'Dark Grasp', 'Living Shadows', 'Possess', 'Fearsome Stare', 'Heart of Darkness', 'Haunt', 'Shadow Field', 'Umbra Beast', ],
            'Earth Control'    : [ 'Stone Prison', 'Fossilize', 'Stone Cages', 'Quicksand', 'Salt Crystals', 'Stalagmites', 'Earthquake', 'Volcanic Gasses', 'Animate Stone', ],
            'Electric Control' : [ 'Electric Fence', 'Tesla Cage', 'Chain Fences', 'Jolting Chain', 'Conductive Aura', 'Static Field', 'Paralyzing Blast', 'Synaptic Overload', 'Gremlins', ],
            'Fire Control'     : [ 'Ring of Fire', 'Char', 'Fire Cages', 'Smoke', 'Hot Feet', 'Flashfire', 'Cinders', 'Bonfire', 'Fire Imps', ],
            'Gravity Control'  : [ 'Crush', 'Lift', 'Gravity Distortion', 'Propel', 'Crushing Field', 'Dimension Shift', 'Gravity Distortion Field', 'Wormhole', 'Singularity', ],
            'Ice Control'      : [ 'Chilblain', 'Block of Ice', 'Frostbite', 'Arctic Air', 'Shiver', 'Ice Slick', 'Flash Freeze', 'Glacier', 'Jack Frost', ],
            'Illusion Control' : [ 'Blind', 'Spectral Wall', 'Deceive', 'Spectral Terror', 'Superior Invisibility', 'Gleam', 'Phantom Army', 'Flash', 'Phantasm' ],
            'Mind Control'     : [ 'Mesmerize', 'Levitate', 'Dominate', 'Confuse', 'Mass Hypnosis', 'Telekinesis', 'Total Domination', 'Terrify', 'Mass Confusion', ],
            'Plant Control'    : [ 'Entangle', 'Strangler', 'Roots', 'Spore Burst', 'Seeds of Confusion', 'Spirit Tree', 'Vines', 'Carrion Creepers', 'Fly Trap', ],
            'Water Control'    : [ 'Deluge', 'Suffocate', 'Hypothermia', 'Geyser Burst', 'Turbulent Aura', 'Riptide', 'Tidal Wave', 'Drowning Pool', 'Water Golem', ],
            'Wind Control'     : [ 'Updraft', 'Downdraft', 'Breathless', 'Wind Shear', 'Thundergust', 'Microburst', 'Keening Winds', 'Vacuum', 'Vortex', ],
        },
        'Secondary': {
            'Dark Assault'        : [ 'Dark Blast', 'Smite', 'Gloom', 'Night Fall', 'Gather Shadows', 'Engulfing Darkness', 'Life Drain', 'Moon Beam', 'Midnight Grasp', ],
            'Earth Assault'       : [ 'Stone Spears', 'Stone Mallet', 'Tremor', 'Hurl Boulder', 'Power Boost', 'Heavy Mallet', 'Seismic Smash', 'Mud Pots', 'Fissure', ],
            'Electricity Assault' : [ 'Charged Bolts', 'Charged Brawl', 'Lightning Bolt', 'Havoc Punch', 'Build Up', 'Zapp', 'Static Discharge', 'Thunder Strike', 'Voltaic Sentinel', ],
            'Energy Assault'      : [ 'Power Bolt', 'Bone Smasher', 'Power Push', 'Power Blast', 'Power Boost', 'Whirling Hands', 'Total Focus', 'Sniper Blast', 'Power Burst', ],
            'Fiery Assault'       : [ 'Flares', 'Incinerate', 'Fire Breath', 'Fire Blast', 'Embrace of Fire', 'Combustion', 'Consume', 'Blazing Bolt', 'Blaze', ],
            'Icy Assault'         : [ 'Ice Bolt', 'Ice Sword', 'Ice Sword Circle', 'Ice Blast', 'Power Boost', 'Frost Breath', 'Chilling Embrace', 'Ice Slash', 'Bitter Ice Blast', ],
            'Kinetic Assault':      [ 'Kinetic Bolt', 'Forceful Blow', 'Crushing Blast', 'Disrupting Torrent', 'Coalescence', 'Kinetic Shockwave', 'Energetic Strike', 'Kinetic Lance', 'Mass Driver', ],
            'Martial Assault'     : [ 'Shuriken Throw', 'Thunder Kick', 'Trick Shot', 'Spinning Kick', 'Envenomed Blades', 'Dragon\'s Tail', 'Caltrops', 'Masterful Throw', 'Explosive Shuriken', ],
            'Military Assault':     [ 'Single Shot', 'Pummel', 'Burst', 'Heavy Burst', 'Build Up', 'Shin Breaker', 'Spinning Strike', 'Sniper Round', 'Incendiary Round', ],
            'Ninja Assault':        [ 'Flashing Blade', 'Gambler\'s Cut', 'Soaring Dragon', 'Steel Wind', 'Chi Strike', 'Scorpion\'s Sting', 'The Lotus Drops', 'Caltrops', 'Golden Dragonfly', ],
            'Psionic Assault'     : [ 'Psionic Dart', 'Mind Probe', 'Telekinetic Thrust', 'Mental Blast', 'Psychic Scream', 'Drain Psyche', 'Subdue', 'Psionic Lance', 'Psychic Shockwave', ],
            'Thorny Assault'      : [ 'Thorny Darts', 'Skewer', 'Fling Thorns', 'Impale', 'Aim', 'Thorn Burst', 'Thorntrops', 'Ripper', 'Thorn Barrage', ],
        },
    },
    'Guardian': {
        'Epic': {
            'Fire Mastery': [ 'Ring of Fire', 'Fire Ball', 'Rain of Fire', 'Char', 'Greater Fire Sword', ],
            'Ice Mastery': [ 'Chilblain', 'Frozen Aura', 'Freezing Touch', 'Ice Storm', 'Shiver', ],
            'Leviathan Mastery': [ 'Arctic Breath', 'Spirit Shark Jaws', 'Water Spout', 'Bile Spray', 'Summon Coralax', ],
            'Mace Mastery': [ 'Shatter Armor', 'Web Cocoon', 'Disruptor Blast', 'Focused Accuracy', 'Summon Tarantula', ],
            'Mu Mastery': [ 'Ball Lightning', 'Electric Shackles', 'Conserve Power', 'Thunder Strike', 'Summon Guardian', ],
            'Munitions Mastery': [ 'Attack Munitions', 'Taser Jolt', 'Superior Conditioning', 'Targeting Drone', 'Surveillance', ],
            'Primal Forces Mastery': [ 'Energy Transfer', 'Explosive Blast', 'Energy Torrent', 'Focused Accuracy', 'Physical Perfection', ],
            'Psionic Mastery': [ 'Boggle', 'Greater Psi Blade', 'Mass Levitate', 'Psionic Tornado', 'Mass Hypnosis', ],
            'Soul Mastery': [ 'Dark Obliteration', 'Soul Storm', 'Dark Consumption', 'Soul Drain', 'Summon Widow', ],
        },
        'Primary' : {
            'Dark Assault': [ 'Dark Blast', 'Smite', 'Gloom', 'Night Fall', 'Build Up', 'Engulfing Darkness', 'Life Drain', 'Moon Beam', 'Midnight Grasp', ],
            'Earth Assault': [ 'Stone Fist', 'Stone Spears', 'Fissure', 'Stone Mallet', 'Build Up', 'Tremor', 'Heavy Mallet', 'Hurl Boulder', 'Seismic Smash', ],
            'Electricity Assault' : [ 'Charged Bolts', 'Charged Brawl', 'Lightning Bolt', 'Chain Induction', 'Build Up', 'Static Discharge', 'Havoc Punch', 'Zapp',  'Lightning Rod', ],
            'Energy Assault': [ 'Power Bolt', 'Bone Smasher', 'Power Push', 'Power Blast', 'Build Up', 'Whirling Hands', 'Power Burst', 'Sniper Blast', 'Total Focus', ],
            'Fiery Assault': [ 'Flares', 'Cremate', 'Fire Breath', 'Fire Blast', 'Build Up', 'Combustion', 'Incinerate', 'Blazing Bolt', 'Blaze', ],
            'Gun Fu': [ 'Pistols', 'Crane Kick', 'Spinning Kick', 'Dual Wield', 'Focus Chi', 'Empty Clips', 'Crippling Axe Kick', 'Piercing Rounds', 'Eagles Claw', ],
            'Hellfire Assault': [ 'Hellfire Flares', 'Hellfire Smash', 'Crack Whip', 'Corruption', 'Soul Searing', 'Hellfire Burst', 'Lash', 'Hellfire Blaze', 'Wrath of Hell', ],
            'Icy Assault': [ 'Ice Bolt', 'Ice Sword', 'Ice Sword Circle', 'Ice Blast', 'Build Up', 'Frost Breath', 'Ice Slash', 'Bitter Ice Blast', 'Bitter Freeze Ray', ],
            'Kinetic Assault': [ 'Forceful Blow', 'Kinetic Bolt', 'Crushing Blast', 'Disrupting Torrent', 'Coalescence', 'Kinetic Shockwave', 'Energetic Strike', 'Kinetic Lance', 'Mass Driver', ],
            'Luminous Assault': [ 'Gleaming Bolt', 'Luminous Smite', 'Glinting Eye', 'Radiant Strike', 'Inner Light', 'Proton Scatter', 'Gleaming Blast', 'Incandescent Strike', 'Solar Flare', ],
            'Mace Assault': [ 'Bash', 'Mace Beam', 'Mace Beam Blast', 'Pulverize', 'Build Up', 'Poisonous Ray', 'Mace Beam Volley', 'Shatter', 'Crowd Control', ],
            'Martial Assault': [ 'Shuriken Throw', 'Thunder Kick', 'Trick Shot', 'Spinning Kick', 'Envenomed Blades', 'Dragon\'s Tail', 'Caltrops', 'Masterful Throw', 'Explosive Shuriken', ],
            'Military Assault': [ 'Single Shot', 'Pummel', 'Burst', 'Heavy Burst', 'Build Up', 'Shin Breaker', 'Spinning Strike', 'Sniper Round', 'Incendiary Round', ],
            'Ninja Assault': [ 'Flashing Blade', 'Gambler\'s Cut', 'Steel Wind', 'Soaring Dragon', 'Chi Strike', 'Scorpion\'s Sting', 'The Lotus Drops', 'Caltrops', 'Golden Dragonfly', ],
            'Psionic Assault': [ 'Psionic Dart', 'Telekinetic Blow', 'Mental Blast', 'Psychic Scream', 'Concentration', 'Mind Probe', 'Subdue', 'Psionic Lance', 'Psychic Shockwave', ],
            'Radiation Assault': [ 'Neutrino Bolt', 'Radioactive Smash', 'X-Ray Beam', 'Electron Haze', 'Fusion', 'Radiation Siphon', 'Devastating Blow', 'Proton Volley', 'Atom Smasher', ],
            'Thorny Assault'      : [ 'Thorny Darts', 'Skewer', 'Fling Thorns', 'Impale', 'Build Up', 'Thorn Burst', 'Thorntrops', 'Ripper', 'Thorn Barrage', ],
            'Umbral Assault': [ 'Shadow Bolt', 'Umbral Smite', 'Gravimetric Snare', 'Essence Drain', 'Inner Umbra', 'Gravitic Emanation', 'Shadow Blast', 'Gravity Well', 'Dark Extraction', ],
        },
        'Secondary' : {
            'Atmospheric Composition': ['Charged Armor', 'Gale Winds', 'Grounding Shield', 'Static Shield', 'Steamy Mist', 'Mass Energize', 'Snow Storm', 'Power Sink', 'Freezing Rain', ],
            'Dark Composition': [ 'Dark Embrace', 'Twilight Grasp', 'Tar Patch', 'Obsidian Shield', 'Murky Haze', 'Shadow Fall', 'Cloak of Fear', 'Soul Absorption', 'Howling Twilight', ],
            'Energy Composition': [ 'Kinetic Shield', 'Siphon Power', 'Power Shield', 'Entropy Shield', 'Inertial Siphon', 'Mass Energize', 'Kinetic Dampening', 'Transference', 'Fulcrum Flip', ],
            'Fiery Composition' : [ 'Fire Shield', 'Soothing Flames', 'Temperature Protection', 'Plasma Shield', 'Consume', 'Reforge', 'Heat Exhaustion', 'Melt Armor', 'Phoenix Awakening', ],
            'Force Composition': [ 'Temp Invulnerability', 'Force Bolt', 'Force Affinity', 'Dispersion Bubble', 'Force Barrier', 'Containment Shell', 'Repulsion Bomb', 'Force Shielding', 'Suppression Field', ],
            'Ice Composition': [ 'Frost Armor', 'Infrigidate', 'Ice Pack', 'Wet Ice', 'Glacial Armor', 'Arctic Fog', 'Chilling Embrace', 'Sleet', 'Heat Loss', ],
            'Infiltrator Training': [ 'Combat Reflexes', 'Web Grenade', 'Danger Sense', 'Trained Mind', 'Poison Trap', 'Intrusion', 'Seeker Drones', 'Blinding Powder', 'Shredder Mine', ],
            'Organic Composition': [ 'Hardened Carapace', 'Regrowth', 'Environmental Modification', 'Inexhaustible', 'Wild Growth', 'Evolving Armor', 'DNA Siphon', 'Wild Bastion', 'Overgrowth', ],
            'Pain Focusing': [ 'Mind Over Body', 'Nullify Pain', 'Quick Recovery', 'Indomitable Will', 'Suppress Pain', 'Heightened Senses', 'Conduit of Pain', 'Anguishing Cry', 'World of Pain', ],
            'Radiation Composition': [ 'Alpha Barrier', 'Radiant Aura', 'Proton Armor', 'Fallout Shelter', 'Accelerate Metabolism', 'Enervating Field', 'Particle Shielding', 'Ground Zero', 'EM Wave', ],
            'Reconstructive Composition': [ 'Resilience', 'Healing Aura', 'Pain Absorption', 'Dull Pain', 'Integration', 'Recovery Aura', 'Regeneration Aura', 'Revive', 'Fortitude Aura', ],
            'Stone Composition': [ 'Rocky Armor', 'Stone Shelter', 'Quicksand', 'Volcanic Armor', 'Gaia\'s Blessing', 'Crystalline Armor', 'Stone Skin', 'Earthquake', 'Eruption', ],
            'Temporal Composition': [ 'Focused Fighter', 'Time Crawl', 'Agile', 'Practiced Brawler', 'Time\'s Juncture', 'Lucky', 'Farsight', 'Slowed Response', 'Chrono Shift', ],
        },
    },
    'Mastermind': {
        'Epic': {
            'Charge Mastery'    : [ 'Static Discharge', 'Electric Shackles', 'Surge of Power', 'Thunder Strike', 'EM Pulse', ],
            'Chill Mastery'     : [ 'Ice Blast', 'Flash Freeze', 'Hoarfrost', 'Frozen Armor', 'Hibernate', ],
            'Field Mastery'     : [ 'Power Blast', 'Temp Invulnerability', 'Energy Torrent', 'Explosive Blast', 'Force of Nature', ],
            'Heat Mastery'      : [ 'Bonfire', 'Fire Blast', 'Fire Ball', 'Char', 'Rise of the Phoenix', ],
            'Leviathan Mastery' : [ 'School of Sharks', 'Bile Spray', 'Knockout Blow', 'Shark Skin', 'Spirit Shark Jaws', ],
            'Mace Mastery'      : [ 'Web Envelope', 'Scorpion Shield', 'Mace Beam Volley', 'Power Boost', 'Web Cocoon', ],
            'Mu Mastery'        : [ 'Static Discharge', 'Charged Armor', 'Electrifying Fences', 'Thunder Strike', 'Electric Shackles', ],
            'Soul Mastery'      : [ 'Night Fall', 'Dark Embrace', 'Oppressive Gloom', 'Soul Tentacles', 'Soul Storm', ],
        },
        'Primary': {
            'Beast Mastery'   : [ 'Call Swarm', 'Summon Wolves', 'Call Hawk', 'Train Beasts', 'Call Ravens', 'Summon Lions', 'Fortify Pack', 'Summon Dire Wolf', 'Tame Beasts', ],
            'Demon Summoning' : [ 'Corruption', 'Summon Demonlings', 'Lash', 'Enchant Demon', 'Crack Whip', 'Summon Demons', 'Hell on Earth', 'Summon Demon Prince', 'Abyssal Empowerment', ],
            'Mercenaries'     : [ 'Burst', 'Soldiers', 'Slug', 'Equip Mercenary', 'M30 Grenade', 'Spec Ops', 'Serum', 'Commando', 'Tactical Upgrade', ],
            'Necromancy'      : [ 'Dark Blast', 'Zombie Horde', 'Gloom', 'Enchant Undead', 'Life Drain', 'Grave Knight', 'Soul Extraction', 'Lich', 'Dark Empowerment', ],
            'Ninjas'          : [ 'Snap Shot', 'Call Genin', 'Aimed Shot', 'Train Ninjas', 'Fistful of Arrows', 'Call Jounin', 'Smoke Flash', 'Oni', 'Kuji-In Sha', ],
            'Robotics'        : [ 'Pulse Rifle Blast', 'Battle Drones', 'Pulse Rifle Burst', 'Equip Robot', 'Photon Grenade', 'Protector Bots', 'Maintenance Drone', 'Assault Bot', 'Upgrade Robot', ],
            'Thugs'           : [ 'Pistols', 'Call Thugs', 'Dual Wield', 'Equip Thugs', 'Empty Clips', 'Call Enforcer', 'Gang War', 'Call Bruiser', 'Upgrade Equipment', ],
        },
        'Secondary': {
            'Cold Domination'     : [ 'Infrigidate', 'Ice Shield', 'Snow Storm', 'Glacial Shield', 'Frostwork', 'Arctic Fog', 'Benumb', 'Sleet', 'Heat Loss', ],
            'Dark Miasma'         : [ 'Twilight Grasp', 'Tar Patch', 'Darkest Night', 'Howling Twilight', 'Shadow Fall', 'Fearsome Stare', 'Petrifying Gaze', 'Black Hole', 'Dark Servant', ],
            'Force Field'         : [ 'Force Bolt', 'Deflection Shield', 'Insulation Shield', 'Barrier Field', 'Personal Force Field', 'Dispersion Bubble', 'Containment Shell', 'Repulsion Bomb', 'Force Bubble', ],
            'Nature Affinity'     : [ 'Corrosive Enzymes', 'Regrowth', 'Wild Growth', 'Spore Cloud', 'Lifegiving Spores', 'Wild Bastion', 'Rebirth', 'Entangling Aura', 'Overgrowth', ],
            'Pain Domination'     : [ 'Nullify Pain', 'Soothe', 'Share Pain', 'Conduit of Pain', 'Enforced Morale', 'Suppress Pain', 'World of Pain', 'Anguishing Cry', 'Painbringer', ],
            'Poison'              : [ 'Alkaloid', 'Envenom', 'Weaken', 'Neurotoxic Breath', 'Elixir of Life', 'Antidote', 'Paralytic Poison', 'Poison Trap', 'Noxious Gas', ],
            'Sonic Resonance'     : [ 'Sonic Siphon', 'Sonic Barrier', 'Sonic Haven', 'Sonic Cage', 'Disruption Field', 'Sonic Dispersion', 'Sonic Repulsion', 'Clarity', 'Liquefy', ],
            'Storm Summoning'     : [ 'Gale', 'O2 Boost', 'Snow Storm', 'Steamy Mist', 'Freezing Rain', 'Hurricane', 'Thunder Clap', 'Tornado', 'Lightning Storm', ],
            'Thermal Radiation'   : [ 'Warmth', 'Fire Shield', 'Cauterize', 'Plasma Shield', 'Power of the Phoenix', 'Thaw', 'Forge', 'Heat Exhaustion', 'Melt Armor', ],
            'Time Manipulation'   : [ 'Time Crawl', 'Temporal Mending', 'Time\'s Juncture', 'Temporal Selection', 'Distortion Field', 'Time Stop', 'Farsight', 'Slowed Response', 'Chrono Shift', ],
            'Traps'               : [ 'Web Grenade', 'Caltrops', 'Triage Beacon', 'Acid Mortar', 'Force Field Generator', 'Poison Trap', 'Seeker Drones', 'Trip Mine', 'Detonator', ],
            'Trick Arrow'         : [ 'Entangling Arrow', 'Flash Arrow', 'Glue Arrow', 'Ice Arrow', 'Poison Gas Arrow', 'Acid Arrow', 'Disruption Arrow', 'Oil Slick Arrow', 'EMP Arrow', ],
        },
    },
    'Peacebringer': {
        'Epic': {},
        'Dependent': {
            'Bright Nova': [ 'Bright Nova Bolt', 'Bright Nova Blast', 'Bright Nova Scatter', 'Bright Nova Detonation', ],
            'White Dwarf': [ 'White Dwarf Strike', 'White Dwarf Smite', 'White Dwarf Flare', 'White Dwarf Sublimation', 'White Dwarf Antagonize', 'White Dwarf Step', ],
        },
        'Inherent': {
            'Inherent': [ 'Combat Flight', 'Energy Flight', 'Quantum Acceleration',],
        },
        'Primary': {
            'Luminous Blast': [ 'Gleaming Bolt', 'Glinting Eye', 'Gleaming Blast', 'Bright Nova', 'Radiant Strike', 'Proton Scatter', 'Inner Light',
                                'Luminous Detonation', 'Incandescent Strike', 'Pulsar', 'Glowing Touch', 'Solar Flare', 'Dawn Strike', 'Photon Seekers',
                                'Bright Nova Bolt', 'Bright Nova Blast', 'Bright Nova Scatter', 'Bright Nova Detonation', ],
        },
        'Secondary': {
            'Luminous Aura': [ 'Incandescence', 'Shining Shield', 'Essence Boost', 'Thermal Shield', 'Quantum Shield', 'Group Energy Flight', 'White Dwarf',
                               'Reform Essence', 'Conserve Energy', 'Quantum Maneuvers', 'Quantum Flight', 'Restore Essence', 'Light Form',
                               'White Dwarf Strike', 'White Dwarf Smite', 'White Dwarf Flare', 'White Dwarf Sublimation', 'White Dwarf Antagonize', 'White Dwarf Step', ],
        },
    },
    'Scrapper': {
        'Epic': {
            'Blaze Mastery'     : [ 'Ring of Fire', 'Char', 'Fire Blast', 'Melt Armor', 'Fire Ball', ],
            'Body Mastery'      : [ 'Conserve Power', 'Focused Accuracy', 'Laser Beam Eyes', 'Physical Perfection', 'Energy Torrent', ],
            'Darkness Mastery'  : [ 'Torrent', 'Petrifying Gaze', 'Dark Blast', 'Night Fall', 'Tenebrous Tentacles', ],
            'Leviathan Mastery' : [ 'Spirit Shark', 'Water Spout', 'Hibernate', 'Spirit Shark Jaws', 'Summon Guardian', ],
            'Mace Mastery'      : [ 'Mace Blast', 'Mace Beam', 'Disruptor Blast', 'Web Cocoon', 'Summon Spiderlings', ],
            'Martial Prowess'   : [ 'Entangling Arrow', 'Warrior\'s Mark', 'Aimed Shot', 'Shukuchi', 'Gather Chi', ],
            'Mu Mastery'        : [ 'Mu Bolts', 'Zapp', 'Ball Lightning', 'Electric Shackles', 'Summon Adept', ],
            'Soul Mastery'      : [ 'Dark Blast', 'Moonbeam', 'Shadow Meld', 'Soul Storm', 'Summon Widow', ],
            'Weapon Mastery'    : [ 'Web Grenade', 'Caltrops', 'Shuriken', 'Targeting Drone', 'Exploding Shuriken', ],
        },
        'Primary': {
            'Battle Axe'       : [ 'Beheader', 'Chop', 'Gash', 'Build Up', 'Swoop', 'Confront', 'Whirling Axe', 'Cleave', 'Pendulum', ],
            'Broad Sword'      : [ 'Hack', 'Slash', 'Slice', 'Build Up', 'Parry', 'Confront', 'Whirling Sword', 'Disembowel', 'Head Splitter', ],
            'Claws'            : [ 'Swipe', 'Strike', 'Slash', 'Spin', 'Follow Up', 'Confront', 'Focus', 'Eviscerate', 'Shockwave', ],
            'Dark Melee'       : [ 'Shadow Punch', 'Smite', 'Shadow Maul', 'Touch of Fear', 'Siphon Life', 'Confront', 'Dark Consumption', 'Soul Drain', 'Midnight Grasp', ],
            'Dual Blades'      : [ 'Nimble Slash', 'Power Slice', 'Ablating Strike', 'Typhoon\'s Edge', 'Blinding Feint', 'Confront', 'Vengeful Slice', 'Sweeping Strike', 'One Thousand Cuts', ],
            'Electrical Melee' : [ 'Charged Brawl', 'Havoc Punch', 'Jacobs Ladder', 'Build Up', 'Thunder Strike', 'Confront', 'Chain Induction', 'Lightning Clap', 'Lightning Rod', ],
            'Fiery Melee'      : [ 'Scorch', 'Fire Sword', 'Cremate', 'Build Up', 'Breath of Fire', 'Confront', 'Fire Sword Circle', 'Incinerate', 'Greater Fire Sword', ],
            'Ice Melee'        : [ 'Frozen Fists', 'Ice Sword', 'Frost', 'Build Up', 'Greater Ice Sword', 'Confront', 'Ice Patch', 'Freezing Touch', 'Frozen Aura', ],
            'Katana'           : [ 'Sting of the Wasp', 'Gambler\'s Cut', 'Flashing Steel', 'Build Up', 'Divine Avalanche', 'Calling the Wolf', 'The Lotus Drops', 'Soaring Dragon', 'Golden Dragonfly', ],
            'Kinetic Melee'    : [ 'Quick Strike', 'Body Blow', 'Smashing Blow', 'Power Siphon', 'Repulsing Torrent', 'Confront', 'Burst', 'Focused Burst', 'Concentrated Strike', ],
            'Martial Arts'     : [ 'Thunder Kick', 'Storm Kick', 'Cobra Strike', 'Focus Chi', 'Crane Kick', 'Warrior\'s Challenge', 'Crippling Axe Kick', 'Dragon\'s Tail', 'Eagle\'s Claw', ],
            'Psionic Melee'    : [ 'Mental Strike', 'Psi Blade', 'Telekinetic Blow', 'Concentration', 'Psi Blade Sweep', 'Confront', 'Boggle', 'Greater Psi Blade', 'Mass Levitate', ],
            'Radiation Melee'  : [ 'Contaminated Strike', 'Radioactive Smash', 'Proton Sweep', 'Fusion', 'Radiation Siphon', 'Confront', 'Irradiated Ground', 'Devastating Blow', 'Atom Smasher', ],
            'Savage Melee'     : [ 'Maiming Slash', 'Savage Strike', 'Shred', 'Vicious Slash', 'Rending Flurry', 'Confront', 'Blood Thirst', 'Hemorrhage', 'Savage Leap', ],
            'Spines'           : [ 'Barb Swipe', 'Lunge', 'Spine Burst', 'Build Up', 'Impale', 'Confront', 'Quills', 'Ripper', 'Throw Spines', ],
            'Staff Fighting'   : [ 'Mercurial Blow', 'Precise Strike', 'Guarded Spin', 'Eye of the Storm', { 'Staff Mastery': [ 'Form of the Body', 'Form of the Mind', 'Form of the Soul', ]}, 'Confront', 'Serpent\'s Reach', 'Innocuous Strikes', 'Sky Splitter', ],
            'Street Justice'   : [ 'Initial Strike', 'Heavy Blow', 'Sweeping Cross', 'Combat Readiness', 'Rib Cracker', 'Confront', 'Spinning Strike', 'Shin Breaker', 'Crushing Uppercut', ],
            'Titan Weapons'    : [ 'Defensive Sweep', 'Crushing Blow', 'Titan Sweep', 'Follow Through', 'Build Momentum', 'Confront', 'Rend Armor', 'Whirling Smash', 'Arc of Destruction', ],
            'War Mace'         : [ 'Bash', 'Pulverize', 'Jawbreaker', 'Build Up', 'Clobber', 'Confront', 'Whirling Mace', 'Shatter', 'Crowd Control', ],
        },
        'Secondary': {
            'Bio Armor'       : [ 'Hardened Carapace', 'Inexhaustible', 'Environmental Modification', {'Adaptation' : ['Efficient Adaptation', 'Defensive Adaptation', 'Offensive Adaptation', ]}, 'Ablative Carapace', 'Evolving Armor', 'DNA Siphon', 'Genetic Contamination', 'Parasitic Aura', ],
            'Dark Armor'      : [ 'Dark Embrace', 'Death Shroud', 'Murky Cloud', 'Obsidian Shield', 'Dark Regeneration', 'Cloak of Darkness', 'Cloak of Fear', 'Oppressive Gloom', 'Soul Transfer', ],
            'Electric Armor'  : [ 'Charged Armor', 'Lightning Field', 'Conductive Shield', 'Static Shield', 'Grounded', 'Energize', 'Lightning Reflexes', 'Power Sink', 'Power Surge', ],
            'Energy Aura'     : [ 'Kinetic Shield', 'Dampening Field', 'Power Shield', 'Entropic Aura', 'Energy Protection', 'Energy Cloak', 'Energize', 'Energy Drain', 'Overload', ],
            'Fiery Aura'      : [ 'Fire Shield', 'Blazing Aura', 'Healing Flames', 'Temperature Protection', 'Plasma Shield', 'Consume', 'Burn', 'Fiery Embrace', 'Rise of the Phoenix', ],
            'Ice Armor'       : [ 'Frozen Armor', 'Hoarfrost', 'Chilling Embrace', 'Wet Ice', 'Glacial Armor', 'Permafrost', 'Icicles', 'Energy Absorption', 'Icy Bastion', ],
            'Invulnerability' : [ 'Resist Physical Damage', 'Temp Invulnerability', 'Dull Pain', 'Resist Elements', 'Unyielding', 'Resist Energies', 'Invincibility', 'Tough Hide', 'Unstoppable', ],
            'Ninjitsu'        : [ 'Hide', 'Ninja Reflexes', 'Danger Sense', 'Caltrops', 'Kuji-In Rin', 'Kuji-In Sha', 'Smoke Flash', 'Blinding Powder', 'Kuji-In Retsu', ],
            'Radiation Armor' : [ 'Alpha Barrier', 'Gamma Boost', 'Proton Armor', 'Fallout Shelter', 'Radiation Therapy', 'Beta Decay', 'Particle Shielding', 'Ground Zero', 'Meltdown', ],
            'Regeneration'    : [ 'Fast Healing', 'Reconstruction', 'Quick Recovery', 'Dull Pain', 'Integration', 'Resilience', 'Instant Healing', 'Revive', 'Moment of Glory', ],
            'Shield Defense'  : [ 'Deflection', 'Battle Agility', 'True Grit', 'Active Defense', 'Against All Odds', 'Phalanx Fighting', 'Grant Cover', 'Shield Charge', 'One with the Shield', ],
            'Stone Armor'     : [ 'Rock Armor', 'Stone Skin', 'Earth\'s Embrace', 'Mud Pots', 'Rooted', 'Crystal Armor', 'Minerals', 'Brimstone Armor', 'Geode', ],
            'Super Reflexes'  : [ 'Focused Fighting', 'Focused Senses', 'Agile', 'Practiced Brawler', 'Dodge', 'Quickness', 'Lucky', 'Evasion', 'Elude', ],
            'Willpower'       : [ 'High Pain Tolerance', 'Mind Over Body', 'Fast Healing', 'Indomitable Will', 'Rise to the Challenge', 'Quick Recovery', 'Heightened Senses', 'Resurgence', 'Strength of Will', ],
        },
    },
    'Stalker': {
        'Epic': {
            'Blaze Mastery'     : [ 'Ring of Fire', 'Char', 'Fire Blast', 'Melt Armor', 'Fire Ball', ],
            'Body Mastery'      : [ 'Superior Conditioning', 'Focused Accuracy', 'Laser Beam Eyes', 'Physical Perfection', 'Energy Torrent', ],
            'Darkness Mastery'  : [ 'Torrent', 'Petrifying Gaze', 'Dark Blast', 'Night Fall', 'Tenebrous Tentacles', ],
            'Leviathan Mastery' : [ 'Spirit Shark', 'Water Spout', 'Hibernate', 'Spirit Shark Jaws', 'Summon Guardian', ],
            'Mace Mastery'      : [ 'Mace Blast', 'Mace Beam', 'Disruptor Blast', 'Web Cocoon', 'Summon Spiderlings', ],
            'Martial Prowess'   : [ 'Entangling Arrow', 'Warrior\'s Mark', 'Assassin\'s Arrow', 'War Cry', 'Gather Chi', ],
            'Mu Mastery'        : [ 'Mu Bolts', 'Zapp', 'Ball Lightning', 'Electric Shackles', 'Summon Adept', ],
            'Psionic Mastery'   : [ 'Mental Blast', 'Psionic Lance', 'Psychic Scream', 'Harmonic Mind', 'Psionic Nexus', ],
            'Soul Mastery'      : [ 'Dark Blast', 'Moonbeam', 'Shadow Meld', 'Soul Storm', 'Summon Widow', ],
            'Weapon Mastery'    : [ 'Web Grenade', 'Physical Perfection', 'Shuriken', 'Targeting Drone', 'Exploding Shuriken', ],
        },
        'Primary'              : {
            'Broad Sword'      : [ 'Hack', 'Slash', 'Slice', 'Assassin\'s Slash', 'Build Up', 'Placate', 'Parry', 'Disembowel', 'Head Splitter', ],
            'Claws'            : [ 'Swipe', 'Strike', 'Slash', 'Assassin\'s Claw', 'Build Up', 'Placate', 'Focus', 'Eviscerate', 'Shockwave', ],
            'Dark Melee'       : [ 'Shadow Punch', 'Smite', 'Shadow Maul', 'Assassin\'s Eclipse', 'Build Up', 'Placate', 'Siphon Life', 'Touch of Fear', 'Midnight Grasp', ],
            'Dual Blades'      : [ 'Nimble Slash', 'Power Slice', 'Ablating Strike', 'Assassin\'s Blades', 'Build Up', 'Placate', 'Vengeful Slice', 'Sweeping Strike', 'One Thousand Cuts', ],
            'Electrical Melee' : [ 'Charged Brawl', 'Havoc Punch', 'Jacobs Ladder', 'Assassin\'s Shock', 'Build Up', 'Placate', 'Chain Induction', 'Thunder Strike', 'Lightning Rod', ],
            'Energy Melee'     : [ 'Barrage', 'Energy Punch', 'Bone Smasher', 'Assassin\'s Strike', 'Build Up', 'Placate', 'Staggering Burst', 'Energy Transfer', 'Total Focus', ],
            'Ice Melee'        : [ 'Frozen Fists', 'Ice Sword', 'Frost', 'Assassin\'s Icicle', 'Build Up', 'Placate', 'Greater Ice Sword', 'Freezing Touch', 'Frozen Aura', ],
            'Kinetic Melee'    : [ 'Quick Strike', 'Body Blow', 'Smashing Blow', 'Assassin\'s Strike', 'Build Up', 'Placate', 'Burst', 'Focused Burst', 'Concentrated Strike', ],
            'Martial Arts'     : [ 'Thunder Kick', 'Storm Kick', 'Crippling Axe Kick', 'Assassin\'s Blow', 'Focus Chi', 'Placate', 'Cobra Strike', 'Crane Kick', 'Eagle\'s Claw', ],
            'Ninja Blade'      : [ 'Sting of the Wasp', 'Gambler\'s Cut', 'Flashing Steel', 'Assassin\'s Blade', 'Build Up', 'Placate', 'Divine Avalanche', 'Soaring Dragon', 'Golden Dragonfly', ],
            'Psionic Melee'    : [ 'Mental Strike', 'Psi Blade', 'Telekinetic Blow', 'Assassin\'s Psi Blade', 'Concentration', 'Placate', 'Boggle', 'Greater Psi Blade', 'Mass Levitate', ],
            'Radiation Melee'  : [ 'Contaminated Strike', 'Radioactive Smash', 'Proton Sweep', 'Assassin\'s Corruption', 'Build Up', 'Placate', 'Radiation Siphon', 'Devastating Blow', 'Atom Smasher', ],
            'Savage Melee'     : [ 'Savage Strike', 'Maiming Slash', 'Shred', 'Assassin\'s Frenzy', 'Build Up', 'Placate', 'Blood Thirst', 'Hemorrhage', 'Savage Leap', ],
            'Spines'           : [ 'Barb Swipe', 'Lunge', 'Spine Burst', 'Assassin\'s Impaler', 'Build Up', 'Placate', 'Impale', 'Ripper', 'Throw Spines', ],
            'Staff Fighting'   : [ 'Mercurial Blow', 'Precise Strike', 'Guarded Spin', 'Assassin\'s Staff', 'Build Up', 'Placate', 'Eye of the Storm', 'Serpent\'s Reach', 'Sky Splitter', ],
            'Street Justice'   : [ 'Initial Strike', 'Heavy Blow', 'Sweeping Cross', 'Assassin\'s Strike', 'Build Up', 'Placate', 'Spinning Strike', 'Shin Breaker', 'Crushing Uppercut', ],
        },
        'Secondary': {
            'Bio Armor'       : [ 'Hide', 'Hardened Carapace', 'Boundless Energy', 'Environmental Modification', {'Adaptation' : ['Efficient Adaptation', 'Defensive Adaptation', 'Offensive Adaptation', ]}, 'Ablative Carapace', 'DNA Siphon', 'Genetic Corruption', 'Parasitic Aura', ],
            'Dark Armor'      : [ 'Hide', 'Dark Embrace', 'Murky Cloud', 'Shadow Dweller', 'Obsidian Shield', 'Dark Regeneration', 'Cloak of Fear', 'Oppressive Gloom', 'Soul Transfer', ],
            'Electric Armor'  : [ 'Hide', 'Charged Armor', 'Conductive Shield', 'Static Shield', 'Grounded', 'Lightning Reflexes', 'Energize', 'Power Sink', 'Power Surge ', ],
            'Energy Aura'     : [ 'Hide', 'Kinetic Shield', 'Power Shield', 'Entropy Shield', 'Kinetic Dampening', 'Disrupt', 'Energy Drain', 'Energize', 'Overload', ],
            'Ice Armor'       : [ 'Hide', 'Frozen Armor', 'Hoarfrost', 'Wet Ice', 'Chilling Embrace', 'Permafrost', 'Glacial Armor', 'Energy Absorption', 'Icy Bastion', ],
            'Ninjitsu'        : [ 'Hide', 'Ninja Reflexes', 'Danger Sense', 'Caltrops', 'Kuji-In Rin', 'Kuji-In Sha', 'Smoke Flash', 'Blinding Powder', 'Kuji-In Retsu', ],
            'Radiation Armor' : [ 'Hide', 'Alpha Barrier', 'Gamma Boost', 'Proton Armor', 'Fallout Shelter', 'Radiation Therapy', 'Particle Shielding', 'Ground Zero', 'Meltdown', ],
            'Regeneration'    : [ 'Hide', 'Fast Healing', 'Reconstruction', 'Dull Pain', 'Integration', 'Resilience', 'Instant Healing', 'Revive', 'Moment of Glory', ],
            'Super Reflexes'  : [ 'Hide', 'Focused Fighting', 'Focused Senses', 'Agile', 'Practiced Brawler', 'Dodge', 'Quickness', 'Evasion', 'Elude', ],
            'Willpower'       : [ 'Hide', 'High Pain Tolerance', 'Reconstruction', 'Mind Over Body', 'Indomitable Will', 'Heightened Senses', 'Fast Healing', 'Resurgence', 'Strength of Will', ],
        },
    },
    'Tanker': {
        'Epic': {
            'Arctic Mastery'    : [ 'Chillblain', 'Block of Ice', 'Ice Blast', 'Shiver', 'Ice Storm', ],
            'Earth Mastery'     : [ 'Stone Prison', 'Salt Crystals', 'Fossilize', 'Quicksand', 'Stalagmites', ],
            'Energy Mastery'    : [ 'Conserve Power', 'Focused Accuracy', 'Laser Beam Eyes', 'Physical Perfection', 'Energy Torrent', ],
            'Leviathan Mastery' : [ 'Spirit Shark', 'School of Sharks', 'Arctic Breath', 'Bile Spray', 'Summon Guardian', ],
            'Mace Mastery'      : [ 'Mace Blast', 'Web Envelope', 'Disruptor Blast', 'Focused Accuracy', 'Summon Blaster', ],
            'Martial Prowess'   : [ 'Battle Hardened', 'Throwing Dagger', 'Bodkin Bolt', 'Art of War', 'Valiance', ],
            'Mu Mastery'        : [ 'Mu Lightning', 'Electrifying Fences', 'Ball Lightning', 'Static Discharge', 'Summon Striker', ],
            'Pyre Mastery'      : [ 'Ring of Fire', 'Char', 'Fire Blast', 'Melt Armor', 'Fire Ball', ],
            'Soul Mastery'      : [ 'Gloom', 'Soul Tentacles', 'Darkest Night', 'Dark Obliteration', 'Summon Widow', ],
        },
        'Primary': {
            'Bio Armor'       : [ 'Hardened Carapace', 'Inexhaustible', 'Environmental Modification', {'Adaptation' : ['Efficient Adaptation', 'Defensive Adaptation', 'Offensive Adaptation', ]}, 'Ablative Carapace', 'Evolving Armor', 'DNA Siphon', 'Genetic Contamination', 'Parasitic Aura', ],
            'Dark Armor'      : [ 'Death Shroud', 'Dark Embrace', 'Murky Cloud', 'Obsidian Shield', 'Dark Regeneration', 'Cloak of Darkness', 'Cloak of Fear', 'Oppressive Gloom', 'Soul Transfer', ],
            'Electric Armor'  : [ 'Charged Armor', 'Lightning Field', 'Conductive Shield', 'Static Shield', 'Grounded', 'Energize', 'Lightning Reflexes', 'Power Sink', 'Power Surge', ],
            'Fiery Aura'      : [ 'Blazing Aura', 'Fire Shield', 'Healing Flames', 'Temperature Protection', 'Consume', 'Plasma Shield', 'Burn', 'Fiery Embrace', 'Rise of the Phoenix', ],
            'Ice Armor'       : [ 'Frozen Armor', 'Hoarfrost', 'Chilling Embrace', 'Wet Ice', 'Permafrost', 'Icicles', 'Glacial Armor', 'Energy Absorption', 'Hibernate', ],
            'Invulnerability' : [ 'Resist Physical Damage', 'Temp Invulnerability', 'Dull Pain', 'Resist Elements', 'Unyielding', 'Resist Energies', 'Invincibility', 'Tough Hide', 'Unstoppable', ],
            'Radiation Armor' : [ 'Alpha Barrier', 'Gamma Boost', 'Proton Armor', 'Fallout Shelter', 'Radiation Therapy', 'Beta Decay', 'Particle Shielding', 'Ground Zero', 'Meltdown', ],
            'Shield Defense'  : [ 'Deflection', 'Battle Agility', 'True Grit', 'Active Defense', 'Against All Odds', 'Phalanx Fighting', 'Grant Cover', 'Shield Charge', 'One with the Shield', ],
            'Stone Armor'     : [ 'Rock Armor', 'Stone Skin', 'Earth\'s Embrace', 'Mud Pots', 'Rooted', 'Brimstone Armor', 'Crystal Armor', 'Minerals', 'Granite Armor', ],
            'Super Reflexes'  : [ 'Focused Fighting', 'Focused Senses', 'Agile', 'Practiced Brawler', 'Dodge', 'Evasion', 'Lucky', 'Quickness', 'Elude', ],
            'Willpower'       : [ 'High Pain Tolerance', 'Mind Over Body', 'Fast Healing', 'Indomitable Will', 'Rise to the Challenge', 'Quick Recovery', 'Heightened Senses', 'Resurgence', 'Strength of Will', ],
        },
        'Secondary': {
            'Battle Axe'       : [ 'Beheader', 'Chop', 'Gash', 'Taunt', 'Build Up', 'Whirling Axe', 'Swoop', 'Cleave', 'Pendulum',  ],
            'Broad Sword'      : [ 'Hack', 'Slash', 'Slice', 'Taunt', 'Build Up', 'Parry', 'Whirling Sword', 'Disembowel', 'Head Splitter', ],
            'Claws'            : [ 'Swipe', 'Strike', 'Slash', 'Taunt', 'Spin', 'Follow Up', 'Focus', 'Eviscerate', 'Shockwave', ],
            'Dark Melee'       : [ 'Shadow Punch', 'Smite', 'Shadow Maul', 'Taunt', 'Siphon Life', 'Touch of Fear', 'Soul Drain', 'Dark Consumption', 'Midnight Grasp', ],
            'Dual Blades'      : [ 'Nimble Slash', 'Power Slice', 'Ablating Strike', 'Taunt', 'Typhoon\'s Edge', 'Blinding Feint', 'Vengeful Slice', 'Sweeping Strike', 'One Thousand Cuts', ],
            'Electrical Melee' : [ 'Charged Brawl', 'Havoc Punch', 'Jacobs Ladder', 'Taunt', 'Thunder Strike', 'Build Up', 'Chain Induction', 'Lightning Clap', 'Lightning Rod', ],
            'Energy Melee'     : [ 'Barrage', 'Energy Punch', 'Bone Smasher', 'Taunt', 'Whirling Hands', 'Staggering Burst', 'Build Up', 'Energy Transfer', 'Total Focus', ],
            'Fiery Melee'      : [ 'Scorch', 'Fire Sword', 'Combustion', 'Taunt', 'Breath of Fire', 'Build Up', 'Fire Sword Circle', 'Incinerate', 'Greater Fire Sword', ],
            'Ice Melee'        : [ 'Frozen Fists', 'Ice Sword', 'Frost', 'Taunt', 'Build Up', 'Ice Patch', 'Freezing Touch', 'Greater Ice Sword', 'Frozen Aura', ],
            'Katana'           : [ 'Sting of the Wasp', 'Gambler\'s Cut', 'Flashing Steel', 'Dragon\'s Roar', 'Build Up', 'Divine Avalanche', 'The Lotus Drops', 'Soaring Dragon', 'Golden Dragonfly', ],
            'Kinetic Melee'    : [ 'Quick Strike', 'Body Blow', 'Smashing Blow', 'Taunt', 'Repulsing Torrent', 'Power Siphon', 'Burst', 'Focused Burst', 'Concentrated Strike', ],
            'Martial Arts'     : [ 'Thunder Kick', 'Storm Kick', 'Cobra Strike', 'Warrior\'s Provocation', 'Crane Kick', 'Focus Chi', 'Crippling Axe Kick', 'Dragon\'s Tail', 'Eagle\'s Claw', ],
            'Psionic Melee'    : [ 'Mental Strike', 'Psi Blade', 'Telekinetic Blow', 'Taunt', 'Psi Blade Sweep', 'Concentration', 'Boggle', 'Greater Psi Blade', 'Mass Levitate', ],
            'Radiation Melee'  : [ 'Contaminated Strike', 'Radioactive Smash', 'Proton Sweep', 'Taunt', 'Radiation Siphon', 'Fusion', 'Irradiated Ground', 'Devastating Blow', 'Atom Smasher', ],
            'Savage Melee'     : [ 'Savage Strike', 'Maiming Slash', 'Shred', 'Taunt', 'Vicious Slash', 'Rending Flurry', 'Blood Thirst', 'Hemorrhage', 'Savage Leap', ],
            'Spines'           : [ 'Barb Swipe', 'Lunge', 'Spine Burst', 'Taunt', 'Ripper', 'Build Up', 'Impale', 'Quills', 'Throw Spines', ],
            'Staff Fighting'   : [ 'Mercurial Blow', 'Precise Strike', 'Guarded Spin', 'Taunt', 'Eye of the Storm', { 'Staff Mastery': [ 'Form of the Body', 'Form of the Mind', 'Form of the Soul', ]}, 'Serpent\'s Reach', 'Innocuous Strikes', 'Sky Splitter',  ],
            'Stone Melee'      : [ 'Stone Fist', 'Stone Mallet', 'Heavy Mallet', 'Taunt', 'Build Up', 'Fault', 'Tremor', 'Hurl Boulder', 'Seismic Smash', ],
            'Street Justice'   : [ 'Initial Strike', 'Heavy Blow', 'Sweeping Cross', 'Taunt', 'Combat Readiness', 'Rib Cracker', 'Spinning Strike', 'Shin Breaker', 'Crushing Uppercut', ],
            'Super Strength'   : [ 'Jab', 'Punch', 'Haymaker', 'Taunt', 'Hand Clap', 'Knockout Blow', 'Rage', 'Hurl', 'Foot Stomp', ],
            'Titan Weapons'    : [ 'Defensive Sweep', 'Crushing Blow', 'Titan Sweep', 'Taunt', 'Follow Through', 'Build Momentum', 'Rend Armor', 'Whirling Smash', 'Arc of Destruction', ],
            'War Mace'         : [ 'Bash', 'Pulverize', 'Jawbreaker', 'Taunt', 'Build Up', 'Whirling Mace', 'Clobber', 'Shatter', 'Crowd Control', ],
        },
    },
    'Warshade': {
        'Epic': {},
        'Dependent': {
            'Black Dwarf': [ 'Black Dwarf Strike', 'Black Dwarf Smite', 'Black Dwarf Mire', 'Black Dwarf Drain', 'Black Dwarf Step', 'Black Dwarf Antagonize', ],
            'Dark Nova': [ 'Dark Nova Blast', 'Dark Nova Bolt', 'Dark Nova Detonation', 'Dark Nova Emanation', ],
        },
        'Inherent': {
            'Inherent': [ 'Shadow Recall', 'Shadow Step', ],
        },
        'Primary': {
            'Umbral Blast': [ 'Shadow Bolt', 'Ebon Eye', 'Gravimetric Snare', 'Dark Nova', 'Shadow Blast', 'Sunless Mire','Dark Detonation',
                              'Gravity Well', 'Essence Drain', 'Gravitic Emanation', 'Unchain Essence', 'Dark Extraction', 'Quasar',
                              'Dark Nova Blast', 'Dark Nova Bolt', 'Dark Nova Detonation', 'Dark Nova Emanation', ],
        },
        'Secondary': {
            'Umbral Aura': [ 'Absorption', 'Gravity Shield', 'Orbiting Death', 'Penumbral Shield', 'Shadow Cloak', 'Twilight Shield',
                             'Black Dwarf', 'Stygian Circle', 'Nebulous Form', 'Inky Aspect', 'Stygian Return', 'Eclipse',
                             'Black Dwarf Strike', 'Black Dwarf Smite', 'Black Dwarf Mire', 'Black Dwarf Drain', 'Black Dwarf Step', 'Black Dwarf Antagonize', ],
        },
    },
};

MiscPowers: Dict[str, dict] = {
    'Badge': {
        'Accolade': [
            'Core Attunement',
            'Eye of the Magus',
            'Crey CBX-9 Pistol',
            'Demonic Aura',
            'Elusive Mind',
            'Force of Nature',
            'Geas of the Kind Ones',
            'Mark',
            'Portable Workbench',
            'Recall',
            'Sheer Willpower',
            'Stolen Immobilizer Ray',
            'Megalomaniac',
            'Vanguard Medal',
        ],
    },
    'General': {
        'Inherent': [
            'Brawl',
            'Rest',
            'Sprint',
            'Walk',
            'Prestige Power Slide',
        ],
        'SMART': [
            'Prestige Power Rush',
            'Prestige Power Dash',
            'Prestige Power Surge ',
            'Prestige Power Quick',
            'Shadowy Presence',
            'Jump Pack',
            'Pocket D VIP Pass',
            'Mission Transporter',
            'Athletic Run',
            'Beast Run',
            'Inner Inspiration',
            'Mystic Fortune',
            'Ninja Run',
            'Secondary Mutation',
            'Self Destruction',
            'Steam Jump',
            'Apprentice Charm',
            'Mutagen',
            'Taser Dart',
            'Throwing Knives',
            'Tranq Dart',
        ],
    },
    'Pool'                : {
        'Concealment'     : [ 'Stealth', 'Grant Invisibility', 'Infiltration', 'Misdirection', 'Phase Shift', ],
        'Experimentation' : [ 'Experimental Injection', 'Toxic Dart', 'Speed of Sound', 'Corrosive Vial', 'Adrenal Booster', 'Jaunt', ],
        'Fighting'        : [ 'Boxing', 'Kick', 'Tough', 'Weave', 'Cross Punch', ],
        'Flight'          : [ 'Hover', 'Air Superiority', 'Fly', 'Group Fly', 'Evasive Maneuvers', 'Afterburner' ],
        'Force of Will'   : [ 'Weaken Resolve', 'Mighty Leap', 'Project Will', 'Wall of Force', 'Unleash Potential', 'Takeoff', ],
        'Leadership'      : [ 'Maneuvers', 'Assault', 'Tactics', 'Vengeance', 'Victory Rush', ],
        'Leaping'         : [ 'Jump Kick', 'Super Jump', 'Combat Jumping', 'Acrobatics', 'Spring Attack', 'Double Jump', ],
        'Medicine'        : [ 'Aid Other', 'Injection', 'Aid Self', 'Field Medic', 'Resuscitate', ],
        'Presence'        : [ 'Pacify', 'Provoke', 'Intimidate', 'Invoke Panic', 'Unrelenting', ],
        'Sorcery'         : [ 'Spirit Ward', 'Arcane Bolt', 'Mystic Flight', 'Enflame', 'Rune of Protection', 'Translocation',],
        'Speed'           : [ 'Flurry', 'Hasten', 'Super Speed', 'Burnout', 'Whirlwind', 'Speed Phase', ],
        'Teleportation'   : [ 'Teleport Target', 'Teleport', 'Combat Teleport', 'Fold Space', 'Team Teleport', ],
    },
    'Incarnate': {
        'Alpha': {
            'Types': [ 'Agility', 'Cardiac', 'Intuition', 'Musculature', 'Nerve' ,'Resilient', 'Spiritual', 'Vigor' ],
            'Powers': [ 'Boost', 'Core Boost', 'Radial Boost', 'Total Core Revamp', 'Partial Core Revamp',
                       'Partial Radial Revamp', 'Total Radial Revamp', 'Core Paragon', 'Radial Paragon', ],
        },
        'Judgement': {
            'Types': [ 'Cryonic', 'Ion', 'Mighty', 'Pyronic', 'Void', 'Vorpal', ],
            'Powers': [ 'Judgement', 'Core Judgement', 'Radial Judgement', 'Total Core Judgement', 'Partial Core Judgement',
                       'Partial Radial Judgement', 'Total Radial Judgement', 'Core Final Judgement', 'Radial Final Judgement' ],
        },
        'Interface': {
            'Types': [ 'Cognitive', 'Degenerative', 'Diamagnetic', 'Gravitic', 'Paralytic', 'Preemptive', 'Reactive', 'Spectral', ],
            'Powers': [ 'Interface', 'Core Interface', 'Radial Interface', 'Total Core Conversion', 'Partial Core Conversion',
                       'Partial Radial Conversion', 'Total Radial Conversion', 'Core Flawless Interface', 'Radial Flawless Interface', ],
        },
        'Lore': {
            'Types': [ 'Arachnos', 'Banished Pantheon', 'Carnival of Shadows', 'Cimerorans', 'Clockwork', 'Demons', 'IDF',
                      'Knives of Vengeance', 'Longbow', 'Nemesis', 'Phantom', 'Polar Lights', 'Rikti', 'Robotic Drones',
                      'Rularuu', 'Seers', 'Storm Elementals', 'Talons of Vengeance', 'Tsoo', 'Vanguard', 'Warworks', ],
            'Powers': [ 'Ally', 'Core Ally', 'Radial Ally', 'Total Core Improved Ally', 'Partial Core Improved Ally',
                       'Partial Radial Improved Ally', 'Total Radial Improved Ally', 'Core Superior Ally', 'Radial Superior Ally', ],
        },
        'Destiny': {
            'Types': [ 'Ageless', 'Barrier', 'Clarion', 'Incandescence', 'Rebirth', ],
            'Powers': [ 'Invocation', 'Core Invocation', 'Radial Invocation', 'Total Core Invocation', 'Partial Core Invocation',
                       'Partial Radial Invocation', 'Total Radial Invocation', 'Core Epiphany', 'Radial Epiphany', ],
        },
        'Hybrid': {
            'Types': [ 'Assault', 'Control', 'Melee', 'Support', ],
            'Powers': [ 'Genome', 'Core Genome', 'Radial Genome', 'Total Core Graft', 'Partial Core Graft',
                       'Partial Radial Graft', 'Total Radial Graft', 'Core Embodiment', 'Radial Embodiment', ],
        },
        'Genesis': {
            'Types': [ 'Data', 'Fate', 'Socket', 'Verdict', ],
            'Powers' : [ 'Genesis', 'Core Genesis', 'Radial Genesis', 'Total Core Genesis', 'Partial Core Genesis',
                        'Total Radial Genesis', 'Partial Radial Genesis', 'Core Flawless Genesis', 'Radial Flawless Genesis', ],
        },
    }
}

SprintPowers = [
    'Sprint',
    'Prestige Power Slide',
    'Prestige Power Dash',
    'Prestige Power Quick',
    'Prestige Power Rush',
    'Prestige Power Slide',
    'Athletic Run',
    'Beast Run',
    'Ninja Run',
    'Infiltration',
]

Inspirations = {
    'Single' : {
        'Accuracy'     : {
            'ltcolor': (255, 238, 0),
            'dkcolor': (118, 80, 0),
            'tiers': ['Insight', 'Keen Insight', 'Uncanny Insight', 'Sight Beyond Sight',],
        },
        'Health'       : {
            'ltcolor': (135, 220, 38),
            'dkcolor': (0, 66, 7),
            'tiers': ['Respite', 'Dramatic Improvement', 'Resurgence', 'Perfect Health',],
        },
        'Damage'       : {
            'ltcolor': (249, 163, 152),
            'dkcolor': (179, 0, 0),
            'tiers': ['Enrage', 'Focused Rage', 'Righteous Rage', 'Furious Rage',],
        },
        'Endurance'    : {
            'ltcolor': (122, 220, 255),
            'dkcolor': (0, 30, 160),
            'tiers': ['Catch a Breath', 'Take a Breather', 'Second Wind', 'Back in the Fight',],
        },
        'Defense'      : {
            'ltcolor': (228, 166, 236),
            'dkcolor': (94, 0, 94),
            'tiers': ['Luck', 'Good Luck', 'Phenomenal Luck', 'Amazing Luck',],
        },
        'ResistDamage' : {
            'ltcolor': (255, 178, 99),
            'dkcolor': (151, 54, 0),
            'tiers': ['Sturdy', 'Rugged', 'Robust', 'Resistant',],
        },
        'BreakFree'    : {
            'ltcolor': (186, 174, 255),
            'dkcolor': (57, 0, 113),
            'tiers': ['Break Free', 'Emerge', 'Escape', 'Liberate',],
        },
        'Resurrection' : {
            'ltcolor': (50, 180, 160), # cyan
            'dkcolor': (0, 30, 10),
            'tiers': ['Awaken', 'Bounce Back', 'Restoration', 'Immortal Recovery',],
        },
    },
    'Dual' : {
        'Acc / Dam' : {
            'ltcolor' : (255, 238, 0),
            'dkcolor' : (179, 0, 0),
            'tiers' : ['Keen', 'Tactical', 'Precise', 'Intuition',],
        },
        'Def / Res' : {
            'ltcolor' : (255, 178, 99),
            'dkcolor' : (179, 0, 148),
            'tiers' : ['Shielded', 'Guarded', 'Protected', 'Impenetrable',],
        },
        'End / Heal' : {
            'ltcolor' : (135, 220, 38),
            'dkcolor' : (0, 30, 160),
            'tiers' : ['Revitalize', 'Rejuvenate', 'Invigorate', 'Refresh',],
        }
    },
    'Team' : {
        'Accuracy'     : {
            'ltcolor': (255, 238, 0),
            'dkcolor': (118, 80, 0),
            'tiers': ['Insight Imbuement', 'Keen Insight Imbuement', 'Uncanny Insight Imbuement',],
        },
        'Health'       : {
            'ltcolor': (135, 220, 38),
            'dkcolor': (0, 66, 7),
            'tiers': ['Health Imbuement', 'Greater Health Imbuement', 'Superior Health Imbuement',],
        },
        'Damage'       : {
            'ltcolor': (249, 163, 152),
            'dkcolor': (179, 0, 0),
            'tiers': ['Rage Imbuement', 'Focused Rage Imbuement', 'Righteous Rage Imbuement',],
        },
        'Endurance'    : {
            'ltcolor': (122, 220, 255),
            'dkcolor': (0, 30, 160),
            'tiers': ['Endurance Imbuement', 'Greater Endurance Imbuement', 'Superior Endurance Imbuement',],
        },
        'Defense'      : {
            'ltcolor': (228, 166, 236),
            'dkcolor': (94, 0, 94),
            'tiers': ['Luck Imbuement', 'Good Luck Imbuement', 'Phenomenal Luck Imbuement',],
        },
        'ResistDamage' : {
            'ltcolor': (255, 178, 99),
            'dkcolor': (151, 54, 0),
            'tiers': ['Sturdy Imbuement', 'Rugged Imbuement', 'Robust Imbuement',],
        },
        'BreakFree'    : {
            'ltcolor': (186, 174, 255),
            'dkcolor': (57, 0, 113),
            'tiers': ['Protection Imbuement', 'Greater Protection Imbuement', 'Superior Protection Imbuement',],
        },
    },
    'DualTeam' : {
        'Acc / Dam' : {
            'ltcolor' : (255, 238, 0),
            'dkcolor' : (179, 0, 0),
            'tiers' : ['Tactical Imbuement', 'Precise Imbuement', 'Intuition Imbuement',],
        },
        'Def / Res' : {
            'ltcolor' : (255, 178, 99),
            'dkcolor' : (179, 0, 148),
            'tiers' : ['Guarding Imbuement', 'Protecting Imbuement', 'Impenetrable Imbuement',],
        },
        'End / Heal' : {
            'ltcolor' : (135, 220, 38),
            'dkcolor' : (0, 30, 160),
            'tiers' : ['Rejuvenating Imbuement', 'Invigorating Imbuement', 'Refreshing Imbuement',],
        }
    },
}

DefaultBinds = {
    '\''         : "quickchat",
    '-'          : "prev_tray",
    'ALT+-'      : "prev_tray_alt",
    '/'          : "show chat$$slashchat",
    '0'          : "powexec_slot 10",
    'CTRL+0'     : "powexec_alt2slot 10",
    'ALT+0'      : "powexec_altslot 10",
    '1'          : "powexec_slot 1",
    'CTRL+1'     : "powexec_alt2slot 1",
    'SHIFT+1'    : "team_select 1",
    'ALT+1'      : "powexec_altslot 1",
    '2'          : "powexec_slot 2",
    'CTRL+2'     : "powexec_alt2slot 2",
    'SHIFT+2'    : "team_select 2",
    'ALT+2'      : "powexec_altslot 2",
    '3'          : "powexec_slot 3",
    'CTRL+3'     : "powexec_alt2slot 3",
    'SHIFT+3'    : "team_select 3",
    'ALT+3'      : "powexec_altslot 3",
    '4'          : "powexec_slot 4",
    'CTRL+4'     : "powexec_alt2slot 4",
    'SHIFT+4'    : "team_select 4",
    'ALT+4'      : "powexec_altslot 4",
    '5'          : "powexec_slot 5",
    'CTRL+5'     : "powexec_alt2slot 5",
    'SHIFT+5'    : "team_select 5",
    'ALT+5'      : "powexec_altslot 5",
    '6'          : "powexec_slot 6",
    'CTRL+6'     : "powexec_alt2slot 6",
    'SHIFT+6'    : "team_select 6",
    'ALT+6'      : "powexec_altslot 6",
    '7'          : "powexec_slot 7",
    'CTRL+7'     : "powexec_alt2slot 7",
    'SHIFT+7'    : "team_select 7",
    'ALT+7'      : "powexec_altslot 7",
    '8'          : "powexec_slot 8",
    'CTRL+8'     : "powexec_alt2slot 8",
    'SHIFT+8'    : "team_select 8",
    'ALT+8'      : "powexec_altslot 8",
    '9'          : "powexec_slot 9",
    'CTRL+9'     : "powexec_alt2slot 9",
    'ALT+9'      : "powexec_altslot 9",
    ';'          : "show chat$$slashchat",
    '\\'         : "menu",
    'A'          : "+left",
    'B'          : "++first",
    'BACKSPACE'  : "autoreply",
    'C'          : "chat",
    'COMMA'      : "show chat$$beginchat /tell $target, ",
    'D'          : "+right",
    'DELETE'     : "+lookdown",
    'DOWN'       : "+backward",
    'DOWNARROW'  : "+backward",
    'E'          : "+turnright",
    'END'        : "+zoomout",
    'ENTER'      : "show chat$$startchat",
    'EQUALS'     : "next_tray",
    'ALT+EQUALS' : "next_tray_alt",
    'ESC'        : "unselect",
    'F'          : "follow",
    'F1'         : "inspexec_slot 1",
    'F10'        : "say $battlecry $$ emote attack",
    'F2'         : "inspexec_slot 2",
    'F3'         : "inspexec_slot 3",
    'F4'         : "inspexec_slot 4",
    'F5'         : "inspexec_slot 5",
    'F6'         : "local <color white><bgcolor red>RUN!",
    'F7'         : "say <color black><bgcolor #22aa22>Ready! $$ emote thumbsup",
    'F8'         : "local <color black><bgcolor #aaaa22>HELP! $$ emote whistle",
    'F9'         : "local <color white><bgcolor #2222aa><scale .75>level $level $archetype$$local <color white><bgcolor #2222aa>Looking for team",
    'HOME'       : "+zoomin",
    'INSERT'     : "+lookup",
    'LALT'       : "+alttray",
    'LCONTROL'   : "+alt2tray",
    'LCTRL'      : "+alt2tray",
    'LEFT'       : "+turnleft",
    'LEFTARROW'  : "+turnleft",
    'M'          : "map",
    'MBUTTON'    : "+camrotate",
    'MouseChord' : "+forward_mouse",
    'MOUSEWHEEL' : "+camdistadjust",
    'N'          : "nav",
    'P'          : "powers",
    'PAGEDOWN'   : "camreset",
    'PAGEUP'     : "+camrotate",
    'Q'          : "+turnleft",
    'R'          : "++autorun",
    'RALT'       : "alttraysticky",
    'RBUTTON'    : "+mouse_look",
    'RIGHT'      : "+turnright",
    'RIGHTARROW' : "+turnright",
    'S'          : "+backward",
    'SPACE'      : "+up",
    'SYSRQ'      : "screenshot",
    'T'          : "target",
    'TAB'        : "target_enemy_next",
    'CTRL+TAB'   : "target_enemy_near",
    'SHIFT+TAB'  : "target_enemy_prev",
    'UP'         : "+forward",
    'UPARROW'    : "+forward",
    'V'          : "+ctm_invert",
    'W'          : "+forward",
    'X'          : "+down",
    'Z'          : "powexec_abort",
}

Emotes = {
    'emotes': [
        { 'Converse' : [
            { 'Greetings' : [
                'Hi%em wave$$local Hi!',
                'Hello <$target>%em wave$$local Hello, $target',
                'Introduce <self>%em wave$$local Pleased to meet you! I am $name, a level $level $origin $archetype.',
                'Looking for Team%local level $level $archetype$$local Looking for team.',
                'Welcome%em welcome$$local Welcome!',
            ] },
            { 'Combat   ' : [
                'On my mark...%em stop$$local On my mark...',
                'ATTACK!%em attack$$local ATTACK!',
                'Don\'t attack!%em no$$local Don\'t attack!',
                'Stop!%em stop$$local Stop!',
                'Come get some!%em taunt1$$local Come get some!',
            ] },
            { 'Travel'    : [
                'Lead On!%em thumbsup$$local Lead On!',
                'Onward!%em points$$local Onward!',
                'Follow me!%em point$$local Follow me!',
                'Stop!%em stop$$local Stop!',
                'Wait Here%em stop$$local Wait here.',
                'Let\'s go!%em thumbsup$$local Let\'s go!',
                'On my way%local On my way.',
                'Over here!%em bigwave%%local Over here!',
                'Where to?%em shrug$$local Where to?',
                'Ready?%local Ready?',
                'Get a mission?%local Get a mission?',
            ] },
            { 'Speech'    : [
                'Yes%em thumbsup$$local Yes',
                'Yes sir!%em salute$$local Yes sir!',
                'No%em no$$No',
                'Huh?%em shrug$$local Huh?'
                'Good job!%em thumbsup$$Good job!',
                'Sorry%em bow$$local Sorry',
                'Thank You%em thanks$$local Thank You',
                'You\'re Welcome%em yourewelcome$$local You\'re Welcome',
                'No Problem%em thumbsup$$No Problem',
                'Grrrrrrrr!%em beatchest$$local Grrrrrrrr!',
                'Arrrrggggh!%em frustrated$$local Arrrrggggh!',
                'Excellent!%em clap$$local Excellent!',
                'Mua Ha Ha Ha!%em evillaugh$$local Mua ha ha ha!',
            ] },
            '---',
            'Chat|Talk', 'Lecture', 'Explain',
            '---',
            'Nod', 'Thumbs Up|yes', 'Shrug|huh', 'Thanks', 'Welcome', 'You\'re Welcome|YoureWelcome',
            '---',
            'Disagree|no', 'Shake Head|No', 'Yada Yada Yada|Yata', 'Talk to the Hand|TalkToHand',
        ]},
        { 'Interact' : [
            'Salute', 'Military Salute', 'Praetorian Salute', 'At Ease',
            '---',
            'Bow', 'Fancy Bow', 'Clap', 'Praise', 'Camera',
            '---',
            'You bow down!|bowdown', 'Surrender', 'Get Some', 'Go Away', 'Taunt 1', 'Taunt 2',
            'Chicken', 'Slash Throat', 'Bring it!', 'Threaten|threathand', 'Hands Up', 'Smack',
            'Slap', 'Slap React', 'Alakazam!', 'Alakazam! React', 'Bat Smash',
            'Bat Smash React', 'Ultimate Power', 'Facepalm', 'Double Facepalm',
            'Casting', 'Channel',
            '---',
            { 'Judge' : [
                'Score 1', 'Score 2', 'Score 3', 'Score 4', 'Score 5',
                'Score 6', 'Score 7', 'Score 8', 'Score 9', 'Score 10',
            ] },
            { 'Decide' : [
                'Coin Toss|coin', 'Roll Dice|dice', 'Observe Dice', 'High Roller|dice7',
                '---',
                'Rock', 'Paper', 'Scissors',
            ] },
            { 'Environment' : [
                'Peer In', 'Touch Screen|screen', 'Type', 'Research', 'Research Low',  'Dig',
                'Jackhammer', 'Spraypaint', 'Warm Hands', 'Pick Lock', 'Throw Snowflakes|snowflakes',
                '---',
                'Sit Chair 1', 'Sit Chair 2', 'Sit Chair 3', 'Sit Bench 1', 'Sit Bench 2',
                'Sit Bench 3', 'Sit Bench 4', 'Sit Executive Chair', 'Sit Stool',
                'Sit Table 1', 'Sit Table 2', 'Sit Ledge|ledgesit',
                '---',
                'Wall Lean', 'Assume the Position|assumepositionwall',
            ]},
        ]},
        { 'Actions'  : [
            'Wave', 'Big Wave', 'Raise Hand', 'Point', 'Attack',
            '---',
            'Cheer', 'Wave Fist', 'Crack Knuckles|crack', 'Whistle', 'Victory', 'Winner', 'The Wave',
            '---',
            'Angry', 'Frustrated', 'Curse You', 'Roar', 'Howl', 'Tarzan', 'Growl', 'Show Off',
            '---',
            'Dust Off', 'Read Book', 'Burp',
            '---',
            'Laughs|laugh', 'Giggle|laugh2', 'Drat', 'Shucks', 'Grief', 'Flipping Coin',
            'Open Gift', 'Ghoul Flex', 'Tantrum', 'Collapse', 'Swoon', 'Defeated',
            '---',
            { 'Athletics' : [
                'Backflip', 'Flex 1', 'Flex 2', 'Flex 3', 'Jumping Jacks', 'Kata', 'Pushups|Pushup',
            ] },
            { 'Wedding' : [
                'Propose', 'Throw Rice', 'Throw Confetti', 'Throw Rose Petals',
            ] },
            { 'Animal': [
                'Hiss', 'Sniff', 'Savage',
            ] },
            { 'Holiday' : [
                'Offer Gift', 'Receive Gift', 'Throw Snowflakes|snowflakes', 'Fireworks - Rocket Flare|FireworkRocket',
                'Fireworks - Bloom|FireworkBloom', 'Fireworks - Sparkle|FireworkSparkle',
            ] },
            { 'Steam Punk': [
                'Inspiration', 'Hot Temper', 'Train Whistle',
            ]},
        ]},
        { 'Idle'     : [
            'Afraid', 'Fish|fishing', 'Binoculars', 'Flashlight', 'Flashlight (Up)', 'Flashlight (Down)', 'Clipboard',
            'Invent', 'Panhandle', 'Stunned|wounded', 'Plotting|plot', 'Floating Books|floatbooks',
            'Pamphlet', 'Vendor', 'Protest', 'Listen to Policeband|ListenPoliceBand',
            'Protest Loyalists|protestloyalist', 'Protest Resistance',
            '---',
            'Robot Power Up|powerup', 'Robot Power Down|powerdown',
            'Listen to Stolen Policeband|ListenStolenPoliceBand', 'Tablet Write|matablet',
            'Calculate Theories|calculate', 'Mix Formula', 'Talk Pool|pool', 'Soccer Kick|soccer',
            'Basketball Dribble|basketball', 'Catch Breath',
            '---',
            { 'Food and Drink' : [
                'Eat Food', 'Eat Donut', 'Eat Hotdog|hotdog', 'Eat Hamburger|hamburger', 'Eat Jumbo Hotdog|jumbohotdog',
                'Eat Pocket Dog|pocketdog', 'Eat Watermelon|watermelon', 'Eat Onigiri|onigiri', 'Drink',  'Drink Tea|teabag', 'Drink Enriche',
                { 'Drenched Donuts' :
                    [ 'Eat Strawberry Donut|Donut1', 'Eat Chocolate Donut|Donut2', 'Eat Sprinkled Donut|Donut3',
                     'Eat Plain Donut|Donut4', 'Eat Blue Sky Donut|Donut5', 'Eat Winter Donut|WinterDonut',
                     'Eat Spooky Donut|SpookyDonut', 'Eat Jelly Donut|jellydonut', 'Eat Lemon Donut|lemondonut',
                     'Drink DD Coffee|DDCoffee', 'Drink DD Coffee 2|DDCoffee2' ],
                 },
                { 'Collectible Mugs' :
                    [ 'Arachnos Mug', 'Paragon Mug', 'Winter Mug', 'Pumpkin Mug', ],
                 },
            ]},
            { 'Away' : [
                { 'Phone' :
                    [ 'Smartphone 1', 'Smartphone 2', 'Cellphone', 'Text 1', 'Text 2', 'Camera Phone 1', 'Camera Phone 2', ],
                 },
                'Crouch',
                { 'Kneel' : [ 'kneel', 'kneel2', 'kneel3', 'kneel4', 'kneel5'] },
                'Use Laptop|laptop', 'Lotus', 'Read Newspaper|newspaper',
                'AFK Sleep|sleep', 'Sit on Ground|sit', 'Wait|waiting',
            ]},
            { 'Evil' : [
                'Hold Bat|batlookout', 'Evil Laugh', 'Hold Torch', 'Scheme',
            ]},
            { 'Magic': [
                'Card Trick', 'Juggle', 'Juggle Magic', 'Juggle Fire', 'Juggle Electricity',
            ]},
            { 'Stances' : [
                'Center Stance|idle2', 'Cross Arms', 'Hands on Hips|akimbo', 'Neutral Stance|idle1',
                'Hero Stance 1|stancehero1', 'Hero Stance 2|stancehero2',
                'Villain Stance 1|stancevillain1', 'Villain Stance 2|stancevillain2',
            ]},
            { 'Swimming' : [
                { 'Innertube' : [
                    'Random|Innertube', 'Strawberry Donut|Innertube1', 'Chocolate Donut|Innertube2',
                    'Neon Sport|Innertube3', 'Moo!|Innertube4', 'Naval Academy|Innertube5', 'Lifeguard|Innertube6',
                ]}
            ]},
            { 'Loyalty': [
                'Hero Loyal', 'Vigilante Loyal', 'Villain Loyal', 'Rogue Loyal',
            ]},
        ]},
        { 'Music'    : [
            'Boombox',
            { 'Tracklist': [
                'Track - Altitude|BBAltitude',
                'Track - Beat|BBBeat',
                'Track - Catch Me|BBCatchMe',
                'Track - Dance|BBDance',
                'Track - ElectroVibe|BBElectroVibe',
                'Track - Disco Freak|BBDiscoFreak',
                'Track - Dog Walk|BBDogWalk',
                'Track - Heavy Dude|BBHeavyDude',
                'Track - Info Overload|BBInfoOverload',
                'Track - Jumpy|BBJumpy',
                'Track - Kick It|BBKickIt',
                'Track - Looker|BBLooker',
                'Track - Meaty|BBMeaty',
                'Track - Notorious|BBNotorious',
                'Track - Move On|BBMoveOn',
                'Track - Peace|BBPeace',
                'Track - Quickie|BBQuickie',
                'Track - Raver|BBRaver',
                'Track - Shuffle|BBShuffle',
                'Track - Technoid|BBTechnoid',
                'Track - Wind It Up|BBWindItUp',
                'Track - Venus|BBVenus',
                'Track - Wah Wah|BBWahWah',
                'Track - Yellow|BBYellow',
                'Track - Spaz|BBSpaz',
            ] },
            '---',
            'Dance', 'Shuffle|dance1', 'Rock It|dance2', 'The Washer|dance3', 'Raise the Roof|dance4',
            'Bounce|dance5', 'The Monkey|dance6', 'Drum Dance|drum', 'Robot Dance', 'Karate Dance',
            'Pop Dance', 'Air Guitar', 'Disco Dance',
            '---',
            'Big Drum|drum', 'Small Drum|drumlow',
        ] },
    ],
    'costumechange' : [
        'Backflip',
        'Cast',
        'Confetti Throw',
        'Dimension Shift',
        'Drink Formula',
        'Energy Morph',
        'Evil Laugh',
        'Feather Burst',
        'Feather Spin',
        'Fireworks',
        'Fur Burst',
        'Fur Spin',
        'Gift Burst',
        'Howl',
        'Ice Block',
        'Inner Will',
        'Light Magic',
        'Lightning',
        'Murder Of Crows',
        'Ninja Leap',
        'Nuke',
        'Oil Strike',
        'Peacebringer',
        'Pressure Release',
        'Presto Chango',
        'Pure Energy',
        'Rainbow',
        'Rapid Boil',
        'Salute',
        'Smoke Bomb',
        'Spin',
        'Stone Block',
        'Super Serum',
        'Vanguard Sigil',
        'Warshade',
    ],
}



# TODO -- these emotes seem not to be in the in-game picker, but are in the game.  Filter them into the structure above.
'''
            'Cameraphone',
            'Despair',
            'Dice7',
            'Flypose1',
            'Flypose2',
            'Flypose3',
            'Flypose4',
            'JellyDonut2',
            'Hi',
            'Hmmm',
            'Liedown',
            'Lookup',
            'None',
            'Shocked',
            'Slrcamera',
            'Smartphone',
            'Text',
            'WalkieTalkie',
'''
